'use strict';

// Namkaran Sanskar — 27 Nakshatras × 4 Padas = 108 Phonetic Sounds
// Source: Brihat Parashara Hora Shastra + South Indian Panchang tradition
// Each pada has: en (English), hi (Devanagari), sound (pronunciation guide)

const NAKSHATRA_DATA = [
  {
    name: 'Ashwini',     nameHi: 'अश्विनी',
    lord: 'Ketu',        lordHi: 'केतु',
    deity: 'Ashwini Kumars', deityHi: 'अश्विनी कुमार',
    element: 'Fire',     elementHi: 'अग्नि',
    gana: 'Deva',        ganaHi: 'देव',
    symbol: 'Horse Head',
    pada: [
      { en: 'Chu', hi: 'चू', sound: 'ch as in "choose"' },
      { en: 'Che', hi: 'चे', sound: 'ch as in "chess"' },
      { en: 'Cho', hi: 'चो', sound: 'ch as in "chore"' },
      { en: 'La',  hi: 'ला', sound: 'la as in "la-la"' },
    ],
  },
  {
    name: 'Bharani',     nameHi: 'भरणी',
    lord: 'Venus',       lordHi: 'शुक्र',
    deity: 'Yama',       deityHi: 'यम',
    element: 'Earth',    elementHi: 'पृथ्वी',
    gana: 'Manushya',    ganaHi: 'मनुष्य',
    symbol: 'Yoni',
    pada: [
      { en: 'Li', hi: 'ली', sound: 'li as in "lean"' },
      { en: 'Lu', hi: 'लू', sound: 'lu as in "loop"' },
      { en: 'Le', hi: 'ले', sound: 'le as in "late"' },
      { en: 'Lo', hi: 'लो', sound: 'lo as in "low"' },
    ],
  },
  {
    name: 'Krittika',    nameHi: 'कृत्तिका',
    lord: 'Sun',         lordHi: 'सूर्य',
    deity: 'Agni',       deityHi: 'अग्नि',
    element: 'Fire',     elementHi: 'अग्नि',
    gana: 'Rakshasa',    ganaHi: 'राक्षस',
    symbol: 'Flame',
    pada: [
      { en: 'A',  hi: 'अ',  sound: 'a as in "art"' },
      { en: 'I',  hi: 'इ',  sound: 'i as in "it"' },
      { en: 'U',  hi: 'उ',  sound: 'u as in "put"' },
      { en: 'E',  hi: 'ए',  sound: 'e as in "eight"' },
    ],
  },
  {
    name: 'Rohini',      nameHi: 'रोहिणी',
    lord: 'Moon',        lordHi: 'चन्द्र',
    deity: 'Brahma',     deityHi: 'ब्रह्मा',
    element: 'Earth',    elementHi: 'पृथ्वी',
    gana: 'Manushya',    ganaHi: 'मनुष्य',
    symbol: 'Cart / Chariot',
    pada: [
      { en: 'O',  hi: 'ओ',  sound: 'o as in "open"' },
      { en: 'Va', hi: 'वा', sound: 'va as in "vast"' },
      { en: 'Vi', hi: 'वि', sound: 'vi as in "victory"' },
      { en: 'Vu', hi: 'वु', sound: 'vu as in "voodoo"' },
    ],
  },
  {
    name: 'Mrigashira',  nameHi: 'मृगशिरा',
    lord: 'Mars',        lordHi: 'मंगल',
    deity: 'Soma',       deityHi: 'सोम',
    element: 'Air',      elementHi: 'वायु',
    gana: 'Deva',        ganaHi: 'देव',
    symbol: 'Deer Head',
    pada: [
      { en: 'Ve', hi: 'वे', sound: 've as in "veil"' },
      { en: 'Vo', hi: 'वो', sound: 'vo as in "vote"' },
      { en: 'Ka', hi: 'का', sound: 'ka as in "calm"' },
      { en: 'Ki', hi: 'कि', sound: 'ki as in "keen"' },
    ],
  },
  {
    name: 'Ardra',       nameHi: 'आर्द्रा',
    lord: 'Rahu',        lordHi: 'राहु',
    deity: 'Rudra',      deityHi: 'रुद्र',
    element: 'Water',    elementHi: 'जल',
    gana: 'Manushya',    ganaHi: 'मनुष्य',
    symbol: 'Teardrop',
    pada: [
      { en: 'Ku',  hi: 'कु',  sound: 'ku as in "cool"' },
      { en: 'Gha', hi: 'घ',   sound: 'gha as in "Ghana"' },
      { en: 'Ing', hi: 'ञ',   sound: 'ng as in "singing"' },
      { en: 'Cha', hi: 'छ',   sound: 'chh as in "chhat"' },
    ],
  },
  {
    name: 'Punarvasu',   nameHi: 'पुनर्वसु',
    lord: 'Jupiter',     lordHi: 'गुरु',
    deity: 'Aditi',      deityHi: 'अदिति',
    element: 'Water',    elementHi: 'जल',
    gana: 'Deva',        ganaHi: 'देव',
    symbol: 'Bow & Quiver',
    pada: [
      { en: 'Ke', hi: 'के', sound: 'ke as in "key"' },
      { en: 'Ko', hi: 'को', sound: 'ko as in "coat"' },
      { en: 'Ha', hi: 'हा', sound: 'ha as in "heart"' },
      { en: 'Hi', hi: 'हि', sound: 'hi as in "heat"' },
    ],
  },
  {
    name: 'Pushya',      nameHi: 'पुष्य',
    lord: 'Saturn',      lordHi: 'शनि',
    deity: 'Brihaspati', deityHi: 'बृहस्पति',
    element: 'Water',    elementHi: 'जल',
    gana: 'Deva',        ganaHi: 'देव',
    symbol: 'Lotus / Cow Udder',
    pada: [
      { en: 'Hu', hi: 'हु', sound: 'hu as in "hoop"' },
      { en: 'He', hi: 'हे', sound: 'he as in "hey"' },
      { en: 'Ho', hi: 'हो', sound: 'ho as in "home"' },
      { en: 'Da', hi: 'ड',  sound: 'da as in "drum"' },
    ],
  },
  {
    name: 'Ashlesha',    nameHi: 'आश्लेषा',
    lord: 'Mercury',     lordHi: 'बुध',
    deity: 'Naga',       deityHi: 'नाग',
    element: 'Water',    elementHi: 'जल',
    gana: 'Rakshasa',    ganaHi: 'राक्षस',
    symbol: 'Coiled Serpent',
    pada: [
      { en: 'Di', hi: 'डि', sound: 'di as in "din"' },
      { en: 'Du', hi: 'डु', sound: 'du as in "dune"' },
      { en: 'De', hi: 'डे', sound: 'de as in "day"' },
      { en: 'Do', hi: 'डो', sound: 'do as in "dote"' },
    ],
  },
  {
    name: 'Magha',       nameHi: 'मघा',
    lord: 'Ketu',        lordHi: 'केतु',
    deity: 'Pitrs',      deityHi: 'पितृ',
    element: 'Fire',     elementHi: 'अग्नि',
    gana: 'Rakshasa',    ganaHi: 'राक्षस',
    symbol: 'Throne Room',
    pada: [
      { en: 'Ma', hi: 'मा', sound: 'ma as in "mama"' },
      { en: 'Mi', hi: 'मि', sound: 'mi as in "meet"' },
      { en: 'Mu', hi: 'मु', sound: 'mu as in "moon"' },
      { en: 'Me', hi: 'मे', sound: 'me as in "made"' },
    ],
  },
  {
    name: 'PurvaPhalguni',  nameHi: 'पूर्वाफाल्गुनी',
    lord: 'Venus',          lordHi: 'शुक्र',
    deity: 'Bhaga',         deityHi: 'भग',
    element: 'Fire',        elementHi: 'अग्नि',
    gana: 'Manushya',       ganaHi: 'मनुष्य',
    symbol: 'Hammock',
    pada: [
      { en: 'Mo', hi: 'मो', sound: 'mo as in "more"' },
      { en: 'Ta', hi: 'ट',  sound: 'ta as in "tub" (retroflex)' },
      { en: 'Ti', hi: 'टि', sound: 'ti as in "tin" (retroflex)' },
      { en: 'Tu', hi: 'टु', sound: 'tu as in "tool" (retroflex)' },
    ],
  },
  {
    name: 'UttaraPhalguni', nameHi: 'उत्तराफाल्गुनी',
    lord: 'Sun',            lordHi: 'सूर्य',
    deity: 'Aryaman',       deityHi: 'अर्यमन',
    element: 'Fire',        elementHi: 'अग्नि',
    gana: 'Manushya',       ganaHi: 'मनुष्य',
    symbol: 'Bed',
    pada: [
      { en: 'Te', hi: 'टे', sound: 'te as in "tape" (retroflex)' },
      { en: 'To', hi: 'टो', sound: 'to as in "tone" (retroflex)' },
      { en: 'Pa', hi: 'पा', sound: 'pa as in "park"' },
      { en: 'Pi', hi: 'पि', sound: 'pi as in "peak"' },
    ],
  },
  {
    name: 'Hasta',       nameHi: 'हस्त',
    lord: 'Moon',        lordHi: 'चन्द्र',
    deity: 'Savitar',    deityHi: 'सवितर',
    element: 'Fire',     elementHi: 'अग्नि',
    gana: 'Deva',        ganaHi: 'देव',
    symbol: 'Hand / Fist',
    pada: [
      { en: 'Pu',  hi: 'पु',  sound: 'pu as in "pool"' },
      { en: 'Sha', hi: 'ष',   sound: 'sh as in "shut" (retroflex)' },
      { en: 'Na',  hi: 'ण',   sound: 'na as in "name" (retroflex)' },
      { en: 'Tha', hi: 'ठ',   sound: 'tha (retroflex aspirated)' },
    ],
  },
  {
    name: 'Chitra',      nameHi: 'चित्रा',
    lord: 'Mars',        lordHi: 'मंगल',
    deity: 'Vishvakarma',deityHi: 'विश्वकर्मा',
    element: 'Air',      elementHi: 'वायु',
    gana: 'Rakshasa',    ganaHi: 'राक्षस',
    symbol: 'Pearl / Bright Jewel',
    pada: [
      { en: 'Pe', hi: 'पे', sound: 'pe as in "pay"' },
      { en: 'Po', hi: 'पो', sound: 'po as in "pole"' },
      { en: 'Ra', hi: 'र',  sound: 'ra as in "run"' },
      { en: 'Ri', hi: 'रि', sound: 'ri as in "ring"' },
    ],
  },
  {
    name: 'Swati',       nameHi: 'स्वाति',
    lord: 'Rahu',        lordHi: 'राहु',
    deity: 'Vayu',       deityHi: 'वायु',
    element: 'Air',      elementHi: 'वायु',
    gana: 'Deva',        ganaHi: 'देव',
    symbol: 'Sword / Coral',
    pada: [
      { en: 'Ru', hi: 'रु', sound: 'ru as in "rude"' },
      { en: 'Re', hi: 'रे', sound: 're as in "ray"' },
      { en: 'Ro', hi: 'रो', sound: 'ro as in "road"' },
      { en: 'Ta', hi: 'त',  sound: 'ta as in "task"' },
    ],
  },
  {
    name: 'Vishakha',    nameHi: 'विशाखा',
    lord: 'Jupiter',     lordHi: 'गुरु',
    deity: 'Indra-Agni', deityHi: 'इन्द्राग्नि',
    element: 'Fire',     elementHi: 'अग्नि',
    gana: 'Rakshasa',    ganaHi: 'राक्षस',
    symbol: 'Triumphal Arch',
    pada: [
      { en: 'Ti', hi: 'ति', sound: 'ti as in "till"' },
      { en: 'Tu', hi: 'तु', sound: 'tu as in "too"' },
      { en: 'Te', hi: 'ते', sound: 'te as in "take"' },
      { en: 'To', hi: 'तो', sound: 'to as in "tone"' },
    ],
  },
  {
    name: 'Anuradha',    nameHi: 'अनुराधा',
    lord: 'Saturn',      lordHi: 'शनि',
    deity: 'Mitra',      deityHi: 'मित्र',
    element: 'Water',    elementHi: 'जल',
    gana: 'Deva',        ganaHi: 'देव',
    symbol: 'Lotus',
    pada: [
      { en: 'Na', hi: 'न',  sound: 'na as in "name"' },
      { en: 'Ni', hi: 'नि', sound: 'ni as in "knee"' },
      { en: 'Nu', hi: 'नु', sound: 'nu as in "new"' },
      { en: 'Ne', hi: 'ने', sound: 'ne as in "nest"' },
    ],
  },
  {
    name: 'Jyeshtha',    nameHi: 'ज्येष्ठा',
    lord: 'Mercury',     lordHi: 'बुध',
    deity: 'Indra',      deityHi: 'इन्द्र',
    element: 'Air',      elementHi: 'वायु',
    gana: 'Rakshasa',    ganaHi: 'राक्षस',
    symbol: 'Circular Amulet',
    pada: [
      { en: 'No', hi: 'नो', sound: 'no as in "note"' },
      { en: 'Ya', hi: 'य',  sound: 'ya as in "yarn"' },
      { en: 'Yi', hi: 'यि', sound: 'yi as in "yield"' },
      { en: 'Yu', hi: 'यु', sound: 'yu as in "youth"' },
    ],
  },
  {
    name: 'Mula',        nameHi: 'मूल',
    lord: 'Ketu',        lordHi: 'केतु',
    deity: 'Nirriti',    deityHi: 'निर्ऋति',
    element: 'Fire',     elementHi: 'अग्नि',
    gana: 'Rakshasa',    ganaHi: 'राक्षस',
    symbol: 'Bunch of Roots',
    pada: [
      { en: 'Ye',  hi: 'ये',  sound: 'ye as in "yet"' },
      { en: 'Yo',  hi: 'यो',  sound: 'yo as in "yoga"' },
      { en: 'Bha', hi: 'भ',   sound: 'bha as in "bhajan"' },
      { en: 'Bhi', hi: 'भि',  sound: 'bhi as in "bhim"' },
    ],
  },
  {
    name: 'PurvaAshadha', nameHi: 'पूर्वाषाढ़ा',
    lord: 'Venus',         lordHi: 'शुक्र',
    deity: 'Apas',         deityHi: 'अप (जल देवी)',
    element: 'Air',        elementHi: 'वायु',
    gana: 'Manushya',      ganaHi: 'मनुष्य',
    symbol: 'Fan / Winnowing Basket',
    pada: [
      { en: 'Bhu', hi: 'भु', sound: 'bhu as in "bhumi"' },
      { en: 'Dha', hi: 'ध',  sound: 'dha as in "dharma"' },
      { en: 'Pha', hi: 'फ',  sound: 'pha as in "phase"' },
      { en: 'Dha', hi: 'ढ',  sound: 'dha (retroflex aspirated)' },
    ],
  },
  {
    name: 'UttaraAshadha', nameHi: 'उत्तराषाढ़ा',
    lord: 'Sun',            lordHi: 'सूर्य',
    deity: 'Vishvadevas',   deityHi: 'विश्वदेव',
    element: 'Fire',        elementHi: 'अग्नि',
    gana: 'Manushya',       ganaHi: 'मनुष्य',
    symbol: 'Elephant Tusk',
    pada: [
      { en: 'Bhe', hi: 'भे', sound: 'bhe as in "they" with bh' },
      { en: 'Bho', hi: 'भो', sound: 'bho as in "below"' },
      { en: 'Ja',  hi: 'ज',  sound: 'ja as in "jar"' },
      { en: 'Ji',  hi: 'जि', sound: 'ji as in "jeer"' },
    ],
  },
  {
    name: 'Shravana',    nameHi: 'श्रवण',
    lord: 'Moon',        lordHi: 'चन्द्र',
    deity: 'Vishnu',     deityHi: 'विष्णु',
    element: 'Air',      elementHi: 'वायु',
    gana: 'Deva',        ganaHi: 'देव',
    symbol: 'Three Footprints / Ear',
    pada: [
      { en: 'Ju', hi: 'जु', sound: 'ju as in "juice"' },
      { en: 'Je', hi: 'जे', sound: 'je as in "jest"' },
      { en: 'Jo', hi: 'जो', sound: 'jo as in "joke"' },
      { en: 'Gha',hi: 'घा', sound: 'gha as in "Ghana"' },
    ],
  },
  {
    name: 'Dhanishtha',  nameHi: 'धनिष्ठा',
    lord: 'Mars',        lordHi: 'मंगल',
    deity: 'Ashta Vasus',deityHi: 'अष्ट वसु',
    element: 'Air',      elementHi: 'वायु',
    gana: 'Rakshasa',    ganaHi: 'राक्षस',
    symbol: 'Drum / Flute',
    pada: [
      { en: 'Ga', hi: 'ग',  sound: 'ga as in "garden"' },
      { en: 'Gi', hi: 'गि', sound: 'gi as in "give"' },
      { en: 'Gu', hi: 'गु', sound: 'gu as in "guru"' },
      { en: 'Ge', hi: 'गे', sound: 'ge as in "game"' },
    ],
  },
  {
    name: 'Shatabhisha', nameHi: 'शतभिषा',
    lord: 'Rahu',        lordHi: 'राहु',
    deity: 'Varuna',     deityHi: 'वरुण',
    element: 'Air',      elementHi: 'वायु',
    gana: 'Rakshasa',    ganaHi: 'राक्षस',
    symbol: 'Empty Circle',
    pada: [
      { en: 'Go', hi: 'गो', sound: 'go as in "goal"' },
      { en: 'Sa', hi: 'स',  sound: 'sa as in "sun"' },
      { en: 'Si', hi: 'सि', sound: 'si as in "seen"' },
      { en: 'Su', hi: 'सु', sound: 'su as in "soon"' },
    ],
  },
  {
    name: 'PurvaBhadrapada', nameHi: 'पूर्वाभाद्रपद',
    lord: 'Jupiter',         lordHi: 'गुरु',
    deity: 'Aja Ekapad',     deityHi: 'अज एकपाद',
    element: 'Air',          elementHi: 'वायु',
    gana: 'Manushya',        ganaHi: 'मनुष्य',
    symbol: 'Sword / Two Front Legs of Funeral Cot',
    pada: [
      { en: 'Se', hi: 'से', sound: 'se as in "set"' },
      { en: 'So', hi: 'सो', sound: 'so as in "soul"' },
      { en: 'Da', hi: 'द',  sound: 'da as in "day"' },
      { en: 'Di', hi: 'दि', sound: 'di as in "dim"' },
    ],
  },
  {
    name: 'UttaraBhadrapada', nameHi: 'उत्तराभाद्रपद',
    lord: 'Saturn',           lordHi: 'शनि',
    deity: 'Ahir Bhudhanya',  deityHi: 'अहिर्बुध्न्य',
    element: 'Air',           elementHi: 'वायु',
    gana: 'Manushya',         ganaHi: 'मनुष्य',
    symbol: 'Two Rear Legs of Funeral Cot',
    pada: [
      { en: 'Du',  hi: 'दु', sound: 'du as in "duel"' },
      { en: 'Tha', hi: 'थ',  sound: 'tha as in "thin"' },
      { en: 'Jha', hi: 'झ',  sound: 'jha as in "jheel"' },
      { en: 'Da',  hi: 'ञ',  sound: 'na (palatal nasal)' },
    ],
  },
  {
    name: 'Revati',      nameHi: 'रेवती',
    lord: 'Mercury',     lordHi: 'बुध',
    deity: 'Pushan',     deityHi: 'पूषन',
    element: 'Water',    elementHi: 'जल',
    gana: 'Deva',        ganaHi: 'देव',
    symbol: 'Fish / Drum',
    pada: [
      { en: 'De',  hi: 'दे', sound: 'de as in "deal"' },
      { en: 'Do',  hi: 'दो', sound: 'do as in "dome"' },
      { en: 'Cha', hi: 'च',  sound: 'cha as in "chart"' },
      { en: 'Chi', hi: 'चि', sound: 'chi as in "chip"' },
    ],
  },
];

// Map nakshatra name (as stored in DB) → index
const NAK_INDEX = {};
NAKSHATRA_DATA.forEach((n, i) => { NAK_INDEX[n.name] = i; });

function getNamkaranLetter(nakshatra, pada) {
  const idx = NAK_INDEX[nakshatra];
  if (idx === undefined) return null;
  const nak = NAKSHATRA_DATA[idx];
  const padaIdx = (parseInt(pada) || 1) - 1;
  const letter = nak.pada[padaIdx] || nak.pada[0];
  return {
    nakshatra: nak.name,
    nakshatraHi: nak.nameHi,
    lord: nak.lord,
    lordHi: nak.lordHi,
    deity: nak.deity,
    deityHi: nak.deityHi,
    element: nak.element,
    elementHi: nak.elementHi,
    gana: nak.gana,
    ganaHi: nak.ganaHi,
    symbol: nak.symbol,
    pada: parseInt(pada) || 1,
    letter,           // { en, hi, sound }
    allPadas: nak.pada,
  };
}

module.exports = { NAKSHATRA_DATA, getNamkaranLetter };
