'use strict';

// English content for the 10 life-area detailed life forecast section

// ─── LAGNA LIFE DOMAINS (English) ─────────────────────────────────────────────
const LAGNA_LIFE_EN = {
  Aries: {
    charitra:     'Your character is courageous, direct, and transparent — what you think, you say. A natural pioneer, you earn trust through bold action and fearless honesty rather than diplomacy.',
    vivah:        'Marriage calls for a spirited, independent partner who matches your energy and respects your autonomy. Ego clashes are possible; mutual respect and personal space create lasting harmony.',
    jeevan_shaili:'Your lifestyle thrives on movement, challenge, and novelty. Static routines drain you — fresh goals and competitive environments keep you emotionally alive.',
    rozgar:       'Leadership roles with independent decision-making suit you best. Government service, defence, engineering, and entrepreneurship align with your Mars-ruled drive.',
    vyavsay:      'Surgery, engineering, military, police, sports coaching, and real-estate construction are ideal. You excel wherever decisive action under pressure is the job requirement.',
    swasthya:     'Head, brain, and eyes are your sensitive areas. Manage anger consciously — hypertension and migraines arise from suppressed frustration. Vigorous daily exercise is your most effective medicine.',
    ruchi:        'Adventure sports, competitive games, trekking, martial arts, and motorsport are your natural recreations. Physical outlets convert Mars energy into achievement.',
    prem:         'In love you are passionate, direct, and all-in from the start. You need a partner who values transparency and does not require emotional games or strategic mystery.',
    vitta:        'You earn boldly and spend impulsively. Real estate and equity markets attract you; cultivating savings discipline balances your natural risk appetite.',
    shiksha:      'Engineering, medicine, sports science, and defence studies are your ideal fields. Hands-on, competitive learning brings out your full intellectual potential.',
  },
  Taurus: {
    charitra:     'Steady, loyal, and profoundly reliable — your word is your bond. Once committed to a person or cause, you stay regardless of difficulty; this constancy is your most trusted quality.',
    vivah:        'You seek a stable, sensually attuned partner who values comfort and security as much as you do. Patient in courtship, you are devoted for life once fully committed.',
    jeevan_shaili:'A comfortable home, fine food, good music, and reliable routines form the foundation of your contentment. Change is accepted slowly — you build for permanence.',
    rozgar:       'Banking, finance, agriculture, hospitality, real estate, and creative arts suit your patient, Venus-ruled temperament. You shine in roles requiring sustained effort over time.',
    vyavsay:      'Interior design, music, culinary arts, jewelry, land management, and financial consulting are ideal businesses. Sensory excellence and steady returns define your professional identity.',
    swasthya:     'Throat, thyroid, and digestive system require attention. Comfort eating and a sedentary lifestyle can cause weight and metabolic issues — disciplined diet and daily walks are your medicine.',
    ruchi:        'Music, gardening, gourmet cooking, art collecting, and crafts fill your leisure with deep satisfaction. Nature and beautiful objects restore you completely.',
    prem:         'You love slowly but completely — physical affection, gifts, and steady nurturing are your love language. Once in love, you are unwavering and profoundly loyal.',
    vitta:        'You are a natural wealth accumulator — disciplined, long-term, and prudent. Land, gold, and fixed-income instruments suit your conservative financial temperament.',
    shiksha:      'Finance, architecture, music, culinary science, and horticulture are your ideal academic fields. You learn deeply and thoroughly — never rushing education.',
  },
  Gemini: {
    charitra:     'Intellectually versatile, communicative, and endlessly curious — you carry the room with your wit. Adaptability allows you to thrive in changing environments that exhaust others.',
    vivah:        'A partner who is your intellectual equal and best friend is non-negotiable. Mental chemistry keeps the marriage alive; freedom and variety within the partnership sustain it.',
    jeevan_shaili:'Busy, social, multi-threaded — you need several projects running simultaneously to feel fully engaged. Reading, networking, and digital connection are daily necessities.',
    rozgar:       'Media, journalism, writing, IT, sales, and education are your natural career domains. You often manage multiple income streams simultaneously with surprising ease.',
    vyavsay:      'Digital marketing, content creation, publishing, travel industry, and e-commerce suit you ideally. Businesses requiring communication agility are your native forte.',
    swasthya:     'Lungs, nervous system, and shoulders are your sensitive points. Mental overload and anxiety from constant stimulation require disciplined rest and regular pranayama.',
    ruchi:        'Reading, travel, debates, puzzles, language learning, and social networking are your favorite recreations. Intellectual stimulation IS rest for you.',
    prem:         'Wit and intelligence attract you far more than looks alone. You need a partner who can talk, joke, and think with you — mental fire must precede emotional surrender.',
    vitta:        'Multiple income streams are your natural financial pattern. Quick thinking identifies opportunities — but maintain a systematic savings plan to offset impulsive expenditure.',
    shiksha:      'Mathematics, linguistics, computer science, communications, and psychology are ideal academic pathways. You may complete multiple degrees or certifications across a career.',
  },
  Cancer: {
    charitra:     'Deeply empathetic, fiercely loyal, and blessed with near-psychic intuition. You absorb others\' emotions unconsciously — protecting your emotional boundaries is as important as nurturing others.',
    vivah:        'Home and family ARE your marriage — you invest everything into domestic harmony. A partner who honors your emotional depth and supports your nurturing instinct completes you entirely.',
    jeevan_shaili:'A warm home, family rituals, cooking, and honoring tradition are the fabric of your life. The past is sacred to you; cherished memories are your most treasured possessions.',
    rozgar:       'Nursing, child education, hospitality, real estate, psychology, and food-industry roles align perfectly with your Moon-ruled nurturing energy.',
    vyavsay:      'Restaurants, childcare centers, dairy, real estate, and healthcare businesses draw on your core strengths. Any enterprise that feeds, shelters, or nurtures people suits you naturally.',
    swasthya:     'Chest, digestion, and lymphatic system are your sensitive points. Emotional stress translates directly into digestive disorders — processing feelings is as important as diet.',
    ruchi:        'Cooking, gardening, family history, nostalgic music, and collecting sentimental objects are your deepest pleasures. Water — rivers, lakes, the sea — restores you profoundly.',
    prem:         'You love with your whole being — protective, devoted, and deeply romantic. Emotional security is your first need; withdrawal and rejection wound you more than harsh words.',
    vitta:        'Family property and inheritance may bring wealth. Savings instinct is strong — you provision for the future naturally. Avoid emotionally-driven overspending on family.',
    shiksha:      'Child psychology, nutrition, history, home science, and social work are ideal academic paths. You learn best through emotional connection with the subject and teacher.',
  },
  Leo: {
    charitra:     'Regal, magnanimous, and radiating natural authority — you lead by inspiration, never intimidation. Generosity is your defining trait; recognition is your emotional oxygen.',
    vivah:        'Your partner must celebrate your light, not compete with it. A loyal, admiring, and warm-hearted spouse turns your marriage into a lifelong royal partnership.',
    jeevan_shaili:'Drama, elegance, entertainment, and social prominence define your natural lifestyle. Ordinary settings bore you — you create atmosphere and meaning wherever you are.',
    rozgar:       'Government roles, executive management, entertainment, politics, and education suit your Sun-ruled authority and natural charisma. You are made for visible, respected positions.',
    vyavsay:      'Jewelry, luxury brands, event management, film, performing arts, and premium real estate are ideal businesses. Ventures where your personality IS the brand succeed most.',
    swasthya:     'Heart, spine, and upper back are your vulnerable areas. Ego stress and suppressed pride affect cardiac health — regular physical exercise and creative expression are vital medicine.',
    ruchi:        'Theater, music, dancing, organizing grand events, and mentoring others are your natural recreations. Being admired for your creative output gives you deep, authentic satisfaction.',
    prem:         'Love is grand, romantic, and theatrical for you — you give abundantly and expect adoration in return. A partner who openly celebrates you keeps the flame burning permanently.',
    vitta:        'You earn with confidence and spend generously. Wealth comes through authority and position. Disciplined investment in quality assets is your wisest long-term strategy.',
    shiksha:      'Leadership studies, political science, performing arts, and management are ideal academic fields. You excel when given visible roles and genuine recognition for achievement.',
  },
  Virgo: {
    charitra:     'Precise, service-minded, and perpetually improving — you express love through usefulness. Your critical eye, productively turned inward, drives remarkable personal mastery.',
    vivah:        'A diligent, intelligent, and health-conscious partner earns your deepest respect. You show love through acts of service; receiving it graciously requires accepting imperfection.',
    jeevan_shaili:'Organized schedules, clean environments, healthy routines, and intellectually stimulating work define your ideal lifestyle. Chaos and disorder create profound, physical-feeling anxiety.',
    rozgar:       'Healthcare, data analysis, editing, auditing, nutrition, and pharmaceuticals align with your Mercury-ruled precision. Systematic, quality-focused roles are your native territory.',
    vyavsay:      'Health tech, herbal medicine, editing and publishing, accounting, and consulting businesses draw on your native strengths. Quality and precision are your competitive advantages.',
    swasthya:     'Digestive system, intestines, and nervous system are your sensitive points. Anxiety and over-analysis manifest as IBS and chronic tension — regular yoga and a simple diet provide real relief.',
    ruchi:        'Research, healthy cooking, detailed crafts, journaling, and self-improvement activities are your preferred recreations. You find genuine rest in purposeful, improving work.',
    prem:         'You show love through practical care — remembering preferences, solving problems, and being utterly reliable. A partner who appreciates subtlety rather than dramatic gestures is your ideal.',
    vitta:        'Methodical and disciplined with money, you budget and plan naturally. Healthcare, editing services, or analytical consultancy offer your best earning opportunities.',
    shiksha:      'Medicine, chemistry, statistics, linguistics, and editing are your ideal academic paths. Precision and attention to detail give you exceptional examination results.',
  },
  Libra: {
    charitra:     'Graceful, just, and naturally diplomatic — you find the middle path in every conflict. Your gift for seeing all sides makes you an outstanding negotiator and genuine peacemaker.',
    vivah:        'Partnership is your life purpose — marriage and close alliances define and complete you. A sophisticated, fair-minded, and aesthetically refined partner brings out your best self.',
    jeevan_shaili:'Beauty, social harmony, cultural events, and balanced relationships form the texture of your ideal life. Discord and forced choices drain you; aesthetic environments restore you.',
    rozgar:       'Law, diplomacy, HR, interior design, fashion, and arts administration suit your Venus-ruled temperament. Professions requiring balance, beauty, or negotiation are your natural domain.',
    vyavsay:      'Luxury goods, beauty services, legal consulting, and event management are ideal businesses. Partnerships and joint ventures typically succeed better for you than solo ventures.',
    swasthya:     'Kidneys, lower back, and skin are your vulnerable areas. Unresolved conflict and chronic indecision manifest as physical ailments — making clear choices benefits your health directly.',
    ruchi:        'Music, visual arts, theater, fashion, interior decoration, and elegant social gatherings are your natural pleasures. Aesthetic refinement in all areas of life is your ongoing project.',
    prem:         'Courtship, romantic gestures, and beauty within the relationship are essential needs. A thoughtful, elegant, and socially engaging partner keeps you fully enchanted.',
    vitta:        'Earnings grow through partnerships and aesthetic industries. Impulsive luxury expenditure can unbalance finances — a trusted advisor helps maintain equilibrium.',
    shiksha:      'Law, fine arts, social sciences, diplomacy, and design are ideal academic fields. Cooperative, debate-rich learning environments bring out your intellectual best.',
  },
  Scorpio: {
    charitra:     'Intense, psychologically penetrating, and magnetically compelling — you transform everything you touch. Your capacity for regeneration after loss is your most extraordinary personal quality.',
    vivah:        'Total emotional merger is what you seek — surface-level partnership leaves you cold. A partner who matches your depth and remains loyal through every transformation is your life mate.',
    jeevan_shaili:'Your life is structured around investigation, transformation, and intense engagement. Privacy and purposeful solitude are essential — you need depth, not breadth of experience.',
    rozgar:       'Research, investigation, surgery, psychology, intelligence services, and occult sciences align with your Mars-Ketu intensity. Roles requiring depth, secrecy, and transformation suit you.',
    vyavsay:      'Forensics, insurance, surgery, psychology practice, mining, and investigative services are ideal businesses. You succeed professionally where others fear to go.',
    swasthya:     'Reproductive system, colon, and urinary tract are sensitive. Suppressed emotions and obsessive thinking create psychosomatic illness — conscious emotional release is essential medicine.',
    ruchi:        'Mystery, psychology, occult studies, deep investigation, martial arts, and transformative solitary practices are your natural recreations. Shallow entertainment barely holds your interest.',
    prem:         'You love with volcanic intensity and uncompromising fidelity. Jealousy and control impulses require conscious management — the reward is a bond of extraordinary and rare depth.',
    vitta:        'Wealth comes through depth of expertise and well-kept confidence. Inheritance, joint finances, and insurance may feature prominently. You protect accumulated wealth fiercely.',
    shiksha:      'Psychology, forensic science, research medicine, and occult sciences are ideal academic paths. You specialize deeply rather than broadly — mastery is always your educational goal.',
  },
  Sagittarius: {
    charitra:     'Optimistic, philosophical, and expansive — you convert experience into wisdom and wisdom into teaching. Freedom of thought is your most non-negotiable requirement.',
    vivah:        'A partner who is your fellow explorer — intellectually, philosophically, and geographically — fulfills your deepest need. Rigid or narrow-minded partners stifle you progressively.',
    jeevan_shaili:'Travel, higher education, outdoor adventure, philosophical inquiry, and teaching define your ideal life. Small worlds confine you — horizon-expanding experiences are your regular diet.',
    rozgar:       'Education, law, international business, religious leadership, publishing, and the travel industry align with your Jupiter-ruled expansiveness. Large scope is your minimum requirement.',
    vyavsay:      'Export-import, higher education institutes, religious tourism, legal consulting, and sports management are your natural business areas. A large, inspiring vision fuels your best work.',
    swasthya:     'Hips, thighs, and liver are your sensitive areas. Overindulgence in food and a tendency to overextend physically require moderation and regular medical check-ups.',
    ruchi:        'Travel, philosophy, archery, horse riding, foreign cultures, and mentoring others are your deepest pleasures. Expanding your perspective IS recreation for you.',
    prem:         'Your love is joyful, free, and perpetually adventurous. A partner who travels — physically and intellectually — with you keeps love permanently fresh and exciting.',
    vitta:        'Wealth comes through knowledge, foreign connections, and expansive ventures. Generosity occasionally exceeds prudence — balance giving freely with building long-term assets.',
    shiksha:      'Philosophy, law, foreign languages, sports science, and international relations are ideal academic paths. Study abroad opportunities, if available, transform your worldview and prospects.',
  },
  Capricorn: {
    charitra:     'Disciplined, deeply ambitious, and unfailingly reliable — your word means everything. Life improves steadily with age; Saturn rewards your extraordinary patience with compounding returns.',
    vivah:        'A marriage of mutual respect, shared goals, and practical partnership suits you best. Romance grows slowly but lasts; you are the most faithful of spouses once committed.',
    jeevan_shaili:'Structured routines, professional advancement, long-term goals, and social standing frame your lifestyle. You delay gratification masterfully — you build while others merely consume.',
    rozgar:       'Government service, law, engineering, management, banking, and large corporations suit your Saturn-ruled discipline. Authority and seniority arrive reliably with sustained effort and time.',
    vyavsay:      'Construction, mining, real estate, accounting, and industrial manufacturing are ideal businesses. You succeed through systematic process discipline over the long term.',
    swasthya:     'Bones, knees, joints, and skin are your sensitive areas. Overwork and emotional suppression can lead to depression — rest, warmth, and deliberate social connection are important medicine.',
    ruchi:        'Mountain trekking, chess, classical music, history, architecture, and mentoring professionals are your natural recreations. You genuinely enjoy effort-based mastery.',
    prem:         'You are a slow, steady, and deeply loyal lover. Emotional expression comes cautiously — but once given, your devotion is absolute and enduring. You protect your partner with quiet ferocity.',
    vitta:        'Methodical wealth-building through property, regulated investments, and career advancement is your financial signature. Compounding returns from disciplined savings define your financial life.',
    shiksha:      'Engineering, law, accounting, architecture, and public administration are ideal academic fields. You perform exceptionally in structured, examination-based systems requiring sustained effort.',
  },
  Aquarius: {
    charitra:     'Innovative, humanitarian, and intellectually independent — you think for yourself and for society simultaneously. Conventional thinking bores you; systems that serve humanity excite and energize you.',
    vivah:        'A partner who is first your intellectual equal and then your companion serves you best. Freedom, mutual respect, and intellectual stimulation within the partnership are non-negotiable.',
    jeevan_shaili:'Technology, social causes, unconventional thinking, and wide networks define your emotional ecosystem. Predictability suffocates you — innovation and independence nourish you.',
    rozgar:       'Technology, social work, research, aviation, and media suit your Saturn-ruled humanitarian intellect. Roles advancing human progress and allowing independent thinking are your best fit.',
    vyavsay:      'Tech startups, NGOs, scientific research, digital services, and social enterprises align with your nature. Mission-driven ventures succeed for you more than purely profit-driven ones.',
    swasthya:     'Calves, ankles, and the nervous system are sensitive areas. Carrying the world\'s causes creates burnout — intentional physical grounding and deliberate rest are essential health practices.',
    ruchi:        'Technology projects, social activism, astronomy, unusual hobbies, and group intellectual pursuits fill your leisure with genuine meaning and purpose.',
    prem:         'Friendship is the mandatory foundation of your love. You need a partner who allows you to be completely yourself — a fellow citizen of the world rather than a dependent companion.',
    vitta:        'Income flows through technology, networks, and intellectual capital. Unconventional financial instruments suit your nature, but diversification and a financial advisor provide necessary stability.',
    shiksha:      'Computer science, astrophysics, social science, engineering, and philosophy are ideal academic fields. Progressive institutions that reward original thinking bring out your very best.',
  },
  Pisces: {
    charitra:     'Compassionate, spiritually attuned, and artistically gifted — you perceive what others merely see. Your empathy is your greatest gift and the boundary you must most carefully protect.',
    vivah:        'A soulmate-level connection — spiritual, artistic, and emotionally honest — is what you truly seek. A grounding partner who also honors your sensitivity creates the most enduring bond.',
    jeevan_shaili:'Meditation, music, art, spiritual practice, and connection with natural water bodies form your ideal life rhythm. Aggressive or relentlessly materialistic environments erode your core energy.',
    rozgar:       'Healthcare, arts, music, spiritual guidance, marine sciences, and social welfare are your natural career terrains. Creative and compassionate roles sustain you deeply.',
    vyavsay:      'Music studios, healing arts, spa and wellness centers, marine businesses, and spiritual retreats align with your Jupiter-ruled compassionate nature and innate aesthetic sense.',
    swasthya:     'Feet, lymphatic system, and immune function are your vulnerable areas. Absorbing others\' emotional stress is your most significant health risk — boundaries and regular detoxification are essential.',
    ruchi:        'Music, poetry, painting, swimming in natural water, spiritual reading, and solitary contemplation are your deepest pleasures. Dreams and imagination are realms you inhabit naturally.',
    prem:         'You love with otherworldly depth — idealistic, selfless, and romantically visionary. Balance your boundless compassion with discernment; protect your open heart from those who exploit it.',
    vitta:        'Wealth may come through creative or spiritual work, inheritance, or overseas connections. A disciplined financial advisor is crucial — generous and impractical impulses need careful management.',
    shiksha:      'Fine arts, music, marine science, spiritual studies, psychology, and social work are ideal academic areas. Intuitive learning and mentorship relationships inspire your finest academic work.',
  },
};

// ─── MOON-SIGN DOMAIN ADDITIONS (English) ─────────────────────────────────────
const MOON_DOMAIN_EN = {
  Aries: {
    charitra:      'Your Aries Moon makes you emotionally spontaneous and unable to mask feelings. What you experience, you express immediately — a refreshing directness that builds genuine trust.',
    vivah:         'An Aries Moon demands emotional freedom and an energetic partner in marriage. You recover from conflict quickly and hold no grudges — clean disagreements rather than simmering resentment.',
    jeevan_shaili: 'Emotional restlessness drives you toward constant activity and new challenges. Stagnation is your emotional enemy — movement and ambitious goals are your inner medicine.',
    swasthya:      'Your Aries Moon loads the nervous system and head. Emotional frustration can trigger headaches, insomnia, and hypertension — vigorous physical exercise is your most effective stress release.',
    ruchi:         'Competitive sport, adventure, exploration, and leadership activities satisfy your Aries Moon\'s hunger for achievement and stimulus.',
    prem:          'Your Moon makes you an eager, direct, and impulsive lover — you declare feelings without hesitation. Allow time to truly know someone before full emotional commitment.',
  },
  Taurus: {
    charitra:      'Your Taurus Moon is exalted — granting emotional bedrock, patience, and deep sensory intelligence. You are the person others lean on; stability radiates from you naturally.',
    vivah:         'Your Taurus Moon needs physical security, steady affection, and a comfortable home life to feel truly married. A patient, tactile, and reliable partner brings out your most devoted nature.',
    jeevan_shaili: 'Regular rhythms, good food, pleasant surroundings, and unhurried enjoyment define your emotional needs. Sensory experience and emotional experience are one and the same for you.',
    swasthya:      'Your Taurus Moon makes you susceptible to throat, thyroid, and metabolic imbalances under stress. Gentle music, good food, and natural settings restore you more quickly than any medication.',
    ruchi:         'Music, cooking, gardening, and leisurely nature walks in beautiful settings are your native pleasures. Quality objects, art, and comfort serve as emotional anchors.',
    prem:          'Your Moon makes you an exquisitely devoted and physically expressive lover. Touch, gifts, and cooking for your beloved are how you say "I love you" most naturally and authentically.',
  },
  Gemini: {
    charitra:      'Your Gemini Moon makes you emotionally agile, curious, and communicative. You process feelings by talking about them — conversation is your primary emotional processing chamber.',
    vivah:         'A Gemini Moon needs mental chemistry in marriage above all else. Boredom genuinely threatens your relationships — intellectual exchange and novelty keep love alive.',
    jeevan_shaili: 'Variety, social connection, media, and intellectual stimulation are your emotional necessities. Multiple simultaneous streams of engagement produce emotional satisfaction.',
    swasthya:      'Your Gemini Moon creates a nervous system that rarely switches off. Anxiety, restless sleep, and respiratory sensitivity result from information overload — deliberate quiet time is essential.',
    ruchi:         'Reading, travel, learning new languages, and witty conversation are your Moon\'s natural recreations. A daily diet of new information maintains your emotional equilibrium.',
    prem:          'Intellectual attraction is your primary romantic trigger. You need a partner who thinks, jokes, and communicates with you — the mind must catch fire before the heart follows.',
  },
  Cancer: {
    charitra:      'Your Cancer Moon (exalted) gives you extraordinary empathy, emotional depth, and an almost clairvoyant intuition. You are the natural emotional center of every group you belong to.',
    vivah:         'Home, family rituals, and deep emotional bonding are the very DNA of your marriage. A Cancer Moon must feel completely safe before giving itself fully — then gives absolutely everything.',
    jeevan_shaili: 'Your emotional needs are met through home, family, tradition, and the preservation of cherished memories. You return to the past not to escape it but to replenish yourself from it.',
    swasthya:      'Your Cancer Moon encodes emotions directly into the digestive system. Unexpressed sadness becomes stomach problems — emotional honesty is a genuine health practice for you.',
    ruchi:         'Cooking for loved ones, tending a garden, listening to nostalgic music, and preserving family history are your deepest pleasures and most restorative activities.',
    prem:          'You love with every cell of your being — protective, romantic, and devoted to the end. Security is your first emotional need; a partner who provides it receives your eternal loyalty.',
  },
  Leo: {
    charitra:      'Your Leo Moon makes you warm, generous, and emotionally dramatic. Being seen and appreciated is an emotional necessity, not vanity — recognition genuinely energizes you.',
    vivah:         'A Leo Moon needs visible affection, open admiration, and a spouse who is genuinely proud of you. Your love is given lavishly — it needs to be returned with equal generosity.',
    jeevan_shaili: 'Your emotional wellbeing requires creativity, celebration, and being at the center of something meaningful. Anonymity deflates you; a life with an audience nourishes you.',
    swasthya:      'Heart and spine hold your emotional stress. Feeling overlooked has measurable physical impact — creative expression and regular recognition are genuine health interventions for you.',
    ruchi:         'Theatre, music, hosting gatherings, creative arts, and leading groups satisfy your Leo Moon\'s deep need for expression and heartfelt appreciation.',
    prem:          'Love is simultaneously a grand performance and a profound commitment for you. You adore your partner extravagantly — and need to be celebrated equally and openly in return.',
  },
  Virgo: {
    charitra:      'Your Virgo Moon makes you emotionally attentive, service-oriented, and quietly compassionate. You show love through acts of care rather than declarations — doing is your natural emotional idiom.',
    vivah:         'A Virgo Moon needs order, reliability, and mutual competence in marriage. Practical care, problem-solving, and noticing small details are how you express deep love.',
    jeevan_shaili: 'Clean environments, structured routines, and useful work create your emotional stability. Order is not control for you — it is peace, and chaos genuinely disturbs your wellbeing.',
    swasthya:      'Digestive and intestinal health is directly linked to your emotional state. Anxiety from overthinking is your primary health risk — yoga, simple diet, and mindful breathing provide real relief.',
    ruchi:         'Research, healthy cooking, detailed crafts, journaling, and system-improving projects are your natural leisure. You find rest in purposeful, improving activity rather than idleness.',
    prem:          'You love carefully, practically, and with extraordinary attentiveness. A partner who recognizes your quiet acts of devotion — and reciprocates in kind — makes you feel profoundly loved.',
  },
  Libra: {
    charitra:      'Your Libra Moon makes you emotionally attuned to fairness, beauty, and social harmony. Conflict distresses you deeply; diplomacy and aesthetic grace are your natural emotional defaults.',
    vivah:         'Partnership is not a choice for your Libra Moon — it is an emotional necessity. You function best in close, harmonious relationship; isolation or prolonged discord diminishes you.',
    jeevan_shaili: 'Beautiful spaces, cultured company, aesthetic pursuits, and balanced social engagement define your emotional wellbeing. You wither in harsh or perpetually conflicted environments.',
    swasthya:      'Kidneys and lower back absorb the stress of unresolved conflict. Making clear decisions rather than hovering between options has direct, measurable physical health benefits.',
    ruchi:         'Art appreciation, music, interior design, social gatherings, and cultural events are your natural pleasures. Aesthetic refinement in everyday life is a health practice for your soul.',
    prem:          'Romance, thoughtful gestures, and beautiful settings are your love language. A considerate and elegant partner who courts you with genuine care wins your deepest and most lasting affection.',
  },
  Scorpio: {
    charitra:      'Your Scorpio Moon gives you extraordinary emotional intensity, penetrating psychological insight, and a capacity for complete transformation. You feel everything at maximum depth — no emotional half-measures.',
    vivah:         'Complete emotional merger is your deepest need in marriage. Superficial partnership leaves you profoundly unsatisfied — you need a bond that goes all the way to the soul.',
    jeevan_shaili: 'Your Scorpio Moon drives you toward depth, investigation, and intense purposeful experience. Comfortable mediocrity is alien to your emotional landscape — transformation is your natural state.',
    swasthya:      'Suppressed emotion is your primary health risk. Unexpressed rage, grief, or desire manifests as reproductive or urinary issues — emotional honesty and therapeutic release are essential.',
    ruchi:         'Mystery, psychology, occult sciences, deep research, and intense transformative experiences are your natural recreations. Shallow entertainment barely holds your attention.',
    prem:          'You love with volcanic passion and absolute fidelity. Possessiveness and jealousy arise when trust is threatened — communicating these feelings openly, rather than acting on them, transforms the relationship.',
  },
  Sagittarius: {
    charitra:      'Your Sagittarius Moon gives you emotional optimism, philosophical resilience, and a genuine love of freedom. You bounce back from adversity with remarkable ease by finding the larger meaning.',
    vivah:         'Freedom and intellectual companionship are emotional necessities in your marriage. A partner who shares your love of travel, expansive ideas, and wide horizons makes you fully and lastingly happy.',
    jeevan_shaili: 'Travel, outdoor exploration, philosophical inquiry, and generous living define your emotional style. Restrictions — physical or intellectual — create emotional deflation quickly and noticeably.',
    swasthya:      'Hips, thighs, and liver absorb your natural excesses. Optimism can lead to physical overindulgence and medical neglect — moderation and regular check-ups are your health non-negotiables.',
    ruchi:         'Travel, philosophy, outdoor sports, teaching, and exploring foreign cultures and ideas are your deepest pleasures. Expanding your perspective IS your version of rest.',
    prem:          'Your Moon loves freely, joyfully, and without possessiveness. A partner who is your travel companion and philosophical sparring partner keeps romance permanently alive and fresh.',
  },
  Capricorn: {
    charitra:      'Your Capricorn Moon gives you emotional seriousness, unwavering discipline, and a deeply felt sense of duty. Reliability under pressure is your greatest emotional gift.',
    vivah:         'Stability, shared ambitions, and mutual respect are your emotional requirements in marriage. You express love through reliability and steady provision — the partner who notices this truly has your heart.',
    jeevan_shaili: 'Structured goals, measurable progress, and earned achievements form the backbone of your emotional satisfaction. You invest, never merely spend — in finances and in relationships equally.',
    swasthya:      'Joints, bones, and skin carry your emotional stress. Periods of depression from overwork and emotional suppression require conscious rest, warmth, and meaningful social connection to heal.',
    ruchi:         'Mountain trekking, chess, classical music, history, and professional mentoring satisfy your Capricorn Moon\'s need for purposeful, effort-based engagement and mastery.',
    prem:          'Your love is quietly ferocious in its loyalty and slow to declare itself. Once given, your devotion is permanent and unshakeable — a partner who values steadiness over drama is your ideal.',
  },
  Aquarius: {
    charitra:      'Your Aquarius Moon makes you emotionally independent, intellectually oriented, and genuinely invested in collective human wellbeing. Individual emotional drama interests you far less than shared ideals.',
    vivah:         'Friendship is the mandatory foundation of your marriage. A partner who respects your intellectual freedom, social engagement, and need for occasional solitude sustains the relationship long-term.',
    jeevan_shaili: 'Ideas, technology, social causes, and networks of interesting people form your emotional ecosystem. Conventional domestic life alone leaves you chronically under-stimulated.',
    swasthya:      'Calves, ankles, and the nervous system are sensitive areas. Social isolation and the weight of carrying others\' causes create burnout — physical grounding and deliberate rest are essential.',
    ruchi:         'Technology, astronomy, social activism, unusual hobbies, and group intellectual projects fill your leisure time with genuine purpose and meaning.',
    prem:          'You fall in love with minds and causes, not just people. Your Moon needs a partner who is also a true friend, collaborator, and fellow citizen of the world.',
  },
  Pisces: {
    charitra:      'Your Pisces Moon gives you extraordinary empathy, creative sensitivity, and a spiritual intuition that borders on the mystical. You feel invisible undercurrents in every situation.',
    vivah:         'A soulmate connection — deep, spiritual, and emotionally transparent — is what your Pisces Moon truly needs. Practical love that honors your sensitivity creates the most lasting and fulfilling bond.',
    jeevan_shaili: 'Meditation, creative arts, music, spiritual practice, and time near natural water define your emotional needs. Harsh, aggressive environments drain your core energy rapidly.',
    swasthya:      'Feet, immune system, and lymphatic health are sensitive areas. Absorbing others\' emotional pain is your most significant health risk — regular detoxification and firm boundaries are essential.',
    ruchi:         'Poetry, music, painting, swimming in natural water, and spiritual study are your deepest pleasures. Dreams and imagination are realms you inhabit as naturally as waking life.',
    prem:          'Your love is idealistic, self-giving, and romantically boundless. Balance your compassion with discernment — protect your generous heart from those who mistake openness for weakness.',
  },
};

// ─── PLANET-AS-HOUSE-LORD DOMAIN ADDITIONS (English) ──────────────────────────
const PLANET_CAREER_EN = {
  Sun:     'Sun as 10th lord confers success in government service, administration, and leadership positions. Career is marked by public recognition, authority, and a growing reputation for excellence.',
  Moon:    'Moon as 10th lord favors careers in public service, hospitality, nutrition, and professions serving large numbers of people. Career fluctuates in waves but ultimately achieves genuine popular recognition.',
  Mars:    'Mars as 10th lord brings success in technology, military, police, surgery, engineering, and entrepreneurship. Career is defined by decisive action, courage, and relentless execution.',
  Mercury: 'Mercury as 10th lord grants excellence in business, communications, IT, writing, finance, and media. Managing multiple career streams or roles simultaneously is your distinctive professional signature.',
  Jupiter: 'Jupiter as 10th lord confers honor through education, law, judiciary, religion, and advisory roles. Your career grows with wisdom — your field gradually comes to regard you as a respected authority.',
  Venus:   'Venus as 10th lord brings career success through arts, beauty industry, entertainment, fashion, and finance. Public charm and aesthetic excellence are your professional competitive advantage.',
  Saturn:  'Saturn as 10th lord delivers late but permanent career success. Discipline, methodical effort, and long-term thinking build a career that compounds in strength, authority, and respect over time.',
  Rahu:    'Rahu as 10th lord opens unconventional career pathways — technology, media, foreign connections, and disruption of established industries. Sudden, dramatic career breakthroughs are characteristic.',
  Ketu:    'Ketu as 10th lord favors research, spiritual practice, alternative medicine, and technical-scientific fields. Your career path is distinctively individual — beyond conventional professional tracks.',
};

const PLANET_VITTA_EN = {
  Sun:     'Sun as 2nd lord brings wealth through prestige, authority, and government-connected enterprise. Family inheritance and the father\'s financial legacy may play a meaningful role.',
  Moon:    'Moon as 2nd lord creates fluctuating income connected to public-facing businesses and nurturing professions. Family and maternal connections influence financial destiny significantly.',
  Mars:    'Mars as 2nd lord produces wealth through bold enterprise, land, property development, and energetic income-generating activity. Speech can be blunt — choose words in financial negotiations carefully.',
  Mercury: 'Mercury as 2nd lord makes communication, writing, trade, and intellectual services your primary wealth channels. Your voice and written work are literally among your most valuable financial assets.',
  Jupiter: 'Jupiter as 2nd lord brings steadily growing, dharmic wealth through education, knowledge, and family wisdom traditions. True financial deprivation is genuinely rare with this placement.',
  Venus:   'Venus as 2nd lord brings wealth through luxury goods, creative arts, beauty, and sensory industries. A natural orientation toward quality and refinement marks your approach to earning and spending.',
  Saturn:  'Saturn as 2nd lord builds wealth slowly through discipline and methodical frugality. Once established, this financial base is exceptionally durable — patience is your greatest financial virtue.',
  Rahu:    'Rahu as 2nd lord can produce sudden gains through unconventional, technological, or foreign channels — and equally sudden reversals. Financial discipline and meaningful diversification are essential.',
  Ketu:    'Ketu as 2nd lord suggests material wealth takes second place to spiritual and intellectual enrichment. Conscious spending, contentment, and simple living are your wisest long-term financial strategies.',
};

const PLANET_VIDYA_EN = {
  Sun:     'Sun as 5th lord confers academic excellence in leadership, administration, and competitive examinations. Educational achievements bring lasting recognition and the respect of peers and mentors.',
  Moon:    'Moon as 5th lord grants exceptional memory, intuitive understanding, and strength in psychology, nutrition, and creative subjects. You absorb and retain learning with unusual depth and endurance.',
  Mars:    'Mars as 5th lord brings high performance in engineering, medical sciences, competitive sports training, and entrance examinations. Competitive drive and disciplined effort produce outstanding results.',
  Mercury: 'Mercury as 5th lord gives outstanding ability in mathematics, languages, computer science, and commerce. Quick, versatile intelligence grasps new material and synthesizes it with ease.',
  Jupiter: 'Jupiter as 5th lord is a classical indicator of exceptional scholarship — philosophy, law, sacred texts, and higher education are your peak academic territories. Deep wisdom is your educational destiny.',
  Venus:   'Venus as 5th lord produces natural talent in fine arts, music, dance, literature, and design. Creative and aesthetic subjects are your clearest academic high ground.',
  Saturn:  'Saturn as 5th lord creates scholars through sustained effort rather than easy natural gifts. Late academic achievements are often your most significant and enduring accomplishments.',
  Rahu:    'Rahu as 5th lord draws you to technology, modern science, and unconventional fields of study. Exposure to diverse intellectual traditions and study abroad can be genuinely transformative.',
  Ketu:    'Ketu as 5th lord points to mastery of spiritual sciences, occult knowledge, and deep specialized research. Innate capabilities from prior lifetimes manifest as unusual academic gifts.',
};

module.exports = {
  LAGNA_LIFE_EN,
  MOON_DOMAIN_EN,
  PLANET_CAREER_EN,
  PLANET_VITTA_EN,
  PLANET_VIDYA_EN,
};
