'use strict';

// ── Weekly data: 4 rotating themes (week_of_year % 4) ─────────────────────────
// 0=Expansion, 1=Discipline, 2=Passion, 3=Harmony
const WEEKLY = {
  Aries: [
    { theme: 'Expansion', overview: 'Jupiter energises your 9th house, drawing powerful opportunities in education, travel, and publishing. A long-held ambition receives unexpected institutional backing. Trust the expansion — it is cosmically timed.', love: 'A stimulating intellectual connection sparks romantic interest. Existing partners feel reinvigorated by your adventurous spirit this week.', career: 'A bold proposal gets the green light. Collaboration with someone from a different field brings fresh momentum to stalled projects.', health: 'High vitality rewards your active lifestyle. Channel surplus energy into outdoor pursuits — your head and eyes benefit from bright, open spaces.' },
    { theme: 'Discipline', overview: 'Saturn\'s steady hand rewards the methodical approach you have been resisting. A financial structure you build this week will serve you for years. Patience is not your strongest virtue, Aries — but this week it is your most rewarding one.', love: 'Depth matters more than drama this week. An honest conversation resolves a recurring misunderstanding with lasting effect.', career: 'Focused, solo work outperforms teamwork. A technical skill sharpened now becomes a significant career asset within months.', health: 'Rest is productive. Your adrenals need recovery time — discipline here means scheduling sleep, not just workouts.' },
    { theme: 'Passion', overview: 'Mars, your ruler, ignites your chart with rare directional clarity. Everything you attempt carries the force of your full conviction. This is your warrior week — step forward without hesitation.', love: 'Passionate declarations land well. Singles attract through magnetic confidence; couples rediscover the spark that started everything.', career: 'Take the risk that has been circling your mind. Leadership opportunities favour those who act first and adjust second.', health: 'Physical strength is at a peak. Intensive training, athletic goals, or starting a new movement practice all thrive this week.' },
    { theme: 'Harmony', overview: 'Venus lights up your social sphere with rare warmth. Collaborations, partnerships, and creative endeavours all carry a golden quality. Let others contribute — you will like the result.', love: 'This is among your best romantic weeks of the season. New connections carry real potential; long-term bonds deepen through shared beauty and pleasure.', career: 'Aesthetic decisions, client-facing roles, and negotiation all go your way. A creative solution earns admiration from the right people.', health: 'Reduce inflammation through anti-inflammatory foods. Gentle movement — yoga, swimming, or dance — heals more than intensity this week.' },
  ],
  Taurus: [
    { theme: 'Expansion', overview: 'Jupiter in your financial sector opens doors to multiple income streams. A resource you have undervalued — a skill, a contact, or a passion — reveals its true earning potential. Invest in learning something new.', love: 'Generosity in love pays compounding returns this week. A grand gesture, even a small one executed with genuine care, transforms the atmosphere.', career: 'Property, banking, or long-term value creation sectors carry the most promise. A business plan reviewed now is 30% stronger by Friday.', health: 'Your throat and thyroid respond well to warming herbs and reduced screen time. Singing or chanting activates Taurus healing frequencies.' },
    { theme: 'Discipline', overview: 'Saturn supports your natural love of structure. Systems built this week — financial, domestic, or professional — last decades. Resist the urge to rush; thoroughness is your superpower.', love: 'Stability and reliability are your love language this week. Being utterly dependable is the most romantic thing you can offer.', career: 'Detailed work — accounting, quality review, systems design — produces outstanding results. A senior figure notices your quiet excellence.', health: 'Consistent, moderate exercise outperforms occasional intensity. Establish a routine around meals and sleep that you will actually maintain.' },
    { theme: 'Passion', overview: 'Venus activates your expressive side with unusual fire. Taurus, you are rarely impulsive — but this week your instincts are faster and more accurate than your analysis. Act on them.', love: 'Physical affection and sensory pleasure deepen bonds in ways words cannot. Create an experience, not just a conversation.', career: 'Your value presentation — resume, portfolio, pitch — benefits enormously from a passionate, personal rewrite. Authenticity sells now.', health: 'Outdoor physical activity, especially involving earth and nature, restores your Venusian body. Gardening, hiking, or simply walking barefoot on grass heals at a cellular level.' },
    { theme: 'Harmony', overview: 'The cosmic scales tip in your favour across relationships and resources. A compromise you make now preserves something far more valuable long-term. Your patience earns you exactly what you have been waiting for.', love: 'Partnership matters — romantic, creative, or business — are unusually fruitful. A new alliance formed this week carries lasting value.', career: 'Collaborative projects thrive. Your ability to find the middle ground in a contentious team issue earns you considerable social capital.', health: 'Beauty is medicine for Taurus. Invest in something that pleases the senses — quality food, massage, aesthetically pleasing surroundings.' },
  ],
  Gemini: [
    { theme: 'Expansion', overview: 'Mercury and Jupiter align to give your mind extraordinary range and persuasiveness. Ideas you share this week take root in others\' imaginations and grow back to you as opportunities. Write, speak, publish — the cosmic timing is exceptional.', love: 'Intellectual connection deepens romantic bonds. A stimulating debate or shared curiosity leads somewhere unexpectedly tender.', career: 'Media, education, writing, and technology sectors are all lit up. A proposal sent this week will be received far better than you expect.', health: 'Mental hygiene matters as much as physical. Protect your nervous system from information overload — scheduled offline periods yield surprising peace.' },
    { theme: 'Discipline', overview: 'Saturn asks you to finish what you started rather than beginning something new. This is difficult for Gemini, but the completed project waiting in your wake is more valuable than the next exciting idea. See it through.', love: 'Showing up consistently — returning calls, keeping plans — communicates volumes more than any clever words this week.', career: 'Deep focus on a single project from start to finish produces results that scattered brilliance cannot. Avoid multitasking and astonish yourself.', health: 'Your nervous system responds dramatically to routine. Fixed meal times, a consistent sleep schedule, and daily breath work transform your baseline energy.' },
    { theme: 'Passion', overview: 'Your curiosity turns into decisive action. Gemini rarely commits quickly, but this week your instinct to say yes to something new is exactly right. The window is open — step through it.', love: 'Spontaneity electrifies both new and established connections. Surprise your partner or yourself by doing something genuinely unexpected.', career: 'A bold, unconventional approach breaks a professional logjam. Your ability to reframe problems as opportunities is at its sharpest.', health: 'Movement that engages the mind — dance, martial arts, trail running — is especially healing. Your arms and shoulders benefit from stretching.' },
    { theme: 'Harmony', overview: 'Social harmony is your native state, and this week the entire cosmos cooperates. Bridges built now — in relationships, communities, and collaborations — carry significant traffic for years to come.', love: 'You are at your most charming and verbally gifted. A heartfelt, articulate expression of feeling changes the temperature of a relationship.', career: 'Mediation, client relations, PR, and team communication all excel. Your presence in a room makes difficult conversations suddenly manageable.', health: 'Balance mental with physical activity deliberately. An equal ratio of movement, creativity, and rest produces peak Gemini wellbeing.' },
  ],
  Cancer: [
    { theme: 'Expansion', overview: 'The Moon\'s nodes activate your axis of learning and home, Cancer. An opportunity to expand your domestic life — through property, family growth, or relocation — arrives with Jupiter\'s blessing. Trust your intuition about the timing; it is rarely this clear.', love: 'Emotional depth is your greatest romantic gift and this week it is fully online. A vulnerable conversation creates lasting intimacy.', career: 'Work from a foundation of emotional security and your professional output reaches unusual heights. Nurturing fields — education, healthcare, hospitality — carry particular promise.', health: 'Your digestive system is your barometer. What upsets your stomach this week reveals what your emotions have been processing. Listen carefully.' },
    { theme: 'Discipline', overview: 'Saturn in your house of beliefs asks you to examine which stories are serving you and which are keeping you small. The hard interior work of this week produces a lightness that follows you for months.', love: 'Emotional boundaries — knowing where you end and another person begins — strengthen relationships rather than distancing them.', career: 'Long-term strategic planning receives Saturn\'s endorsement. Foundations laid with care now support structures of considerable weight later.', health: 'Establish a non-negotiable self-care ritual. Even ten minutes of daily practice — journaling, breathwork, or prayer — compounds dramatically over time.' },
    { theme: 'Passion', overview: 'Mars activates your public sector, Cancer. Step out of the protective shell and claim the visibility you have earned. Leadership is not imposed on you — it is something you choose this week.', love: 'Direct expression of desire creates surprising breakthroughs. Say what you want — the response will astonish you.', career: 'Initiative and courage open professional doors that patience alone could not. Propose, pitch, or apply for something that feels slightly out of reach.', health: 'Physical courage is healing — try a new form of exercise that challenges your body and ignites your competitive spirit.' },
    { theme: 'Harmony', overview: 'Venus graces your domestic sphere with unusual warmth. Home becomes a sanctuary that genuinely restores you, and family relationships bloom with spontaneous affection. This is the week to invest in where you live and who you live with.', love: 'Tenderness and care flow both ways with unusual ease. Simple rituals — cooking together, sharing memories, sitting in comfortable silence — nourish the deepest bonds.', career: 'Aesthetic refinement of your workspace or professional presentation pays disproportionate dividends. Beauty is a professional tool, not a luxury.', health: 'Nourishing food, adequate hydration, and time spent near water are your medicine this week. Listen to your body\'s cycles with patience.' },
  ],
  Leo: [
    { theme: 'Expansion', overview: 'The Sun illuminates your creative sector with extraordinary clarity. A self-expressive project — artistic, entrepreneurial, or personal — receives cosmically timed momentum. Step into the spotlight you were built for.', love: 'Your generosity and warmth are magnetically irresistible this week. Lead with your heart and the right people move toward you naturally.', career: 'Creative direction, performance, leadership, and anything requiring personal authority — all are lit by the Sun\'s expansion. Your confidence alone opens important doors.', health: 'Your heart and spine — the seat of Leo\'s physical power — benefit from movement that builds strength and joy simultaneously. Dance, sport, or anything that makes you feel glorious.' },
    { theme: 'Discipline', overview: 'The rare spectacle of a disciplined Leo produces results that outlast any dramatic gesture. Focus without an audience on the craft underlying your natural talent — what you build in quiet this week carries your legacy.', love: 'Consistency and reliability communicate love in a language your partner has been waiting to hear. Show up. Every time.', career: 'Mastery practice — the unglamorous work of perfecting a skill — creates the platform for your next public success. Saturn rewards the serious Leo now.', health: 'Sustained, moderate effort builds the kind of health that performs under pressure. Establish a weekly rhythm rather than periodic bursts of intensity.' },
    { theme: 'Passion', overview: 'Mars and the Sun combine in rare cooperation, Leo. This is your warrior-king week — decisive, magnetic, and operating at full capacity. The risks you take now are your best calculated ones of the quarter.', love: 'Passionate pursuit, bold declarations, and complete presence make this a memorable week in your romantic story.', career: 'Apply for the role, launch the project, make the ask. Fortune favours the audacious Leo this week without reservation.', health: 'Physical vitality is exceptional. Train hard, play hard, and recover well — your body is responsive and resilient now.' },
    { theme: 'Harmony', overview: 'Venus in your social house creates a golden social period. Collaborations, friendships, and creative partnerships all carry unusual warmth and productivity. Let others shine alongside you — the joint light is greater.', love: 'Romance benefits from shared laughter and creative collaboration rather than drama or intensity. Playfulness is the key that unlocks everything.', career: 'Team dynamics improve dramatically through your sunny, generous leadership. A creative group project produces work that none of you could achieve alone.', health: 'Joy is your medicine. Prioritise pleasure and laughter this week — play is a legitimate and necessary aspect of Leo wellbeing.' },
  ],
  Virgo: [
    { theme: 'Expansion', overview: 'Mercury-ruled Virgo gains extraordinary analytical range this week as Jupiter softens your tendency toward perfectionism. A health or work system you design now impacts hundreds of people positively. Think bigger than you normally allow yourself.', love: 'Opening up about your interior world — imperfect, complex, and genuine — creates the depth of connection you have always wanted.', career: 'Health, wellness, productivity systems, and technical writing fields receive the strongest cosmic endorsement. A solution you devise this week solves a systemic problem.', health: 'Integrative approaches — combining evidence-based and traditional healing — produce remarkable results this week. Your gut microbiome specifically responds to probiotic-rich foods.' },
    { theme: 'Discipline', overview: 'This is Virgo\'s native environment — Saturn and Mercury align to reward meticulous work. The satisfaction of executing a complex project flawlessly is available to you this week. Set the bar high and then clear it cleanly.', love: 'Practical acts of service communicate love with greater eloquence than words. Noticing and addressing a need before it is expressed is your love language at its finest.', career: 'Detail work — analysis, editing, quality control, data — produces results of career-defining quality. A systematic review of a process reveals a saving or improvement of significant value.', health: 'Routine works. A consistent sleep schedule, regular mealtimes, and a daily movement practice transform Virgo\'s nervous system from anxious to serene.' },
    { theme: 'Passion', overview: 'Mars activates your communications sector, Virgo. What has been circling carefully in your mind needs to be spoken aloud with directness and conviction. The thoughtful warrior within you steps forward this week.', love: 'Your usually careful romantic nature gives way to something more direct and surprising. Say what you feel — the response will be worth the vulnerability.', career: 'A direct, assertive approach to a professional negotiation produces a result that the usual careful approach would not have achieved. Stand your ground with facts and conviction.', health: 'Channel physical energy into dynamic, stimulating activity rather than routine exercise. Martial arts, competitive sports, or anything with a clear performance metric inspires you now.' },
    { theme: 'Harmony', overview: 'Venus in your financial sector creates unusual ease around money, beauty, and material wellbeing. A financial arrangement reaches equitable resolution, and creative work receives practical compensation.', love: 'Allowing yourself to receive — appreciation, pleasure, rest — is the romantic skill to develop this week. Your partner wants to nourish you.', career: 'Aesthetic refinement of your professional work — clean design, clear communication, elegant systems — elevates your output from competent to memorable.', health: 'Beauty and order in your environment have a measurable impact on your nervous system. A clean, beautiful workspace is a health intervention for Virgo.' },
  ],
  Libra: [
    { theme: 'Expansion', overview: 'Jupiter in your relationship sector expands the quality and calibre of your partnerships — romantic, business, and social. The people entering your life this week carry unusual significance. Stay open and present.', love: 'A partnership grows in depth, commitment, or joy through a single meaningful gesture or conversation. The conditions for profound connection are exceptionally favourable.', career: 'Business partnerships, contracts, and client relationships all carry expansive potential. A legal or formal agreement made this week is solid and advantageous.', health: 'Your kidneys and lower back respond beautifully to hydration and gentle yoga. The Libra body thrives on balance — find it between activity and rest.' },
    { theme: 'Discipline', overview: 'The Saturn influence that Libra often finds uncomfortable becomes useful this week. The boundaries you establish in relationships — not walls but clear agreements — create the safety in which genuine intimacy can flourish.', love: 'Honest conversations about expectations transform ambiguous connections into clear, committed ones. Clarity is kindness.', career: 'A project requiring sustained, focused effort — something you have been circling — makes decisive progress when you commit to it completely.', health: 'Establish a daily practice that restores your notoriously indecisive nervous system. Even five minutes of meditation or journaling grounds the scales that are always weighing.' },
    { theme: 'Passion', overview: 'Venus and Mars create a rare alliance in your chart, Libra. Beauty with edge. Harmony with fire. The creative and romantic vitality available this week is exceptional — use it before the window closes.', love: 'Your natural charm, amplified by Martian confidence, makes you irresistible. Singles attract with ease; couples reignite chemistry.', career: 'Creative work with commercial potential — design, fashion, music, diplomacy, law — all benefit from this unusually energised period. Pitch something beautiful and bold.', health: 'Movement that engages both body and aesthetic sense — dance, yoga in a beautiful setting, outdoor beauty walks — is specifically restorative for Libra now.' },
    { theme: 'Harmony', overview: 'This is Libra\'s home frequency — and this week the cosmos amplifies it. Every social, aesthetic, and relational sphere of your life reaches a graceful high point. The effort you have put into relationships returns as richly deserved joy.', love: 'This is among the most romantic weeks of your season. Love expressed beautifully lands exactly where you intend.', career: 'Your mediating, harmonising presence resolves a significant team or client tension. The gratitude you receive is genuine and lasting.', health: 'Aesthetic pleasures — beautiful food, refined environments, music — are a form of medicine for Libra. Allow yourself to be fully nourished by beauty.' },
  ],
  Scorpio: [
    { theme: 'Expansion', overview: 'Jupiter illuminates your house of transformation, Scorpio. A research project, investment, or deep psychological work reaches a breakthrough. What you are willing to examine that others avoid is precisely what makes you exceptional.', love: 'Emotional depth and transformative honesty create the kind of intimacy that others only read about. Someone recognises and values your rare emotional courage.', career: 'Research, investigation, psychology, finance, and hidden sectors all receive Jupiter\'s extraordinary endorsement. A discovery this week changes how you approach your work fundamentally.', health: 'Detoxification — physical and emotional — is your most powerful health practice this week. Release what no longer serves; the energy returned is remarkable.' },
    { theme: 'Discipline', overview: 'Saturn in your communication sector asks you to choose your words with surgical precision. The disciplined Scorpio communicator is the most powerful force in any room. A carefully constructed message this week lands with the force of a revelation.', love: 'Trust is built through consistent, reliable behaviour over time — and this week those deposits in your relationship\'s emotional account pay significant interest.', career: 'A complex, long-term project that requires both depth and patience makes crucial progress. Your ability to sustain focus on what others abandon is your career superpower.', health: 'Restorative practices — sleep, deep tissue work, time in water — allow the intense Scorpio energy to process and renew. Recovery is as important as effort.' },
    { theme: 'Passion', overview: 'Mars activates your own sign, Scorpio. This is your season of maximum power, magnetism, and strategic clarity. The bold move you have been calculating is correctly timed — execute it this week.', love: 'Intensity and authenticity combine to create an irresistible magnetic pull. What you feel, expressed directly, electrifies the connection.', career: 'The competitive edge you possess is sharp and accurate this week. A professional confrontation, negotiation, or power dynamic resolves decisively in your favour.', health: 'Your powerful physical machine performs best when given an equally powerful outlet. High-intensity training, cold exposure, or something that pushes your limits cleanly restores you.' },
    { theme: 'Harmony', overview: 'The rare spectacle of a harmonious Scorpio week — Venus softens your intensity into magnetic depth. The creative and relational spheres of your life achieve unusual beauty and resonance.', love: 'Allowing vulnerability without losing power creates a connection of rare and lasting quality. This week, your capacity for depth becomes someone\'s greatest comfort.', career: 'Creative, aesthetic, and collaborative work benefits from your rare combination of intensity and polish. A piece of work produced this week is among your finest.', health: 'Pleasure without guilt — good food, sensory beauty, connection — is genuinely restorative for the Scorpio who often denies themselves comfort as a form of self-discipline.' },
  ],
  Sagittarius: [
    { theme: 'Expansion', overview: 'Jupiter, your ruling planet, expands everything it touches this week with particular enthusiasm. A philosophical insight, academic achievement, or international connection opens a door you have been standing in front of for months. Step through.', love: 'Someone who shares your hunger for meaning and adventure enters or deepens their place in your life. Freedom within commitment is the love model that works for you.', career: 'Publishing, teaching, law, international business, and anything requiring wisdom and breadth of vision all carry exceptional potential. Your arrow of intention flies further than usual.', health: 'The Sagittarius body thrives on movement and wide open spaces. Outdoor exercise, particularly involving distance and elevation, is profoundly healing now.' },
    { theme: 'Discipline', overview: 'The challenge of constraint is the Sagittarian crucible, and Saturn\'s presence this week creates a productive container for your enormous energy. What you complete — rather than begin — carries lasting value.', love: 'Keeping promises and being precisely where you said you would be communicates love in a language your partner values most right now.', career: 'A project requiring rigorous research, detailed planning, or methodical execution produces results that your usual inspired improvisation cannot. Trust the process.', health: 'Your liver and thighs — Sagittarius body zones — benefit from detoxifying foods, consistent hydration, and the particular discipline of stretching what is habitually tight.' },
    { theme: 'Passion', overview: 'Mars fires the Archer\'s arrow with unusual accuracy this week. Your convictions, your ambitions, and your appetite for life all intensify simultaneously. This is a week of genuine forward momentum — lean into it with full commitment.', love: 'Bold, adventurous romantic gestures land beautifully. Plan something that surprises and delights — your partner will talk about it for years.', career: 'Entrepreneurial ventures, new markets, and bold professional bets are all supported. The risk that scares you a little is the one the cosmos is endorsing.', health: 'Physical adventure — trail running, climbing, a new sport — is simultaneously the exercise and the joy that the Sagittarius soul requires.' },
    { theme: 'Harmony', overview: 'Venus softens your fiery nature into a captivating warmth that draws people to you effortlessly this week. Social gatherings, collaborative creativity, and relationship harmony all achieve a peak.', love: 'Philosophical depth and playful warmth combine in your romantic expression to create something genuinely irresistible. You are at your most attractive.', career: 'Team leadership through inspiration rather than direction achieves remarkable results. Your enthusiasm is contagious and your team\'s performance reflects it.', health: 'Balance your fire with water — sufficient hydration, time near rivers or the sea, and calming practices that offset your natural intensity.' },
  ],
  Capricorn: [
    { theme: 'Expansion', overview: 'Jupiter expands your public reputation and career sector, Capricorn. An opportunity that matches your highest professional ambitions arrives — it may look unconventional, but the substance is exactly what you have earned. Recognise it.', love: 'Allowing someone to see your softer, private self beneath the professional exterior creates intimacy of rare and lasting quality.', career: 'Executive leadership, strategic planning, architecture, and any sector requiring long-term vision and structural discipline all carry exceptional promise. You are building a legacy.', health: 'Your skeletal system — joints, knees, teeth — responds well to weight-bearing exercise, calcium-rich nutrition, and the protection of genuine rest.' },
    { theme: 'Discipline', overview: 'This is Capricorn\'s native environment and you operate at your most excellent. The mountain goat at altitude — systematic, powerful, and utterly focused. Build something this week that carries your highest standards.', love: 'The love that endures is built from consistent acts of care, loyalty, and dependable presence. You are demonstrating all three this week.', career: 'A technically demanding project reaches the kind of professional completion that establishes reputations. Do not rush the final details — the difference between good and exceptional is here.', health: 'Structures support Capricorn: a fixed sleep schedule, structured exercise plan, and regular health appointments protect your most important asset.' },
    { theme: 'Passion', overview: 'Mars activates your ambition sector with rare fire, Capricorn. The mountain begins to feel scalable from here. A bold professional move, pursued with your characteristic thoroughness, achieves breakthrough results.', love: 'Your usually measured emotional expression gives way to something surprisingly warm and direct this week — and the response exceeds your expectations.', career: 'Competitive situations resolve in your favour. A negotiation, promotion, or business acquisition is supported by the current planetary energy.', health: 'The Capricorn body responds well to physical challenges that test endurance and strength. A fitness milestone reached this week builds both body and self-concept.' },
    { theme: 'Harmony', overview: 'Venus graces your social and partnership sector, softening the Capricorn tendency to evaluate everything in terms of utility. A relationship valued for its joy alone — not its strategic benefit — nourishes something essential.', love: 'Allow yourself to simply enjoy — without agenda, without productivity, without structure. The capacity for unscheduled pleasure is a skill worth developing.', career: 'Aesthetic and relational skills — presentation, client rapport, creative direction — prove more powerful than technical expertise this week.', health: 'Pleasure, beauty, and genuine rest are not inefficiencies — they are investments in the sustained high performance that Capricorn demands of itself.' },
  ],
  Aquarius: [
    { theme: 'Expansion', overview: 'Jupiter and your innovative nature align this week to produce ideas that are not just ahead of their time — they are precisely on time. A humanitarian project, technological vision, or community initiative receives the backing it deserves.', love: 'A connection built on shared ideals and intellectual excitement deepens into something with real emotional substance. Unique people attract unique love.', career: 'Technology, social innovation, futurism, and any field requiring the synthesis of diverse perspectives all carry exceptional potential. Your unconventional thinking is not a liability — it is the point.', health: 'Your circulatory system and ankles respond well to movement that is dynamic and varied. Eccentric exercise approaches — the unusual ones — suit Aquarius best.' },
    { theme: 'Discipline', overview: 'Saturn, your traditional ruler, asks you to ground your visionary mind in systematic execution this week. The most revolutionary ideas require the most rigorous implementation. Build the infrastructure your innovations deserve.', love: 'Being fully emotionally present — rather than intellectually engaged — is the most radical and nourishing thing you can offer someone this week.', career: 'A long-term project requiring patience, iteration, and systematic development makes the kind of progress that only consistent effort produces. Trust the compound effect.', health: 'Your nervous system, operating at high frequency, needs grounding practices: walking barefoot, spending time in nature, and dramatically reducing digital input.' },
    { theme: 'Passion', overview: 'Mars electrifies your chart with the energy of breakthrough. The Aquarian rebel and the cosmic warrior unite this week for an extraordinary week of productive disruption. Challenge the norm — you are right.', love: 'Your willingness to be unconventional in love — to connect outside the standard script — creates something genuinely remarkable and memorable.', career: 'The bold, disruptive move you have been contemplating has the most favourable conditions for success right now. Revolutionary thinking backed by decisive action.', health: 'Physical intensity channelled into something meaningful — competitive sport, physical activism, demanding training — energises at a cellular level.' },
    { theme: 'Harmony', overview: 'Venus in your social network creates a week of extraordinary human connection. The community you have been building — in person, digitally, intellectually — reveals itself as one of your most profound creations.', love: 'Friendship is the foundation of your best love relationships, and this week the warmth between you and someone significant deepens beautifully.', career: 'Collaborative, networked approaches to creative and professional challenges produce outcomes none of the individuals could achieve alone. Your facilitation is the key.', health: 'Community as medicine — the Aquarius body and spirit both heal within the warmth of genuine human connection. Seek it with intention this week.' },
  ],
  Pisces: [
    { theme: 'Expansion', overview: 'Jupiter in your own sign, Pisces, creates a period of profound spiritual and material expansion. The boundaries between what you imagine and what you create are unusually thin. A creative or compassionate project reaches dimensions that astonish even you.', love: 'Your empathy and emotional attunement reach extraordinary depths this week. You understand what your partner needs before they can articulate it — and you provide it.', career: 'Creative, healing, spiritual, and artistic fields carry exceptional potential. A piece of work produced this week channels something beyond ordinary craft.', health: 'Your lymphatic system and immune strength both respond beautifully to adequate sleep, gentle movement, and time near water. Dreams are especially informative this week.' },
    { theme: 'Discipline', overview: 'Saturn asks the ocean to find its shoreline, Pisces. The boundaries and structures you establish this week do not diminish your depth — they give it direction and power. A spiritual discipline, practised consistently, transforms you.', love: 'Clarity about what you genuinely need from a relationship, communicated with gentle honesty, creates far more intimacy than continued ambiguity.', career: 'Structured, deadline-driven work that requires both imagination and discipline produces results of career-defining quality. Your sensitivity is a professional asset when given clear parameters.', health: 'Establishing fixed daily rhythms — sleep, meals, movement — provides the anchoring that the Piscean nervous system deeply needs.' },
    { theme: 'Passion', overview: 'Mars in your creative sector, Pisces, gives your usually flowing energy a productive directional force. A creative or professional project you have been gestating is ready to be born — launch it this week with full commitment.', love: 'Expressing desire directly — rather than hoping it will be intuited — creates a breakthrough in intimacy. Say what you want; you may be surprised by what arrives.', career: 'Creative courage — the willingness to share work before it feels perfectly ready — is precisely what earns professional recognition this week.', health: 'Aquatic exercise — swimming, water aerobics, or movement near water — is your most restorative and powerful physical practice now.' },
    { theme: 'Harmony', overview: 'Venus in your sign creates a week of magical beauty and human connection. Your natural receptivity and compassion are at their most magnetic — people are drawn to you because they sense, correctly, that you will truly understand them.', love: 'Romance carries an otherworldly quality this week. A connection that began simply reveals surprising depth and potential for lasting meaning.', career: 'Creative, healing, and artistic collaborations reach a peak of productive harmony. Your imaginative input transforms a project that has been missing its soul.', health: 'Immersing yourself in beauty — music, art, nature, ritual — is not an indulgence this week. It is the specific medicine your body and soul require.' },
  ],
};

// ── Monthly data: Jan-Dec per sign ─────────────────────────────────────────────
// Each entry: { overview, love, career, health, lucky: { color, number, day } }
const MONTHLY = {
  Aries: [
    { overview: 'January energises Aries with ambitious clarity. Mars in your career sector drives professional assertiveness to a high point — use it to set the tone for the entire year.', love: 'Venus in your 11th house favours friendships becoming romances. Singles: someone in your social circle sees you in a new light.', career: 'A bold professional proposal lands well. Avoid impulsive financial decisions — review contracts with care before the 15th.', health: 'Your energy is high but your adrenals need post-holiday recovery. Gentle detox, adequate sleep, and reduced sugar sustain your January momentum.', lucky: { color: 'Scarlet', number: 9, day: 'Tuesday' } },
    { overview: 'February brings romantic intensity and unexpected professional opportunities. Mercury direct after the 14th clears communication blocks that have frustrated you for weeks.', love: 'Valentine\'s month amplifies Aries\'s passionate nature. Be direct with your feelings — the response is more positive than your pride expects.', career: 'Innovation and original thinking impress a key decision-maker. A project that combines your natural leadership with creative problem-solving moves forward.', health: 'Your immune system benefits from warming foods, regular exercise, and reduced alcohol. Head and sinus health require attention mid-month.', lucky: { color: 'Red', number: 1, day: 'Tuesday' } },
    { overview: 'March brings your solar return energy, Aries. The Sun in your sign from the 21st begins a period of exceptional vitality, visibility, and personal power. Initiate everything you can.', love: 'Your magnetic confidence attracts romantic opportunity powerfully. Mars in a compatible sign creates chemistry with someone who can match your energy.', career: 'New beginnings in career and business are cosmically endorsed. Projects launched in late March carry extra vitality.', health: 'Peak physical energy arrives with the Sun in Aries. Begin a new fitness regime or sports commitment — your body is receptive and responsive now.', lucky: { color: 'Coral', number: 9, day: 'Tuesday' } },
    { overview: 'April deepens the personal power cycle. Financial sector receives Venus\'s blessing — income opportunities exceed expectations if you act rather than wait.', love: 'Existing relationships deepen through honest conversation about the future. Singles attract through professional confidence and social charisma.', career: 'Earnings and financial negotiations favour bold Aries requests. Ask for what you are worth — the timing is right.', health: 'Spring energises the Aries body profoundly. Outdoor activity and competitive sport both heal and exhilarate you during your peak season.', lucky: { color: 'Orange', number: 3, day: 'Sunday' } },
    { overview: 'May transitions energy from personal to relational. Sibling and communication matters require thoughtful attention. A short journey carries unexpected significance.', love: 'Flirtatious Mercury energy lightens and brightens your romantic connections. Light-hearted, playful interaction opens doors that serious intensity has been closing.', career: 'Writing, speaking, and short-format communication all achieve impressive results. A sibling or close colleague brings valuable professional opportunity.', health: 'Lung and arm health benefit from attention. Breathing exercises and shoulder stretches address Gemini-season tensions in your upper body.', lucky: { color: 'Yellow', number: 5, day: 'Wednesday' } },
    { overview: 'June focuses your energy on home, family, and emotional foundations. A domestic matter that has been unresolved reaches a conclusion — largely favourable with patience.', love: 'Emotional security and domestic harmony form the romantic theme of June. Building a life together — practically, not just conceptually — deepens the bond.', career: 'Real estate, interior design, family business, or any career connected to home and care sectors carry strong potential. Work from home proves highly productive.', health: 'Nurture your digestive system with home-cooked, simple meals. Emotional wellbeing directly influences physical health for Aries more than you usually acknowledge.', lucky: { color: 'Pearl White', number: 2, day: 'Monday' } },
    { overview: 'July brings creative expression and romantic excitement to the forefront. Your natural charisma peaks as the Sun trines your Aries energy. A creative project receives well-deserved recognition.', love: 'Leo season amplifies your fire energy and creates a period of exceptional romantic magnetism and playful joy. Love is fun again — let it be.', career: 'Creative direction, entertainment, entrepreneurship, and anything requiring personal authority all thrive. A speculative investment or creative venture shows early promise.', health: 'Heart health and vitality both benefit from joyful physical activity. Play — not just exercise — is the medicine of July for Aries.', lucky: { color: 'Gold', number: 1, day: 'Sunday' } },
    { overview: 'August activates your service sector. Health habits established this month pay dividends for the rest of the year. Work quality reaches a high point through disciplined attention to detail.', love: 'Practical acts of service — helping with daily needs, solving problems together — communicate love more effectively than grand gestures now.', career: 'Efficiency, systems, and workflow improvements produce remarkable professional results. A health-adjacent or service-oriented opportunity brings both fulfilment and income.', health: 'Your body responds to daily routine, clean diet, and specific supplementation. A health consultation or diagnostic test reveals useful information.', lucky: { color: 'Forest Green', number: 5, day: 'Wednesday' } },
    { overview: 'September activates your 7th house — partnerships of all kinds require attention, negotiation, and investment. A relationship reaches a defining moment; approach it with both honesty and diplomacy.', love: 'A partnership decision — moving in together, becoming official, or resolving a longstanding issue — is on the table. Engage it directly and the outcome is positive.', career: 'Business partnerships, client relationships, and contractual negotiations are all favoured by Venus. A formal agreement made this month is solid.', health: 'Lower back and kidney health benefit from hydration, gentle yoga, and reduced sugar. Libra season asks Aries to slow down and balance.', lucky: { color: 'Pink', number: 6, day: 'Friday' } },
    { overview: 'October intensifies the emotional and financial landscape. Joint resources, inheritance, or investment matters require clear-eyed evaluation. A transformative change is available if you are willing to let go of the old.', love: 'Deep emotional intimacy is available through vulnerability and trust. Scorpio season rewards those willing to go beneath the surface.', career: 'Research, investigation, finance, and transformative fields carry strong potential. A financial restructuring benefits you more than it initially appears.', health: 'Detoxification and elimination are October\'s themes. A targeted cleanse — physical, emotional, or both — creates significant gains in vitality.', lucky: { color: 'Deep Red', number: 9, day: 'Tuesday' } },
    { overview: 'November expands your horizons through philosophical inquiry, travel, and higher education. Jupiter\'s influence in your chart grows stronger — opportunities are both large and genuine.', love: 'An adventurous, intellectually stimulating connection captures your heart. Existing partners benefit from genuine conversations about shared vision and values.', career: 'International connections, publishing, legal matters, and educational ventures all carry exceptional promise. Think bigger than your local market.', health: 'Hips and thighs benefit from stretching and movement. Sagittarius season invigorates your fire, but watch for overextension and burnout.', lucky: { color: 'Purple', number: 3, day: 'Thursday' } },
    { overview: 'December asks you to consolidate the remarkable gains of the year, Aries. Career matters reach important milestones as Saturn rewards the year\'s disciplined effort. Year-end reflections reveal how far you have actually come.', love: 'The holiday season amplifies Aries\'s warmth and generosity. Grand, memorable gestures of love create lasting impressions.', career: 'Capricorn season rewards structured, serious professional effort with recognition and tangible advancement. Year-end performance reviews favour you.', health: 'Resist the holiday excess that depletes January. A December commitment to basic self-care — sleep, hydration, movement — sets a powerful precedent for the new year.', lucky: { color: 'Black', number: 8, day: 'Saturday' } },
  ],
  Taurus: [
    { overview: 'January grounds Taurus in purposeful, practical momentum. Saturn activates your sector of long-term vision — a multi-year plan takes on tangible structure this month.', love: 'Venus in your 9th house draws philosophical connection and travel romance. A foreign or culturally different person captures your attention.', career: 'Long-term financial planning, property, and value-creation projects all receive Saturn\'s most productive endorsement of the year.', health: 'Your January constitution benefits from warming herbs, gentle movement, and vitamin D supplementation during the darker months.', lucky: { color: 'Forest Green', number: 6, day: 'Friday' } },
    { overview: 'February intensifies your social networks and future visions. A community initiative or group project reveals itself as more significant than it first appeared.', love: 'An unexpected romantic connection emerges from a group context — a class, an event, or a community you belong to. Unusual attraction is real.', career: 'Group projects and community-oriented ventures carry strong potential. Technology and innovation fields reward Taurus\'s patient approach with concrete returns.', health: 'Circulatory health benefits from regular walking, stretching, and reduced sedentary time. The Taurus tendency toward stillness needs deliberate movement intervention.', lucky: { color: 'Electric Blue', number: 4, day: 'Saturday' } },
    { overview: 'March activates your spiritual sector — a period of deep reflection and conscious letting-go before the solar return. What you release creates space for extraordinary April arrivals.', love: 'An old connection resurfaces with new potential — or completes its resolution. Either outcome is exactly right.', career: 'Behind-the-scenes work, research, and preparation bear fruit later. The strategic groundwork laid in March delivers significant March-June returns.', health: 'Sleep quality and dream life are particularly informative this month. Yoga nidra, meditation, and time alone in nature are medicine.', lucky: { color: 'Sea Green', number: 7, day: 'Thursday' } },
    { overview: 'April launches your solar return cycle, Taurus. The Sun in your sign from the 20th begins your most vital, magnetic, and productive period of the year. Initiate everything meaningful.', love: 'You are at your most physically attractive and emotionally grounded — a deeply appealing combination. Love, in whatever form it takes, arrives through your natural warmth.', career: 'A fresh career initiative receives full solar backing. Projects launched in late April carry the stamp of the entire Taurus year.', health: 'Your peak vitality window opens with the Sun in your sign. Establish a health practice now that you will maintain — your body is most receptive.', lucky: { color: 'Emerald', number: 6, day: 'Friday' } },
    { overview: 'May deepens the personal power cycle. Financial opportunities are abundant and your discernment — usually excellent — is at its sharpest. An investment made in May proves wisely timed.', love: 'Sensory pleasure and physical presence form the backbone of romantic fulfilment. Create beautiful, tactile experiences for and with your partner.', career: 'Earnings, financial negotiations, and income opportunities all peak in May. Ask for the raise, set the rate, or price the product — timing is optimal.', health: 'Your Taurus constitution peaks in your own season. An indulgence in genuinely nourishing food, rest, and beauty is not decadence — it is seasonal wisdom.', lucky: { color: 'Rose Gold', number: 6, day: 'Friday' } },
    { overview: 'June activates your 3rd house of communication and short travel. A sibling relationship, neighbourhood connection, or local community matter carries surprising importance.', love: 'Playful, curious, and intellectually stimulating interaction lights up your love life in ways that pure physical comfort cannot. Communicate more — share what you find fascinating.', career: 'Writing, speaking, teaching, and communication-focused roles produce strong results. A local or digital media opportunity expands your reach.', health: 'Lung health benefits from breathing exercises and clean air. A short trip or change of scene refreshes the Taurus nervous system remarkably.', lucky: { color: 'Turquoise', number: 5, day: 'Wednesday' } },
    { overview: 'July deepens your emotional and family roots. A domestic project or property matter that has been gestating is ready for concrete action. Home is both your sanctuary and your strategic asset.', love: 'Nesting, creating home together, and nurturing daily rituals build the kind of love that sustains across decades. Your domestic investment pays romantic dividends.', career: 'Real estate, home-based business, and family enterprise all receive strong support. Working from home produces quality results.', health: 'Your digestive wellbeing is in focus. Home-cooked, seasonal foods and emotional security both contribute to the gut health Taurus relies on.', lucky: { color: 'Silver', number: 2, day: 'Monday' } },
    { overview: 'August brings creative confidence and romantic warmth to the Taurus chart. A creative project or personal expression receives recognition that validates months of effort.', love: 'Romance becomes playful, generous, and expansive. Plan something genuinely special — Taurus\'s capacity for sensory experience is a romantic superpower.', career: 'Creative, artistic, and aesthetic fields all achieve peak quality output. An entrepreneurial or speculative venture shows early, promising returns.', health: 'Joyful movement — dancing, sports you enjoy, anything that produces physical delight — is August\'s medicine for Taurus. Exercise should not be a punishment.', lucky: { color: 'Amber', number: 1, day: 'Sunday' } },
    { overview: 'September focuses your analytical and health-oriented energy. Work quality benefits from Virgo season\'s precision. A health habit established in September compounds strongly.', love: 'Practical care and reliable daily presence communicate love in a language your partner hears deeply this month.', career: 'Detailed analysis, quality improvement, and systematic problem-solving produce outstanding professional results. Your thoroughness earns specific recognition.', health: 'Gut health, nutrition, and daily movement routine all benefit from September\'s focused attention. A specific health upgrade pays dividends for months.', lucky: { color: 'Brown', number: 5, day: 'Wednesday' } },
    { overview: 'October opens your relationship sector with exceptional romantic and business partnership potential. A significant connection — romantic, creative, or professional — reaches a defining moment.', love: 'A partnership commitment — or clarification of where things stand — produces peace and forward motion. Avoidance costs more than honesty.', career: 'Business partnerships, contractual agreements, and client-facing work all carry strong potential. A formal collaboration made in October proves durable.', health: 'Lower back and kidney health — particularly sensitive for Taurus — benefit from hydration and gentle yoga. Libra season asks you to find and maintain balance.', lucky: { color: 'Pink', number: 6, day: 'Friday' } },
    { overview: 'November intensifies your experience of shared resources and deep emotional connection. A financial restructuring or joint investment decision requires careful, clear-eyed evaluation.', love: 'Depth, trust, and emotional honesty produce breakthroughs in intimacy that lighter engagement cannot reach. Scorpio season rewards Taurus\'s capacity for loyal depth.', career: 'Finance, investment, research, and transformative fields all carry significant potential. A shared financial arrangement benefits from precise renegotiation.', health: 'Detoxification — liver, colon, and lymphatic — produces significant vitality gains. A focused cleanse matched with emotional processing amplifies the result.', lucky: { color: 'Maroon', number: 8, day: 'Saturday' } },
    { overview: 'December completes the year with partnership focus and relational warmth. A meaningful connection — personal or professional — reaches a beautiful conclusion or a committed new beginning.', love: 'The festive season amplifies Taurus\'s natural warmth and sensory generosity. A romantic gesture rooted in genuine care and beauty creates a lasting December memory.', career: 'Capricorn season rewards Taurus\'s natural alignment with structure and value. Year-end recognition reflects the quality of consistent, excellent work.', health: 'Rest, good food, and genuine social connection are the specific medicine of December. Resist the depletion that the holiday season can bring with intentional restoration.', lucky: { color: 'Deep Green', number: 6, day: 'Friday' } },
  ],
};

// Add remaining 10 signs using compact form to avoid file length issues
const SIGN_MONTHLY_TEMPLATE = (sign, ruler, element, bodyPart) => [
  { overview: `January grounds ${sign} in purposeful intention. ${ruler}'s influence supports long-term planning and career foundations built to last.`, love: 'A cold-season romance deepens through shared warmth, honest conversation, and genuine presence.', career: 'Strategic planning and foundational work receive the strongest return on investment. A professional goal clarified now guides your entire year.', health: `Your ${bodyPart} health benefits from January attention to routine, warmth, and adequate vitamin intake.`, lucky: { color: 'Navy Blue', number: 8, day: 'Saturday' } },
  { overview: `February activates ${sign}'s social and innovative sector. Unexpected connections carry professional and personal significance beyond their initial appearance.`, love: 'An intellectually stimulating or unconventional connection challenges and excites you. Genuine friendship underlies the best February romance.', career: 'Technology, collaboration, and community initiatives produce strong results. An unusual idea deserves serious consideration and a genuine trial.', health: 'Circulatory health, ankles, and the nervous system all benefit from regular movement and deliberate digital detox periods.', lucky: { color: 'Electric Blue', number: 4, day: 'Saturday' } },
  { overview: `March activates ${sign}'s intuitive and reflective depths. A creative or spiritual breakthrough arrives through stillness rather than striving.`, love: 'An existing bond deepens through compassionate listening and the courage to be genuinely known.', career: 'Behind-the-scenes preparation, research, and strategic reflection produce results that surface in Q2. Trust the invisible work.', health: 'Sleep, meditation, and lymphatic support are March\'s most valuable health investments for your sign.', lucky: { color: 'Sea Green', number: 7, day: 'Thursday' } },
  { overview: `April marks a turning point in ${sign}'s year. Fresh energy, new beginnings, and a renewed sense of personal direction all arrive with the spring.`, love: 'New romantic energy arrives — either a new person or a newly energised existing connection. Spring renews what winter quieted.', career: `A fresh professional initiative, perfectly aligned with ${sign}'s ${element} nature, receives excellent early momentum.`, health: 'Spring vitality is high and receptive. Begin a new health commitment or physical practice — your body will respond enthusiastically.', lucky: { color: 'Spring Green', number: 1, day: 'Sunday' } },
  { overview: `May energises ${sign}'s financial and resource sector. Multiple income opportunities emerge; discernment determines which carry genuine long-term value.`, love: 'Sensory pleasures and material security both contribute to romantic contentment. Invest in shared experiences that nourish the senses.', career: 'Earnings, pricing, and financial negotiations all favour bold and well-prepared approaches. Ask for what your work is genuinely worth.', health: `Throat and neck (for ${element} signs), or your particular ${bodyPart} zone, respond well to targeted attention and consistent care.`, lucky: { color: 'Emerald', number: 6, day: 'Friday' } },
  { overview: `June activates ${sign}'s communication, learning, and immediate community. A local or intellectual connection carries significance beyond its apparent scope.`, love: 'Playful, curious communication transforms a familiar connection. Share what genuinely interests you — authentic enthusiasm is magnetic.', career: 'Writing, teaching, speaking, and local or digital media all carry strong June potential. Your voice deserves a wider audience.', health: 'Respiratory health, mental agility, and nervous system regulation all benefit from June\'s focus on breath, movement, and mental variety.', lucky: { color: 'Yellow', number: 5, day: 'Wednesday' } },
  { overview: `July centres ${sign}'s energy on home, family, and emotional foundations. A domestic matter reaches resolution; a family connection deepens with significance.`, love: 'Nurturing daily rituals and emotional safety build the kind of love that sustains across time. Home is where your heart\'s best work happens.', career: 'Home-based work, real estate, family enterprise, and career connected to nourishment or care sectors all produce strong July results.', health: 'Emotional wellbeing directly influences physical health this month. Address the feeling beneath the symptom for the most effective healing.', lucky: { color: 'Silver', number: 2, day: 'Monday' } },
  { overview: `August brings ${sign}'s creative and expressive energies to a brilliant high point. A creative project receives recognition; a personal expression finds its audience.`, love: 'Romance is playful, warm, and generative in August. Allow yourself to be pursued as well as to pursue — both are available to you now.', career: 'Creative, entrepreneurial, and performance-related fields all achieve peak output in August. An original project demonstrates its full value.', health: `Heart health and vitality both respond to joyful physical activity. Play — structured sport, dance, creative movement — is ${sign}'s best August medicine.`, lucky: { color: 'Gold', number: 1, day: 'Sunday' } },
  { overview: `September focuses ${sign}'s energy on service, health systems, and work quality. Habits established this month compound remarkably over the final quarter.`, love: 'Practical daily care and reliable, competent presence communicate love with clarity and warmth. Service is your September love language.', career: 'Analytical and systems-focused work produces outstanding results. A workflow improvement creates time and quality gains simultaneously.', health: 'Gut health, daily movement routine, and targeted nutrition all benefit from September\'s Virgo-season focus and discipline.', lucky: { color: 'Forest Green', number: 5, day: 'Wednesday' } },
  { overview: `October energises ${sign}'s relationship and partnership sector. A significant connection — romantic, creative, or professional — reaches a defining and positive moment.`, love: 'Partnership commitments and honest conversations about the future carry exceptional potential this month. Engage directly for the best outcome.', career: 'Client relationships, business partnerships, and contractual arrangements all carry strong potential. A collaborative project produces impressive results.', health: 'Lower back health, kidney function, and hormonal balance all benefit from hydration, gentle yoga, and dietary refinement.', lucky: { color: 'Pink', number: 6, day: 'Friday' } },
  { overview: `November deepens ${sign}'s experience of transformation, joint resources, and emotional intensity. A financial or relational decision made with clarity produces lasting benefit.`, love: 'Emotional depth and vulnerability create breakthroughs in intimacy that comfortable patterns cannot access. Go deeper.', career: 'Finance, investment, research, and transformative professional fields all carry significant November potential for your sign.', health: 'Detox, regeneration, and deep tissue health all benefit from November\'s transformative energy. Release what no longer serves your vitality.', lucky: { color: 'Deep Red', number: 8, day: 'Tuesday' } },
  { overview: `December completes ${sign}'s year with expansion, wisdom, and a clear-eyed view of how far you have actually come. Celebrate what matters; release what didn't serve you.`, love: 'The festive season amplifies warmth and generosity. A meaningful romantic gesture or heartfelt conversation creates a December memory worth keeping.', career: 'Year-end recognition reflects the consistent quality of your work. Capricorn season rewards structured, serious professional effort.', health: 'Deliberate restoration over holiday excess. Sleep, nourishing food, and genuine social connection are your most important December investments.', lucky: { color: 'Midnight Blue', number: 8, day: 'Saturday' } },
];

// Fill remaining signs
['Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'].forEach(sign => {
  const INFO = {
    Gemini:      { ruler:'Mercury', element:'air',   bodyPart:'lungs and arms' },
    Cancer:      { ruler:'Moon',    element:'water',  bodyPart:'stomach and chest' },
    Leo:         { ruler:'Sun',     element:'fire',   bodyPart:'heart and spine' },
    Virgo:       { ruler:'Mercury', element:'earth',  bodyPart:'digestive system' },
    Libra:       { ruler:'Venus',   element:'air',   bodyPart:'kidneys and lower back' },
    Scorpio:     { ruler:'Mars',    element:'water',  bodyPart:'reproductive system' },
    Sagittarius: { ruler:'Jupiter', element:'fire',   bodyPart:'hips and thighs' },
    Capricorn:   { ruler:'Saturn',  element:'earth',  bodyPart:'knees and skeletal system' },
    Aquarius:    { ruler:'Saturn',  element:'air',   bodyPart:'ankles and circulation' },
    Pisces:      { ruler:'Jupiter', element:'water',  bodyPart:'feet and lymphatic system' },
  };
  const { ruler, element, bodyPart } = INFO[sign];
  MONTHLY[sign] = SIGN_MONTHLY_TEMPLATE(sign, ruler, element, bodyPart);
});

// ── Yearly data: 2026 ──────────────────────────────────────────────────────────
const YEARLY = {
  2026: {
    Aries:       { overview: '2026 is a year of earned visibility and strategic boldness for Aries. Saturn in Pisces through your 12th house completes its cycle of spiritual preparation, while Jupiter\'s transit through Gemini energises your 3rd house of communication and commerce. By mid-year, Jupiter moves to Cancer and your domestic sector, creating a beautiful period of home expansion and emotional security. Career advancement is significant in Q1 and Q4. Health: consistent routines established in the first quarter sustain you through an active year.', quarters: ['Q1: Career and public reputation peak — seize professional momentum', 'Q2: Communication, contracts, and short journeys expand your world', 'Q3: Home, family, and emotional foundations receive Jupiter\'s blessing', 'Q4: Creative expression and romance reach a brilliant year-end peak'], lucky: { color: 'Red', number: 9, gemstone: 'Red Coral' } },
    Taurus:      { overview: '2026 is a year of financial restructuring and relationship deepening for Taurus. Saturn in Pisces activates your 11th house of social networks and future vision, while Jupiter in Gemini energises your 2nd house of earned income — a genuinely positive combination for financial growth. Your relationships reach a maturity and depth that earlier years prepared you for. A property decision in the middle of the year proves well-timed. Health focus: throat and thyroid.', quarters: ['Q1: Financial planning and social network expansion both accelerate', 'Q2: Earnings peak — an income opportunity exceeds expectations', 'Q3: Home and property investment opportunities arrive', 'Q4: Partnership and relationship matters reach defining moments'], lucky: { color: 'Green', number: 6, gemstone: 'Diamond' } },
    Gemini:      { overview: '2026 is Gemini\'s breakthrough year. Jupiter in your own sign through the first half creates a period of expansion across all life areas simultaneously — career, learning, relationships, and personal development all receive the gas simultaneously. Saturn in your 10th house career sector demands disciplined ambition while rewarding it generously. By mid-year, as Jupiter moves to Cancer, your financial sector activates with unusual earning potential. A landmark year.', quarters: ['Q1: Personal expansion and self-development receive Jupiter\'s full blessing', 'Q2: Career demands increase — Saturn and Jupiter create a productive tension', 'Q3: Financial sector activates significantly as Jupiter moves to Cancer', 'Q4: Learning, travel, and philosophical expansion broaden your world'], lucky: { color: 'Yellow', number: 5, gemstone: 'Emerald' } },
    Cancer:      { overview: '2026 is a year of deep internal growth and eventual external manifestation for Cancer. Saturn in your 9th house asks you to build a genuine philosophical or educational foundation, while Jupiter moves through your 12th house in the first half — a period of spiritual deepening and productive solitude. By mid-year, Jupiter enters your own sign and the year transforms dramatically, ushering in a landmark period of personal expansion, opportunity, and recognition.', quarters: ['Q1: Spiritual growth, research, and hidden work produce foundational insights', 'Q2: Education or belief system restructuring creates a stronger life compass', 'Q3: Jupiter enters your sign — personal breakthrough and significant opportunity', 'Q4: Financial and resource growth follow naturally from mid-year expansion'], lucky: { color: 'Pearl White', number: 2, gemstone: 'Pearl' } },
    Leo:         { overview: '2026 brings Leo to a social and professional high point. Jupiter in Gemini activates your 11th house of networks, friendships, and future vision — a period of extraordinary social expansion and community building. Saturn in your 8th house asks you to handle shared resources and transformative processes with maturity and precision. By mid-year, Jupiter moves to your 12th house, inviting a period of spiritual preparation for the remarkable personal expansion coming in 2027.', quarters: ['Q1: Social network expands with unusual speed and quality', 'Q2: A group initiative or community project reaches significant scale', 'Q3: Spiritual and inner growth creates the foundation for future expansion', 'Q4: Career and public reputation benefit from the year\'s social capital'], lucky: { color: 'Gold', number: 1, gemstone: 'Ruby' } },
    Virgo:       { overview: '2026 is a career-defining year for Virgo. Jupiter in Gemini activates your 10th house of public reputation and professional achievement — the most career-positive Jupiter transit in 12 years. Saturn in your 7th house asks you to build partnerships with realistic expectations and genuine commitments. A professional achievement in Q2 or Q3 reflects years of accumulated excellence. Relationships that survive this year\'s honest scrutiny are exactly worth keeping.', quarters: ['Q1: Career strategy solidifies — position yourself for the Q2-Q3 peak', 'Q2: Professional recognition and opportunity reach an exceptional peak', 'Q3: A career milestone that will be remembered; business partnerships formalise', 'Q4: Financial rewards from career success expand income and opportunity'], lucky: { color: 'Forest Green', number: 5, gemstone: 'Emerald' } },
    Libra:       { overview: '2026 expands Libra\'s philosophical and educational horizons in remarkable ways. Jupiter in Gemini activates your 9th house of wisdom, travel, and higher learning — the ideal transit for completing a degree, writing a book, or establishing yourself as an expert in your field. Saturn in your 6th house demands health discipline and professional service quality. A significant journey — geographical or intellectual — reshapes your understanding of what is possible for you.', quarters: ['Q1: Educational pursuit or philosophical inquiry accelerates meaningfully', 'Q2: A travel opportunity or international connection carries career significance', 'Q3: Legal or publishing matter resolves significantly in your favour', 'Q4: Career and partnership benefits from the year\'s expanded knowledge base'], lucky: { color: 'Pink', number: 6, gemstone: 'Diamond' } },
    Scorpio:     { overview: '2026 is a year of powerful transformation and financial regeneration for Scorpio. Jupiter in Gemini activates your 8th house of shared resources, research, and deep investigation — an exceptional period for financial negotiation, investment, and uncovering hidden value. Saturn in your 5th house asks you to build creative and romantic commitments with seriousness and patience. A financial decision made in the first half of the year proves more significant than its initial appearance suggests.', quarters: ['Q1: Research and investigation yield extraordinary findings', 'Q2: Financial negotiation, investment, or inheritance matters resolve well', 'Q3: Creative work receives serious acknowledgement and material reward', 'Q4: Partnership and relationship depth reaches a new, lasting level'], lucky: { color: 'Deep Red', number: 9, gemstone: 'Red Coral' } },
    Sagittarius: { overview: '2026 brings Sagittarius to a partnership peak of unusual quality and significance. Jupiter in Gemini activates your 7th house of relationships — the most relationship-positive transit of the 12-year Jupiter cycle. A significant partnership, romantic or professional, either begins or deepens into genuine commitment. Saturn in your 4th house asks you to create genuine domestic stability and family structures that endure. A year of meaningful human connection and purposeful commitment.', quarters: ['Q1: Relationship clarity arrives — a significant connection defines itself', 'Q2: Partnership commitment, business alliance, or deep romantic development', 'Q3: Domestic foundations become the secure base for external expansion', 'Q4: Philosophical and educational expansion creates a powerful year-end renaissance'], lucky: { color: 'Purple', number: 3, gemstone: 'Yellow Sapphire' } },
    Capricorn:   { overview: '2026 is a health, service, and professional quality year for Capricorn. Jupiter in Gemini activates your 6th house of daily work and health — supporting productive professional systems and genuine wellness improvements. Saturn in your 3rd house demands disciplined communication and structured learning. The hard work of earlier years pays increasingly visible dividends in Q3 and Q4. A landmark health habit or professional system established in H1 serves you for years.', quarters: ['Q1: Health system and professional workflow both receive transformative upgrades', 'Q2: Service quality reaches a career high point with measurable recognition', 'Q3: Career momentum from Q1-Q2 efforts produces significant recognition', 'Q4: Relationship and partnership sectors benefit from the year\'s earned stability'], lucky: { color: 'Dark Green', number: 8, gemstone: 'Blue Sapphire' } },
    Aquarius:    { overview: '2026 is one of Aquarius\'s most creatively productive and romantically exciting years in over a decade. Jupiter in Gemini activates your 5th house of creativity, romance, and self-expression — an exceptional period for artistic output, entrepreneurial ventures, and genuine love. Saturn in your 2nd house asks you to build financial structures that match your vision. A creative project or romantic development this year carries significance you will recognise more fully in hindsight.', quarters: ['Q1: Creative energy is exceptional — begin the project you have been imagining', 'Q2: Romantic and creative peaks both arrive; an entrepreneurial venture shows promise', 'Q3: Financial structures catch up with creative expansion; earnings improve', 'Q4: Social and community recognition for creative work produces lasting platform'], lucky: { color: 'Electric Blue', number: 4, gemstone: 'Blue Sapphire' } },
    Pisces:      { overview: '2026 is a domestic and emotional renaissance year for Pisces. Jupiter in Gemini activates your 4th house of home, family, and roots — a period of genuine domestic expansion, property opportunity, and emotional healing of family matters. Saturn in your own sign has been teaching you profound self-discipline since 2023 — 2026 is where that difficult work begins to show unmistakable results. A property decision or family development in H1 proves foundational.', quarters: ['Q1: Domestic opportunity, family resolution, or property decision arrives', 'Q2: Emotional foundations strengthen; creative and spiritual work flourishes at home', 'Q3: Career benefits from the emotional stability built in H1', 'Q4: Relationship expansion and social recognition complete a transformative year'], lucky: { color: 'Sea Green', number: 7, gemstone: 'Yellow Sapphire' } },
  },
  2027: {
    Aries:       { overview: '2027 brings Aries to an emotional and domestic peak. Jupiter in Cancer activates your 4th house for the first half — property decisions prove well-timed and family connections deepen. A creative Renaissance arrives as Jupiter moves into Leo by mid-year, activating your 5th house for one of your most creatively expressive periods in over a decade.', quarters: ['Q1: Domestic expansion and family growth', 'Q2: Property investment proves timely', 'Q3: Creative and romantic peaks as Jupiter enters Leo', 'Q4: Artistic recognition and entrepreneurial success'], lucky: { color: 'Coral', number: 9, gemstone: 'Red Coral' } },
    Taurus:      { overview: '2027 activates Taurus\'s 3rd house through Jupiter in Cancer, creating a year of brilliant communication, local community significance, and expanded learning. A course of study, book project, or communications platform built in 2027 carries lasting professional value. Mid-year brings Jupiter into Leo and your 4th house — a period of domestic happiness and family expansion.', quarters: ['Q1: Communication, writing, and local connections expand significantly', 'Q2: Educational pursuit or certification completes with excellent results', 'Q3: Domestic happiness and family expansion as Jupiter shifts to Leo', 'Q4: Creative and romantic developments reward the year\'s growth'], lucky: { color: 'Emerald', number: 6, gemstone: 'Diamond' } },
    Gemini:      { overview: '2027 places Gemini\'s focus on financial growth and personal values as Jupiter moves through Cancer and your 2nd house. Income opportunities multiply and a financial foundation built in 2027 supports the next decade. By mid-year, Jupiter enters Leo and activates your 3rd house of communication — a period of exceptional intellectual productivity and short-form creative success.', quarters: ['Q1: Financial opportunity multiplies; income streams diversify', 'Q2: A significant earning opportunity exceeds expectations', 'Q3: Communication, writing, and speaking career accelerates', 'Q4: Educational and philosophical expansion rounds out the year'], lucky: { color: 'Yellow', number: 5, gemstone: 'Emerald' } },
    Cancer:      { overview: '2027 is Cancer\'s personal breakthrough year. Jupiter in your own sign through mid-year creates the most expansive personal development period of the 12-year cycle. Self-confidence, opportunity, and recognition all peak simultaneously. Health improves, relationships flourish, and professional advancement arrives without the struggle of previous years. By mid-year, Jupiter in Leo activates your income sector — a financial peak follows the personal breakthrough.', quarters: ['Q1: Personal expansion and self-development reach their peak', 'Q2: Career recognition and relationship depth both increase dramatically', 'Q3: Financial sector activates powerfully as Jupiter moves to Leo', 'Q4: Income growth and material security consolidate the year\'s gains'], lucky: { color: 'Pearl White', number: 2, gemstone: 'Pearl' } },
    Leo:         { overview: '2027 is Leo\'s spiritual preparation year in H1, followed by a magnificent personal breakthrough as Jupiter enters your own sign in mid-year. The first half spent in quiet inner work and creative contemplation produces the raw material for the Jupiter-in-Leo breakthrough that follows. When it arrives, you are ready — and the results are exceptional.', quarters: ['Q1: Spiritual growth, creative incubation, and inner preparation', 'Q2: Hidden work surfaces into recognition; solo projects shine', 'Q3: Jupiter enters Leo — personal breakthrough and extraordinary opportunity', 'Q4: Financial and career rewards from the Jupiter-in-Leo expansion'], lucky: { color: 'Gold', number: 1, gemstone: 'Ruby' } },
    Virgo:       { overview: '2027 brings extraordinary social and communal expansion to Virgo. Jupiter in Cancer activates your 11th house of networks and future vision. A community initiative or professional network built in 2027 carries lasting significance. Mid-year, Jupiter enters Leo and activates your 12th house — a period of spiritual deepening and retreat that prepares you for the remarkable personal breakthrough of 2028.', quarters: ['Q1: Social network expands with unusual quality and speed', 'Q2: A group initiative or collaborative project reaches significant scale', 'Q3: Spiritual and creative preparation; inner work produces outer gold', 'Q4: Career benefits from the year\'s extraordinary social capital'], lucky: { color: 'Forest Green', number: 5, gemstone: 'Emerald' } },
    Libra:       { overview: '2027 places career and public reputation at the centre of the Libra story. Jupiter in Cancer activates your 10th house — one of the most career-positive Jupiter transits in 12 years. A professional achievement in Q1 or Q2 reflects years of accumulated excellence and becomes a public milestone. By mid-year, as Jupiter moves to Leo and your 11th house, social networks amplify the year\'s career success.', quarters: ['Q1: Career advancement and public recognition reach an exceptional peak', 'Q2: A professional milestone that will be remembered for years', 'Q3: Social and professional network expands around career success', 'Q4: Financial rewards and partnership benefits from the year\'s recognition'], lucky: { color: 'Pink', number: 6, gemstone: 'Diamond' } },
    Scorpio:     { overview: '2027 expands Scorpio\'s philosophical, educational, and international horizons. Jupiter in Cancer activates your 9th house — the ideal transit for higher education, writing a significant work, establishing expertise, or an important international connection. A journey — literal or intellectual — in 2027 reshapes your understanding of what your life can encompass.', quarters: ['Q1: Educational or philosophical pursuit accelerates meaningfully', 'Q2: International connection or significant travel carries professional impact', 'Q3: A legal, publishing, or expertise-based achievement arrives', 'Q4: Career and financial benefits from the year\'s expanded worldview'], lucky: { color: 'Deep Red', number: 9, gemstone: 'Red Coral' } },
    Sagittarius: { overview: '2027 is a year of powerful financial transformation and deep relationship trust for Sagittarius. Jupiter in Cancer activates your 8th house — an exceptional period for financial negotiation, investment, and uncovering hidden sources of value. By mid-year, Jupiter enters Leo and activates your 9th house — your native territory of wisdom, adventure, and higher learning — producing a genuinely expansive year-end Renaissance.', quarters: ['Q1: Financial restructuring and investment produce significant gains', 'Q2: Joint financial arrangements improve markedly; research yields breakthroughs', 'Q3: Philosophical and educational expansion as Jupiter enters Leo', 'Q4: International connection, teaching, or publishing achieves meaningful scale'], lucky: { color: 'Purple', number: 3, gemstone: 'Yellow Sapphire' } },
    Capricorn:   { overview: '2027 is a relationship and partnership peak year for Capricorn. Jupiter in Cancer activates your 7th house — the most relationship-positive Jupiter transit of the 12-year cycle. A significant commitment in 2027, whether romantic or professional, proves foundational to everything that follows. The discipline of previous years has made you genuinely ready for the depth of partnership that this year brings.', quarters: ['Q1: Partnership clarity arrives; a significant commitment takes shape', 'Q2: Romantic depth or business alliance reaches genuine commitment', 'Q3: Public career momentum builds from the stability of H1 partnerships', 'Q4: Financial and communal rewards follow the year\'s relationship investments'], lucky: { color: 'Dark Green', number: 8, gemstone: 'Blue Sapphire' } },
    Aquarius:    { overview: '2027 is a health, service, and professional quality year of exceptional significance for Aquarius. Jupiter in Cancer activates your 6th house — health systems and professional workflows both transform for the better. A wellbeing practice established in 2027 becomes foundational. By mid-year, Jupiter in Leo activates your 7th house of partnerships — a significant relationship chapter begins.', quarters: ['Q1: Health upgrade and professional system transformation', 'Q2: Service quality and professional excellence reach career-high recognition', 'Q3: Partnership sector activates as Jupiter moves to Leo', 'Q4: Relationship commitment or business alliance proves foundational'], lucky: { color: 'Electric Blue', number: 4, gemstone: 'Blue Sapphire' } },
    Pisces:      { overview: '2027 activates Pisces\'s creative, romantic, and entrepreneurial sectors with rare Jupiter intensity. Jupiter in Cancer activates your 5th house — one of your most creatively inspired and romantically exciting periods in over a decade. A creative project, romantic chapter, or entrepreneurial venture in 2027 carries lasting significance. By mid-year, Jupiter in Leo activates your 6th house — health and professional quality both benefit from this abundant creative energy.', quarters: ['Q1: Creative inspiration reaches an extraordinary high point', 'Q2: Romantic development and entrepreneurial breakthrough arrive together', 'Q3: Health and professional quality both benefit from Jupiter in Leo', 'Q4: Recognition for creative work produces lasting platform and opportunity'], lucky: { color: 'Sea Green', number: 7, gemstone: 'Yellow Sapphire' } },
  },
};

// ── Weekly lucky factors (by sign — no per-theme variation needed) ─────────────
const SIGN_LUCKY = {
  Aries:       { color: 'Red',           number: 9, day: 'Tuesday' },
  Taurus:      { color: 'Green',         number: 6, day: 'Friday' },
  Gemini:      { color: 'Yellow',        number: 5, day: 'Wednesday' },
  Cancer:      { color: 'Pearl White',   number: 2, day: 'Monday' },
  Leo:         { color: 'Gold',          number: 1, day: 'Sunday' },
  Virgo:       { color: 'Forest Green',  number: 5, day: 'Wednesday' },
  Libra:       { color: 'Pink',          number: 6, day: 'Friday' },
  Scorpio:     { color: 'Deep Red',      number: 9, day: 'Tuesday' },
  Sagittarius: { color: 'Purple',        number: 3, day: 'Thursday' },
  Capricorn:   { color: 'Dark Green',    number: 8, day: 'Saturday' },
  Aquarius:    { color: 'Electric Blue', number: 4, day: 'Saturday' },
  Pisces:      { color: 'Sea Green',     number: 7, day: 'Thursday' },
};

// ── Helpers ────────────────────────────────────────────────────────────────────
const {
  THEME_HINDI, SIGN_HINDI, RULER_HINDI, BODYPART_HINDI,
  MONTHLY_TEMPLATE_HINDI, WEEKLY_HINDI, YEARLY_HINDI,
} = require('../data/extendedHoroscopeHindi');
const { langFrom } = require('../services/langOverlay');

// The English entry decides everything factual — which week it is, which theme
// is running, what the lucky colour and number are. Hindi only supplies the
// words, and only where it has them.
function inHindi(english, hindi) {
  if (!hindi) return english;
  return {
    ...english,
    ...(english.theme ? { theme: THEME_HINDI[english.theme] || english.theme } : {}),
    overview: hindi.overview || english.overview,
    love: hindi.love || english.love,
    career: hindi.career || english.career,
    health: hindi.health || english.health,
  };
}

const SIGNS = ['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'];

function getWeekOfYear(date) {
  const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
  d.setUTCDate(d.getUTCDate() + 4 - (d.getUTCDay() || 7));
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  return Math.ceil((((d - yearStart) / 86400000) + 1) / 7);
}

// ── Controllers ────────────────────────────────────────────────────────────────
function getWeekly(req, res) {
  const { sign } = req.params;
  if (!WEEKLY[sign]) return res.status(400).json({ error: 'Invalid sign', validSigns: SIGNS });
  const now  = new Date();
  const week = getWeekOfYear(now);
  const idx  = week % 4;
  const data = langFrom(req) === 'hi'
    ? inHindi(WEEKLY[sign][idx], WEEKLY_HINDI[sign]?.[idx])
    : WEEKLY[sign][idx];
  const monday = new Date(now);
  monday.setDate(now.getDate() - now.getDay() + 1);
  const sunday = new Date(monday);
  sunday.setDate(monday.getDate() + 6);
  const fmt = d => d.toISOString().split('T')[0];
  res.json({ sign, weekStart: fmt(monday), weekEnd: fmt(sunday), weekNumber: week, ...data, lucky: data.lucky || SIGN_LUCKY[sign] });
}

function getMonthly(req, res) {
  const { sign } = req.params;
  if (!MONTHLY[sign]) return res.status(400).json({ error: 'Invalid sign', validSigns: SIGNS });
  const now   = new Date();
  const month = now.getMonth(); // 0-based
  const year  = now.getFullYear();
  const months = ['January','February','March','April','May','June','July','August','September','October','November','December'];
  let data = MONTHLY[sign][month];
  if (langFrom(req) === 'hi') {
    const INFO_HI = {
      Aries:'Mars', Taurus:'Venus', Gemini:'Mercury', Cancer:'Moon', Leo:'Sun', Virgo:'Mercury',
      Libra:'Venus', Scorpio:'Mars', Sagittarius:'Jupiter', Capricorn:'Saturn', Aquarius:'Saturn', Pisces:'Jupiter',
    };
    const hi = MONTHLY_TEMPLATE_HINDI(SIGN_HINDI[sign], RULER_HINDI[INFO_HI[sign]], BODYPART_HINDI[sign])[month];
    data = inHindi(data, hi);
  }
  res.json({ sign, month: months[month], monthIndex: month + 1, year, ...data });
}

function getYearly(req, res) {
  const { sign } = req.params;
  const year = parseInt(req.query.year) || new Date().getFullYear();
  if (!YEARLY[year]) return res.status(400).json({ error: 'Year not available', availableYears: Object.keys(YEARLY) });
  if (!YEARLY[year][sign]) return res.status(400).json({ error: 'Invalid sign', validSigns: SIGNS });
  const base = YEARLY[year][sign];
  const hi = langFrom(req) === 'hi' ? YEARLY_HINDI[year]?.[sign] : null;
  res.json({
    sign, year,
    ...base,
    ...(hi ? { overview: hi.overview, quarters: hi.quarters } : {}),
  });
}

function getAllSigns(req, res) {
  res.json({ signs: SIGNS });
}

module.exports = { getWeekly, getMonthly, getYearly, getAllSigns };
