'use strict';

const { calculateKundali } = require('../services/kundaliEngine');

const SIGNS = ['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'];
const SIGN_SYMBOLS = ['♈','♉','♊','♋','♌','♍','♎','♏','♐','♑','♒','♓'];

// ── Traditional Gochara: favourable houses from natal Moon ─────────────────────
const FAVORABLE = {
  Sun:     new Set([3,6,10,11]),
  Moon:    new Set([1,3,6,7,10,11]),
  Mars:    new Set([3,6,11]),
  Mercury: new Set([2,4,6,8,10,11]),
  Jupiter: new Set([2,5,7,9,11]),
  Venus:   new Set([1,2,3,4,5,8,9,11,12]),
  Saturn:  new Set([3,6,11]),
  Rahu:    new Set([3,6,10,11]),
  Ketu:    new Set([3,6,10,11]),
};

// ── Effect database — each planet in each house from natal Moon ────────────────
// Format: { summary, career, love, health, finance, advice, intensity: 1-5 }
const EFFECTS = {
  Sun: [
    null, // placeholder (1-indexed)
    { h:1,  good:false, summary:'Sun transiting your Moon sign creates health sensitivity and identity challenges. Ego conflicts are possible; guard against stubbornness and overexertion.', career:'Authority figures create friction. Hold back on major initiatives for ~30 days.', love:'Self-centred tendencies may strain close relationships. Listen more than you speak.', health:'Head, eyes, and energy levels need attention. Rest is restorative.', finance:'Hold financial decisions; avoid speculative risks this month.', advice:'Use this period for inner reflection rather than outward assertion.', intensity:3 },
    { h:2,  good:false, summary:'Financial pressures may arise. Family relationships experience tension and impulsive spending is a risk. Speech should be measured and thoughtful.', career:'Minor setbacks in professional communication. Avoid heated arguments.', love:'Family dynamics require patience and diplomacy this month.', health:'Digestive and vocal health benefit from attention and care.', finance:'Review expenses carefully. This is not the ideal time for large financial commitments.', advice:'Focus on conservation of resources — both financial and physical.', intensity:2 },
    { h:3,  good:true,  summary:'Excellent period for communication, courage, and short ventures. Siblings and neighbours bring positive news. Creative energy is heightened.', career:'A bold professional initiative succeeds. Communication projects receive strong support.', love:'Social confidence makes you magnetically attractive and warm.', health:'High physical energy and vitality. Active pursuits bring joy.', finance:'Income through effort and skill improves noticeably this month.', advice:'Launch new projects, send important messages, and pursue courageous goals.', intensity:4 },
    { h:4,  good:false, summary:'Domestic tensions and mother-related matters require careful attention. Property decisions should be postponed. Emotional restlessness is common.', career:'Career visibility decreases temporarily. Focus on internal systems instead.', love:'Relationship harmony at home needs conscious effort this month.', health:'Heart and chest health benefit from attention. Reduce stress at home.', finance:'Property and domestic expenses may increase. Budget accordingly.', advice:'Nurture family relationships with patience. Avoid major property decisions.', intensity:3 },
    { h:5,  good:false, summary:'Creative blocks and obstacles with children or speculative investments are likely. Educational matters may face delays. Guard against excessive pride.', career:'Creative or speculative ventures face resistance. Stick to reliable paths.', love:'Romance may cool slightly. Avoid dramatic emotional displays.', health:'Stomach and digestion benefit from light, simple foods.', finance:'Avoid speculative investments and gambling of any kind this month.', advice:'Focus on steady, practical actions rather than creative risks.', intensity:3 },
    { h:6,  good:true,  summary:'Excellent for overcoming enemies, illness, and debts. Success in competitions and legal matters. Physical vitality helps you tackle long-standing challenges.', career:'Professional conflicts resolve in your favour. Competitors are weakened.', love:'Relationships with colleagues and social connections improve considerably.', health:'Recovery from illness accelerates. Active pursuits strengthen the body.', finance:'Debts can be repaid or reduced. Financial competition resolves favourably.', advice:'Take on challenges directly. This is your most powerful month for tackling obstacles.', intensity:5 },
    { h:7,  good:false, summary:'Partnership tensions and potential conflicts with spouse or business partners. Travel may bring stress. Legal matters require caution.', career:'Business partnerships need extra care and clear agreements.', love:'Marital or romantic friction is possible. Patience and understanding are essential.', health:'Lower back and general vitality require attention.', finance:'Joint financial decisions need careful review before committing.', advice:'Prioritise diplomacy in all relationships. Avoid legal battles if possible.', intensity:3 },
    { h:8,  good:false, summary:'Health concerns, obstacles, and inheritance matters may arise. Avoid risky activities and major changes during this period.', career:'Hidden opposition at work. Avoid power struggles with authorities.', love:'Emotional depth tests relationships. Trust becomes the central theme.', health:'Chronic issues may temporarily intensify. Medical consultations are beneficial.', finance:'Joint resources, insurance, and inheritance matters need careful attention.', advice:'Focus on transformation and regeneration rather than new beginnings.', intensity:4 },
    { h:9,  good:false, summary:'Father-related matters and long-distance travel may face obstacles. Philosophical or spiritual challenges arise. Remain flexible in beliefs.', career:'Foreign or long-distance professional matters face delays.', love:'Long-distance relationships or love involving cultural differences face challenges.', health:'Hips and thighs need attention. Outdoor physical activity is beneficial.', finance:'Long-term investments need review. Avoid committing to foreign ventures.', advice:'Maintain humility in philosophical matters. Learn from setbacks.', intensity:2 },
    { h:10, good:true,  summary:'Excellent for career advancement, public recognition, and professional achievements. Authority figures support your ambitions.', career:'Career peak period. A promotion, award, or professional milestone is likely.', love:'Your confidence and social status attract positive romantic attention.', health:'High energy and drive. Channel into productive physical and professional activity.', finance:'Income and career-related earnings improve significantly this month.', advice:'Step forward boldly in professional matters. Visibility works in your favour.', intensity:5 },
    { h:11, good:true,  summary:'Outstanding period for income gains, social success, and achievement of goals. Elder siblings and friends bring valuable help.', career:'Social and professional networks produce tangible results. Group projects succeed.', love:'Social charisma is magnetic. New connections and friendships flourish.', health:'Vitality is excellent. Social activities energise rather than deplete.', finance:'Multiple income streams open. Financial goals receive strong momentum.', advice:'Network actively and pursue long-held ambitions. The cosmos aligns with your goals.', intensity:5 },
    { h:12, good:false, summary:'Expenses increase, foreign travel may be forced, and sleep patterns can be disturbed. A period requiring spiritual focus and introspection.', career:'Professional visibility decreases. Work from behind the scenes instead.', love:'Romantic isolation or a sense of distance from the partner may occur.', health:'Sleep, immune system, and vitality need deliberate support.', finance:'Expenses rise unexpectedly. Maintain a financial buffer and avoid luxury spending.', advice:'Retreat, reflect, and restore. This period prepares the soil for what comes next.', intensity:3 },
  ],

  Moon: [
    null,
    { h:1,  good:true,  summary:'Moon transiting your own sign brings emotional clarity, enhanced intuition, and public recognition. A personally significant period.', career:'Instincts about career directions are accurate. Trust them now.', love:'Emotional availability makes you deeply attractive and lovable.', health:'Listen to your body carefully — it communicates with unusual clarity now.', finance:'Intuitive financial decisions prove accurate this month.', advice:'Trust your emotional guidance system. It is exceptionally reliable now.', intensity:4 },
    { h:2,  good:false, summary:'Financial instability and family tensions are likely. Speech and communication need careful calibration. Emotional spending is a risk.', career:'Communication challenges at work. Express yourself with extra care.', love:'Family relationships need emotional investment and patience.', health:'Throat, voice, and nutrition benefit from focused attention.', finance:'Budget carefully. Avoid emotionally-driven purchases and unplanned expenses.', advice:'Speak thoughtfully; act financially with discipline and planning.', intensity:2 },
    { h:3,  good:true,  summary:'Excellent for communication, short journeys, and creative expression. Sibling relationships flourish. Mental clarity is exceptional.', career:'Writing, speaking, and communication-heavy work produce outstanding results.', love:'Playful, articulate expression makes you romantically irresistible.', health:'High mental and physical energy. Active, varied pursuits sustain you well.', finance:'Income through skill, communication, or short ventures improves.', advice:'Travel, write, speak, and connect. This is your most expressive lunar period.', intensity:4 },
    { h:4,  good:false, summary:'Domestic restlessness and possible tension with the mother figure. Property matters need careful handling. Emotional sensitivity is heightened.', career:'Career distractions from home matters. Work-from-home balance needs attention.', love:'Family harmony requires extra emotional investment and patience.', health:'Chest and emotional wellbeing benefit from nurturing home environment.', finance:'Domestic and property expenses may increase unexpectedly.', advice:'Prioritise home harmony over external ambitions during this transit.', intensity:3 },
    { h:5,  good:false, summary:'Creativity may feel blocked. Children-related matters and romantic spontaneity face subtle obstacles. Speculative activities should be avoided.', career:'Creative projects need more incubation time. Avoid premature launches.', love:'Romance may feel slightly muted or emotionally complex this period.', health:'Digestive health benefits from light, nourishing foods and reduced stress.', finance:'Speculative and gambling activities carry elevated risk this month.', advice:'Nurture creative ideas patiently. The timing for expression will improve.', intensity:2 },
    { h:6,  good:true,  summary:'A powerful period for overcoming health challenges, defeating opposition, and resolving debts. Your emotional resilience wins the day.', career:'Workplace conflicts resolve through your emotional intelligence and persistence.', love:'A challenging relationship dynamic finds resolution and improvement.', health:'Recovery from illness accelerates. The body and mind both strengthen.', finance:'Debts reduce and financial obstacles clear with targeted effort.', advice:'Face your challenges directly — this is your strongest period for overcoming them.', intensity:5 },
    { h:7,  good:true,  summary:'Partnership matters are emotionally fulfilling. Marriage, business alliances, and social connections all bloom.', career:'Business partnerships and client relationships improve significantly.', love:'A romantic high point. Existing bonds deepen; new connections have potential.', health:'Emotional balance and relational harmony support overall health.', finance:'Joint financial ventures and partnerships produce favourable results.', advice:'Invest in your relationships. The emotional and material returns are significant.', intensity:4 },
    { h:8,  good:false, summary:'Emotional turbulence, health sensitivity, and obstacles are likely. A period requiring careful, deliberate choices.', career:'Hidden workplace tensions need careful navigation. Avoid power struggles.', love:'Trust issues and emotional depth test relationship bonds significantly.', health:'Mental and physical health both need extra attention and support.', finance:'Shared finances, insurance, and unexpected expenses need careful management.', advice:'Prioritise inner healing and emotional processing over external achievements.', intensity:4 },
    { h:9,  good:false, summary:'Travel, dharmic matters, and father-related situations face emotional challenges. Philosophical certainty may waver.', career:'Long-distance professional matters face emotional or practical delays.', love:'Long-distance relationships experience emotional distance and complexity.', health:'Hips and mental restlessness both benefit from grounding practices.', finance:'Foreign financial matters and long-term investments need careful monitoring.', advice:'Stay rooted in your values while remaining open to new perspectives.', intensity:2 },
    { h:10, good:true,  summary:'Career success and public recognition are favoured. Emotional intelligence drives professional achievement this month.', career:'A career milestone, promotion, or public recognition arrives.', love:'Your emotional depth and professional confidence make you irresistible.', health:'Strong vitality and emotional drive. Channel both productively.', finance:'Career-related income and professional opportunities both improve.', advice:'Step into public and professional visibility with confidence.', intensity:4 },
    { h:11, good:true,  summary:'Goals are achieved, income increases, and social connections produce tangible benefits. An emotionally satisfying period.', career:'Social networks produce valuable professional opportunities and support.', love:'Emotionally warm and socially vibrant. New meaningful connections form.', health:'Emotional and physical wellbeing both peak during this favourable transit.', finance:'Multiple income opportunities and goal-achievement in financial matters.', advice:'Pursue your goals with the full force of your emotional energy. This is your time.', intensity:5 },
    { h:12, good:false, summary:'Increased expenditure, possible travel, and emotional withdrawal. A period better suited to reflection than action.', career:'Professional drive diminishes. Behind-the-scenes work is more appropriate.', love:'Emotional distance or withdrawal affects relationships temporarily.', health:'Sleep and immune health need deliberate support and care.', finance:'Unexpected expenses arise. Maintain a financial buffer and conserve resources.', advice:'Use this introspective period for spiritual renewal and inner preparation.', intensity:3 },
  ],

  Mars: [
    null,
    { h:1,  good:false, summary:'Mars transiting your Moon sign brings aggression, accidents, and impulsive decisions. Channel energy into structured physical activity.', career:'Avoid confrontations at work. Direct energy into productive challenges.', love:'Impatience and irritability strain relationships. Exercise before engaging emotionally.', health:'Accident risk is elevated. Head, energy depletion, and inflammation need attention.', finance:'Impulsive financial decisions carry serious risk. Review twice before committing.', advice:'Redirect Mars energy into exercise, discipline, and controlled challenges.', intensity:4 },
    { h:2,  good:false, summary:'Financial outgoings increase and family friction is possible. Harsh speech may create relationship damage that lingers.', career:'Workplace communication requires deliberate restraint and care.', love:'Domestic arguments are likely. Choose words with surgical care and empathy.', health:'Face, teeth, and throat benefit from preventive attention.', finance:'Outgoings increase and impulsive purchases are a significant risk this month.', advice:'Before speaking, pause. Before spending, wait. Patience protects both finances and relationships.', intensity:3 },
    { h:3,  good:true,  summary:'Exceptional courage, communication power, and competitive edge. Short journeys succeed and siblings bring support.', career:'Competitive professional situations resolve decisively in your favour.', love:'Bold, direct expression of desire creates romantic breakthroughs.', health:'Physical energy and stamina are at their peak. Train and compete.', finance:'Energetic effort produces excellent financial returns this month.', advice:'Be bold, be direct, and act with the confidence of Mars in full strength.', intensity:5 },
    { h:4,  good:false, summary:'Domestic disputes and property-related conflicts are possible. Mother-related matters require careful, patient handling.', career:'Career restlessness may tempt impulsive job changes. Pause before acting.', love:'Home environment tension affects the relationship. Address root causes with patience.', health:'Chest and emotional health benefit from calming practices and home harmony.', finance:'Property-related expenses and disputes may arise unexpectedly.', advice:'Invest in domestic harmony before pursuing external ambitions.', intensity:3 },
    { h:5,  good:false, summary:'Creative conflicts, risk-taking impulses, and speculative losses are likely. Children-related matters need protective attention.', career:'Risky career bets are not favoured. Steady, disciplined approaches win.', love:'Romantic drama and impulsive decisions may complicate relationships.', health:'Digestive and cardiac health benefit from reduced stimulants and stress.', finance:'Speculation and gambling carry very high risk of loss this month. Avoid entirely.', advice:'Channel competitive energy into disciplined creative practice rather than risk-taking.', intensity:3 },
    { h:6,  good:true,  summary:'Powerful victory over enemies, competitors, illness, and debt. Your fighting spirit is fully activated and exceptionally effective.', career:'Decisive action defeats workplace opposition and competition.', love:'A difficult relationship dynamic finally resolves through direct confrontation.', health:'Physical strength peaks. High-intensity training produces excellent results.', finance:'Aggressive pursuit of debtors and financial competitors succeeds.', advice:'Tackle every challenge directly and without hesitation. This is your most powerful Mars transit.', intensity:5 },
    { h:7,  good:false, summary:'Marital conflict and partnership tension are a serious risk. Legal disputes may arise. All partnerships need diplomatic, careful management.', career:'Business partner conflicts need careful, diplomatic resolution.', love:'Direct confrontation with a romantic partner is likely. Choose battles wisely.', health:'Kidney and lower back health need attention and care.', finance:'Joint financial disputes or contractual conflicts may arise.', advice:'Apply Mars energy to problem-solving, not relationship warfare.', intensity:4 },
    { h:8,  good:false, summary:'Accident risk, serious health concerns, and obstacles from others are elevated. Exercise extreme caution in all areas.', career:'Hidden enemies and workplace sabotage need careful navigation.', love:'Deep relationship crises may arise. Trust becomes the central test.', health:'This is the most important Mars transit for health vigilance. No unnecessary risks.', finance:'Financial losses and unexpected expenses require conservative management.', advice:'This is a period for maximum caution. Avoid unnecessary risks in all life areas.', intensity:5 },
    { h:9,  good:false, summary:'Long-distance travel carries risk. Father-related matters and beliefs may create conflict. Philosophical rigidity should be released.', career:'International professional matters face obstacles and delays.', love:'Long-distance relationships face friction and distance.', health:'Hips and thighs are vulnerable. Avoid high-risk physical activities.', finance:'Foreign financial ventures carry elevated risk. Review thoroughly before committing.', advice:'Release the need to be right in philosophical or religious matters.', intensity:2 },
    { h:10, good:false, summary:'Career ambitions face obstacles and authority-figure conflicts. Avoid power struggles with superiors and stay focused on quality work.', career:'Career challenges arrive. Demonstrate competence rather than asserting authority.', love:'Professional stress spills into personal relationships. Maintain boundaries.', health:'Overwork and stress are health risks. Establish and maintain firm rest boundaries.', finance:'Career-related financial setbacks need careful management.', advice:'Work hard with discipline and avoid confrontations with those in power above you.', intensity:3 },
    { h:11, good:true,  summary:'Exceptional period for income gains, goal achievement, and success in competitive endeavours. Your drive produces outstanding results.', career:'Professional goals achieved through energetic, competitive effort.', love:'Social confidence and magnetic energy attract positive romantic attention.', health:'Physical energy is excellent and productive. Pursue athletic goals actively.', finance:'Strong financial gains through effort, competition, and decisive action.', advice:'Go after your biggest goals with full Martian energy. The cosmic wind is behind you.', intensity:5 },
    { h:12, good:false, summary:'Energy dissipates into hidden efforts and expenses. Foreign or isolated endeavours carry frustration and loss.', career:'Energy wasted on invisible work. Ensure your efforts are recognised.', love:'Sexual and romantic satisfaction may decline temporarily.', health:'Sleep disturbances and hidden health issues need attention.', finance:'Secret outgoings and losses through careless decisions increase risk.', advice:'Conserve Mars energy for what truly matters. Avoid wasteful efforts and hidden expenditures.', intensity:3 },
  ],

  Mercury: [
    null,
    { h:1,  good:false, summary:'Mental restlessness and nervous anxiety may arise. Communication is over-extended. Focus and discipline are necessary remedies.', career:'Too many ideas and not enough execution. Focus on one priority.', love:'Over-analysis and nervous communication may create misunderstandings.', health:'Nervous system and mental health benefit from meditation and reduced stimulants.', finance:'Financial analysis is sharp but decision-making is scattered. Take time to focus.', advice:'Slow down the mental chatter. One idea, fully executed, outperforms ten ideas half-done.', intensity:2 },
    { h:2,  good:true,  summary:'Excellent for financial communication, family negotiations, and business speech. Wealth through intelligence and clever communication.', career:'Written proposals, financial reports, and business communication all excel.', love:'Articulate, thoughtful communication strengthens family and romantic bonds.', health:'Vocal and respiratory health are generally good. Maintain clarity through hydration.', finance:'Smart financial communication and negotiation produce excellent results.', advice:'Use your words as tools for building wealth and strengthening relationships.', intensity:4 },
    { h:3,  good:false, summary:'Communication overload and scattered sibling dynamics. Short trips become complicated. Mental focus needs deliberate cultivation.', career:'Information overload creates indecision. Prioritise ruthlessly.', love:'Over-communication may paradoxically create distance. Say less, mean more.', health:'Nervous system and respiratory tract need deliberate rest and care.', finance:'Multiple small financial opportunities distract from the most important one.', advice:'Edit rather than add. Clarity comes from reducing, not expanding.', intensity:2 },
    { h:4,  good:true,  summary:'Excellent for real estate negotiations, family communication, and domestic planning. Mental clarity in all home matters.', career:'Remote or home-based work produces particularly sharp results.', love:'Thoughtful, caring family communication creates lasting domestic harmony.', health:'Domestic mental environment becomes an asset. A clean, organised space heals.', finance:'Property and real estate negotiations benefit from Mercury\'s sharp analytical support.', advice:'Apply your analytical gifts to home and family matters for excellent results.', intensity:4 },
    { h:5,  good:false, summary:'Intellectual pride and over-analysis may block creative spontaneity. Education matters need grounded patience.', career:'Creative projects over-analysed to the point of paralysis. Trust your first instinct.', love:'Over-thinking romantic situations creates unnecessary complexity.', health:'Mental overwork and digestive tension benefit from breaks and play.', finance:'Speculative analysis produces more confusion than clarity. Keep it simple.', advice:'Step outside the analytical mind and allow intuition and spontaneity to guide creativity.', intensity:2 },
    { h:6,  good:true,  summary:'Sharp analytical power defeats enemies, resolves health puzzles, and eliminates debts through clever strategy.', career:'Intellectual competition in the workplace resolves in your decisive favour.', love:'A communication conflict in a relationship finds its intelligent resolution.', health:'Medical diagnoses and health analysis are particularly accurate this period.', finance:'Intelligent debt management and financial problem-solving produce excellent results.', advice:'Use your mind as your most powerful weapon for overcoming all challenges now.', intensity:4 },
    { h:7,  good:false, summary:'Partnership communication faces complexity and potential misunderstanding. Legal contracts require exceptionally careful review.', career:'Business partnerships need extra written clarity and explicit agreements.', love:'Communication misunderstandings in the relationship need patient, careful resolution.', health:'Kidney health and nervous system balance both benefit from attention.', finance:'Financial contracts and joint agreements need painstaking review before signing.', advice:'Over-communicate and over-document in all partnership matters this month.', intensity:3 },
    { h:8,  good:true,  summary:'Exceptional period for research, investigation, occult studies, and uncovering hidden information. Transformative intellectual insights arrive.', career:'Research, analysis, and investigation produce extraordinary professional results.', love:'Deep psychological understanding of relationship patterns creates breakthroughs.', health:'Medical research and alternative diagnostic approaches yield valuable insights.', finance:'Financial investigation, research-based investments, and tax matters resolve well.', advice:'Go deep. The hidden information you uncover this month is exceptionally valuable.', intensity:4 },
    { h:9,  good:false, summary:'Philosophical debates and long-distance communication may create complexity. Higher education matters need careful navigation.', career:'Academic or international matters face communication delays and complications.', love:'Long-distance relationships face communication challenges and misunderstandings.', health:'Travel-related health precautions are worth taking. Prepare thoroughly.', finance:'International financial communications need extra care and verification.', advice:'Maintain intellectual humility and listen as much as you speak.', intensity:2 },
    { h:10, good:true,  summary:'Communication skills bring professional recognition and career advancement. A public presentation or written work receives strong positive response.', career:'Writing, speaking, and intellectual contributions to your field receive recognition.', love:'Articulate, confident communication makes you professionally and romantically attractive.', health:'Mental energy is channelled productively into career success.', finance:'Intelligent career communication produces measurable income improvement.', advice:'Speak, write, and present your ideas with confidence. The reception exceeds expectations.', intensity:4 },
    { h:11, good:true,  summary:'Social intelligence and communication skills produce financial gains and valuable social connections. Goals reached through clever networking.', career:'Professional social network produces concrete opportunities through Mercury\'s communication.', love:'Intellectually stimulating social connections create romantic and friendship possibilities.', health:'Mental and social energy is balanced and productive. Stay engaged but rest too.', finance:'Clever networking and information-based decisions produce strong financial results.', advice:'Use your communication gifts to build and deepen the network that builds your future.', intensity:4 },
    { h:12, good:false, summary:'Mental anxiety, hidden information problems, and communication isolation may create frustration.', career:'Work behind the scenes on research or preparation. Avoid public communication errors.', love:'Miscommunication creates emotional distance. Clarify with care and patience.', health:'Mental chatter and anxiety need targeted meditative intervention.', finance:'Hidden financial information needs investigating. A small error may have larger consequences.', advice:'Audit your communications for errors and your finances for hidden leaks.', intensity:2 },
  ],

  Jupiter: [
    null,
    { h:1,  good:false, summary:'Jupiter in the 1st brings expansion but also over-confidence and weight gain. Personal growth is genuine but measured expectations are wise.', career:'Career expansion is available but requires discipline alongside optimism.', love:'Natural warmth and generosity attract affection, though over-indulgence is a risk.', health:'Weight management and liver health need deliberate attention during this expansive period.', finance:'Financial optimism should be tempered with practical planning and budgeting.', advice:'The expansion Jupiter offers is real — but channel it with discipline, not just enthusiasm.', intensity:3 },
    { h:2,  good:true,  summary:'Excellent for financial growth, family harmony, and building lasting wealth. Jupiter expands everything in the 2nd house.', career:'Career earnings and professional value both increase through Jupiter\'s blessing.', love:'Family relationships experience a warm, generous, and harmonious expansion.', health:'General vitality and nutritional abundance both support good health.', finance:'Wealth accumulates through multiple channels. This is among your best financial periods.', advice:'Invest wisely, save deliberately, and build the material foundation Jupiter is offering.', intensity:5 },
    { h:3,  good:false, summary:'Communication expands generously but depth may be sacrificed. Sibling relationships become more prominent and occasionally challenging.', career:'Communication and networking bring opportunities but require focused follow-through.', love:'Many social connections but depth of intimacy needs deliberate cultivation.', health:'Respiratory and shoulder health are generally positive. Maintain physical activity.', finance:'Multiple income channels create opportunity but also diluted focus.', advice:'Choose depth over breadth in both communication and professional pursuits this period.', intensity:2 },
    { h:4,  good:false, summary:'Domestic expansion — possible relocation, family addition, or property changes. Home matters require generous emotional investment.', career:'Career takes second place to home matters. Balance both deliberately.', love:'Family relationships expand and deepen with generosity and warmth.', health:'Comfort eating and domestic contentment need to be balanced with physical activity.', finance:'Property decisions may be large and significant. Research thoroughly before acting.', advice:'Home is where Jupiter\'s blessing manifests this year. Invest in it generously.', intensity:3 },
    { h:5,  good:true,  summary:'Exceptional creativity, romance, and child-related blessings. Speculative investments carry genuine promise when approached wisely.', career:'Creative, entrepreneurial, and speculative career ventures receive Jupiter\'s full blessing.', love:'Romance blossoms with unusual depth, passion, and genuine joy.', health:'Heart health and vitality both benefit from joyful, creative physical activity.', finance:'Wisely managed speculation and creative financial ventures produce strong returns.', advice:'Create, romance, and celebrate. This is one of Jupiter\'s finest transits for joy and abundance.', intensity:5 },
    { h:6,  good:false, summary:'Over-commitment to service and health indulgence can create imbalance. Work quality suffers from over-extension.', career:'Overwork and excessive service without adequate self-care diminish results.', love:'Service to others consumes energy needed for romantic relationships.', health:'Over-indulgence and health complacency need conscious attention and discipline.', finance:'Work-related expenses and service costs may exceed their planned scope.', advice:'Balance generous service to others with deliberate investment in your own wellbeing.', intensity:2 },
    { h:7,  good:true,  summary:'Marriage, partnerships, and legal matters all receive Jupiter\'s generous blessing. A landmark partnership year.', career:'Business partnerships expand with genuine, profitable results.', love:'Marriage and serious romantic commitment are exceptionally favoured this period.', health:'Partnership harmony directly enhances physical and emotional wellbeing.', finance:'Joint financial ventures and business partnerships produce strong, lasting returns.', advice:'Commit to the partnerships — romantic or professional — that Jupiter is highlighting this year.', intensity:5 },
    { h:8,  good:false, summary:'Transformation and occult matters expand, but debt and hidden financial matters need careful management.', career:'Research, investigation, and transformative professional work receive support.', love:'Deep emotional intimacy is available but requires navigating significant vulnerability.', health:'Regenerative health practices — detox, fasting, yoga — are powerfully effective now.', finance:'Inheritance, shared resources, and debt matters may expand in scope. Review carefully.', advice:'Use this period for deep personal transformation and financial restructuring.', intensity:3 },
    { h:9,  good:true,  summary:'Jupiter in the 9th is one of its strongest transits — expansion of wisdom, travel, teaching, and spiritual growth.', career:'Academic, legal, international, and publishing ventures all receive Jupiter\'s maximum blessing.', love:'A philosophically aligned, inspiring romantic connection deepens or arrives.', health:'Optimism and physical vitality are both naturally elevated by this powerful transit.', finance:'International, publishing, and educational financial ventures produce exceptional results.', advice:'Pursue your highest learning, travel your most meaningful journey, and share your wisdom widely.', intensity:5 },
    { h:10, good:false, summary:'Career ambitions expand generously but require grounded discipline. Over-confidence with superiors is a risk.', career:'Career advancement is real but discipline and humility prevent over-extension.', love:'Professional success positively influences romantic confidence and attractiveness.', health:'Maintain physical health routines despite the seduction of professional over-work.', finance:'Income may increase but expanded lifestyle expenses can neutralise gains.', advice:'Accept the career expansion Jupiter offers with disciplined, grounded execution.', intensity:3 },
    { h:11, good:true,  summary:'Outstanding period for income expansion, goal achievement, and community leadership. Jupiter\'s most financially rewarding transit.', career:'Professional network and social capital both produce extraordinary results.', love:'Social abundance creates both romantic opportunities and deep, meaningful friendships.', health:'Emotional abundance and physical vitality are both at a peak during this transit.', finance:'This is among the most financially abundant periods in the Jupiter 12-year cycle.', advice:'Network expansively, pursue your highest ambitions, and accept every genuine opportunity.', intensity:5 },
    { h:12, good:false, summary:'Spiritual expansion and retreat — a period better suited to inner growth than material ambition.', career:'Behind-the-scenes work, research, and spiritual preparation deliver quiet but real value.', love:'Solitude and inner reflection may temporarily create emotional distance.', health:'Spiritual practices, retreat, and rest are this period\'s most powerful medicine.', finance:'Expenses related to travel, hospitals, or spiritual pursuits may increase.', advice:'Embrace the spiritual expansion Jupiter offers in the 12th. The inner preparation it creates is profound.', intensity:3 },
  ],

  Venus: [
    null,
    { h:1,  good:true,  summary:'Exceptional charm, beauty, and romantic magnetism. Your personal presentation and social appeal are at their very best.', career:'Creative direction, client-facing roles, and aesthetic work all thrive.', love:'Romance blooms naturally and easily. Attraction is mutual and genuine.', health:'Vitality, skin health, and overall physical appeal are all enhanced.', finance:'Income through beauty, art, or personal appeal improves during this transit.', advice:'Invest in your appearance and social presence. The returns are immediate and significant.', intensity:5 },
    { h:2,  good:true,  summary:'Financial abundance and family harmony arrive with Venus\'s blessing. Aesthetic pleasures and material comforts are available and deserved.', career:'Financial negotiations and business communication carry Venus\'s persuasive grace.', love:'Family and romantic relationships enjoy an unusually warm and harmonious period.', health:'Nutritional abundance and comfort; guard against over-indulgence.', finance:'Wealth accumulates through beauty, art, social skill, and genuine talent.', advice:'Enjoy material abundance mindfully. Venus in the 2nd is a genuine financial blessing.', intensity:4 },
    { h:3,  good:true,  summary:'Charming, persuasive communication and harmonious sibling relationships. Creative writing and artistic expression peak.', career:'Sales, marketing, creative writing, and public relations all benefit greatly.', love:'Flirtatious, warm, and playful communication deepens romantic connections.', health:'Respiratory and arm health are generally excellent. Keep up enjoyable physical activity.', finance:'Income through communication, creativity, and local connections improves.', advice:'Express yourself with Venus\'s grace and watch every relationship and opportunity open.', intensity:4 },
    { h:4,  good:true,  summary:'Domestic beauty, family harmony, and property blessings. Home becomes a genuine sanctuary of comfort and aesthetic pleasure.', career:'Work from home is both productive and enjoyable during this transit.', love:'Domestic romance and family warmth both flourish with Venus\'s home-sector grace.', health:'Comfort, good food, and beautiful surroundings support excellent health.', finance:'Property values and home-related financial matters are favoured.', advice:'Create beauty at home and with family. Venus in the 4th is pure domestic blessing.', intensity:4 },
    { h:5,  good:true,  summary:'Romance peaks with intense passion, creative inspiration, and joyful play. Venus in the 5th is one of the finest romantic transits.', career:'Creative projects, entertainment, and artistic work receive Venus\'s maximum creative blessing.', love:'A peak romantic period — love is passionate, playful, and genuinely joyful.', health:'Heart health and vitality are both enhanced through creative joy and romantic fulfilment.', finance:'Creative ventures and speculative investments carry genuine promise with disciplined management.', advice:'Fall in love with your work, with your person, and with life itself. Venus invites it now.', intensity:5 },
    { h:6,  good:false, summary:'Work-related relationship stress and minor health complications through indulgence are possible challenges.', career:'Workplace aesthetic disagreements and over-socialising at work need management.', love:'Service to others may leave insufficient time and energy for romance.', health:'Over-indulgence in rich foods and comfort habits may create health imbalances.', finance:'Small luxury expenses accumulate; maintain deliberate financial discipline.', advice:'Balance pleasure with discipline, and service with self-care, for best results.', intensity:2 },
    { h:7,  good:true,  summary:'Marriage and partnership matters flourish with Venus\'s direct blessing on the 7th house. A significant romantic period.', career:'Business partnerships reach a harmonious and productive peak.', love:'Romantic relationships deepen, proposals are favoured, and existing bonds renew.', health:'Relational harmony has a direct, measurable impact on physical and emotional health.', finance:'Joint financial ventures and business alliances produce beautiful results.', advice:'Invest fully in your most significant partnership. Venus is directly blessing it now.', intensity:5 },
    { h:8,  good:true,  summary:'Financial gains through inheritance, joint ventures, and occult or research work. Deep romantic intimacy becomes available.', career:'Research, finance, and transformative professional work benefit from Venus\'s grace.', love:'Deeply intimate, transformative romantic connection is available and beautiful.', health:'Regenerative practices — massage, holistic therapies — are especially effective now.', finance:'Inheritance, joint resources, and investment returns are all favourably highlighted.', advice:'Allow Venus to guide you into profound depth — financially, romantically, and spiritually.', intensity:4 },
    { h:9,  good:true,  summary:'Love through philosophy, travel, and wisdom. Romantic encounters during travel or with culturally different people carry special meaning.', career:'International business, teaching, and publishing all receive Venus\'s graceful support.', love:'Travel romance or philosophically aligned partnerships are particularly favoured now.', health:'Physical vitality is enhanced by outdoor activity, travel, and joyful exploration.', finance:'International business and educational ventures carry financial promise.', advice:'Follow Venus toward beauty, wisdom, and adventure — especially if it requires a journey.', intensity:4 },
    { h:10, good:false, summary:'Career ambition may overshadow personal relationships. Balance professional success with deliberate romantic investment.', career:'Aesthetic refinement of professional presentation produces significant career returns.', love:'Career demands may temporarily reduce romantic availability and attention.', health:'Balance professional ambition with physical and emotional restoration.', finance:'Career-aesthetic improvements produce measurable income and recognition gains.', advice:'Maintain romantic investments even as career demands intensify. Both matter equally.', intensity:3 },
    { h:11, good:true,  summary:'Social abundance, income gains, and romantic connections through friends and networks. A charming, socially magnetic period.', career:'Professional social network and creative community produce beautiful results.', love:'A friend may become a romantic interest, or social connections deepen meaningfully.', health:'Social activity energises and heals — embrace the community Venus is bringing.', finance:'Income through social connections, group ventures, and community appreciation increases.', advice:'Network with Venus\'s grace and watch your social world transform into abundant opportunity.', intensity:4 },
    { h:12, good:true,  summary:'Secret romantic pleasures, spiritual beauty, and hidden creative work produce deep personal fulfilment.', career:'Behind-the-scenes creative work reaches exceptional, quietly satisfying results.', love:'A secret or deeply private romantic connection carries rare and genuine beauty.', health:'Retreat, sensory pleasure, and spiritual beauty are the specific medicines of this transit.', finance:'Private investments and behind-the-scenes financial strategies produce quiet gains.', advice:'Embrace solitude, beauty, and the private pleasures that Venus offers in the 12th.', intensity:3 },
  ],

  Saturn: [
    null,
    { h:1,  good:false, summary:'Saturn transiting your Moon sign — the central phase of Sade Sati. Health tests, delays, and life restructuring are its themes. Profound transformation is the ultimate gift.', career:'Career restructuring and delays require patient, disciplined response.', love:'Relationships face serious tests of commitment and genuine compatibility.', health:'Chronic health management, bone health, and psychological wellbeing all need support.', finance:'Financial constraints require strict budgeting and long-term planning.', advice:'Saturn in the 1st is demanding but profoundly transformative. Every lesson it brings is permanent wisdom.', intensity:5 },
    { h:2,  good:false, summary:'The concluding phase of Sade Sati — financial caution and family responsibilities are Saturn\'s final lessons.', career:'Financial restraint and practical professional choices are Saturn\'s wisdom for this period.', love:'Family responsibilities and practical commitments test and deepen romantic bonds.', health:'Dental, bone, and metabolic health all benefit from Saturn-season attention and discipline.', finance:'Conservative financial management and debt reduction are strongly advised.', advice:'Complete the Sade Sati lessons with wisdom. Practical, patient action now creates lasting stability.', intensity:4 },
    { h:3,  good:true,  summary:'Saturn\'s most productive transit from the Moon — discipline, hard work, and courageous effort produce outstanding, lasting results.', career:'Disciplined communication and hard professional effort produce career-defining results.', love:'Reliable, consistent relationship presence communicates deep love and commitment.', health:'Physical endurance and stamina both build impressively through disciplined exercise.', finance:'Hard work and disciplined saving produce strong and lasting financial results.', advice:'Work with Saturn\'s full discipline. This is the transit where effort meets permanent reward.', intensity:5 },
    { h:4,  good:false, summary:'Domestic burdens, property delays, and family responsibilities weigh more heavily during this transit.', career:'Career must be balanced with significant home responsibilities and duties.', love:'Domestic duties and family obligations test the relationship\'s practical foundations.', health:'Depression, isolation, and joint health all need deliberate care and support.', finance:'Property and domestic expenses increase. Budget conservatively and plan thoroughly.', advice:'Build the patient, practical domestic foundation that Saturn is demanding. It will endure for decades.', intensity:4 },
    { h:5,  good:false, summary:'Creative blocks, delays with children, and speculative losses characterise this challenging transit.', career:'Creative and speculative work faces Saturn\'s disciplining resistance. Practice rather than perform.', love:'Romance is tested by reality and commitment. Only the genuine bonds survive and strengthen.', health:'Digestive and cardiac health need attention. Reduce stimulants and excess.', finance:'Speculative investments and gambling carry very serious risk during this Saturn transit.', advice:'Submit to Saturn\'s disciplining of your creative and romantic impulses. Mastery requires time.', intensity:3 },
    { h:6,  good:true,  summary:'Saturn\'s second most productive transit — steady, disciplined effort defeats all enemies and creates sustainable professional excellence.', career:'Methodical, disciplined work creates career results of unusual quality and permanence.', love:'Reliable, practical service to your partner communicates the deepest love.', health:'Consistent health routines — exercise, diet, sleep — produce lasting improvements.', finance:'Debt reduction through disciplined effort and financial management produce strong results.', advice:'Apply Saturn\'s discipline to your health, work, and daily habits. The compound returns are exceptional.', intensity:5 },
    { h:7,  good:false, summary:'Partnership tests of commitment and realistic compatibility. A relationship that survives Saturn\'s scrutiny in the 7th is built to last.', career:'Business partnerships face serious, reality-testing scrutiny.', love:'Marriage and serious relationships are tested for genuine substance and compatibility.', health:'Kidney health and hormonal balance both benefit from Saturn-season attention.', finance:'Joint financial matters require conservative, carefully documented management.', advice:'Let Saturn test your partnerships honestly. What remains is exactly what deserves to remain.', intensity:4 },
    { h:8,  good:false, summary:'Chronic health challenges, financial obstacles, and transformative life lessons characterise this demanding transit.', career:'Long-term strategic work and transformative professional projects are Saturn\'s gift here.', love:'Deep emotional and physical health tests both individuals and the relationship.', health:'Chronic health conditions need serious medical attention and management.', finance:'Inheritance delays, joint financial obstacles, and insurance matters need careful handling.', advice:'Saturn in the 8th demands profound transformation. The discipline it enforces now is permanent wisdom.', intensity:5 },
    { h:9,  good:false, summary:'Philosophical and spiritual structures are tested. Higher education and long-distance matters face delays and restructuring.', career:'International and academic professional matters require patience and pragmatic adjustment.', love:'Long-distance relationships require deliberate, structured investment to endure.', health:'Hips, sciatic nerves, and long-term health foundations all benefit from Saturn-season focus.', finance:'International investments and speculative long-term ventures need conservative, careful management.', advice:'Build a philosophical foundation that can withstand Saturn\'s rigorous examination. It will serve you for life.', intensity:3 },
    { h:10, good:false, summary:'Career demands are heavy and authority-figure relationships face serious challenges. The work required is significant — so is the reward.', career:'Career difficulties and authority challenges require patient, disciplined navigation.', love:'Professional demands create relationship strain. Deliberate investment in both is essential.', health:'Overwork and stress are the primary health risks. Rest is not optional.', finance:'Career-related financial pressures require careful, conservative planning.', advice:'Build your career with Saturn\'s patience and precision. What you construct now withstands decades.', intensity:4 },
    { h:11, good:true,  summary:'Saturn\'s finest transit — disciplined, patient effort produces extraordinary income gains and lasting goal achievement.', career:'Long-term career goals achieve measurable, permanent progress through sustained effort.', love:'Social relationships based on genuine mutual respect and shared values deepen significantly.', health:'Consistent health routines established during this transit produce lasting, compounding benefits.', finance:'Patient, disciplined financial management produces outstanding long-term wealth accumulation.', advice:'Saturn in the 11th is your most rewarding long-term financial transit. Build diligently and consistently.', intensity:5 },
    { h:12, good:false, summary:'The rising phase of Sade Sati — expenses increase, travel is forced, and spiritual preparation is the real work.', career:'Work behind the scenes while preparing for the upcoming Sade Sati period.', love:'Emotional distance or withdrawal may temporarily affect romantic availability.', health:'Sleep, immune function, and mental health all need deliberate support.', finance:'Unexpected expenses and financial leakages need systematic identification and plugging.', advice:'Begin your Sade Sati spiritual preparation now. Meditation, discipline, and introspection are the best investments.', intensity:4 },
  ],

  Rahu: [
    null,
    { h:1,  good:false, summary:'Rahu creates obsessive focus on self-image, ambition, and identity. Unusual opportunities arrive with unconventional risks. Proceed thoughtfully.', career:'Unconventional career opportunities arrive; evaluate carefully before committing.', love:'Intense, possibly obsessive romantic focus needs grounded, realistic perspective.', health:'Mental health and identity stability need grounding practices and support.', finance:'Unusual financial opportunities carry both genuine potential and hidden risk.', advice:'Use Rahu\'s ambition purposefully. Groundedness is your most valuable counterbalance.', intensity:3 },
    { h:2,  good:false, summary:'Rahu creates unusual financial patterns, unconventional speech, and family disruption. Financial schemes need careful scrutiny.', career:'Unconventional income methods may produce results — or create complications.', love:'Family dynamics become unusual or unconventional. Maintain clear communication.', health:'Dietary experimentation and unusual health patterns need careful monitoring.', finance:'Unusual financial schemes carry both potential and significant risk. Research thoroughly.', advice:'Apply critical thinking to every unconventional financial opportunity Rahu presents.', intensity:3 },
    { h:3,  good:true,  summary:'Excellent for unconventional communication, bold initiatives, and surprising success in competitive endeavours.', career:'Innovative, disruptive approaches to professional communication produce results.', love:'Surprising, unconventional romantic developments carry genuine positive potential.', health:'Unusual physical activities and experimental wellness approaches produce results.', finance:'Bold, unconventional financial strategies produce surprisingly strong returns.', advice:'Trust Rahu\'s disruptive energy here. The unconventional path is, in this case, the right one.', intensity:4 },
    { h:4,  good:false, summary:'Domestic disruption, unusual family circumstances, and property irregularities are Rahu\'s 4th-house themes.', career:'Unusual work-from-home arrangements or domestic career disruptions arise.', love:'Family relationships become complex or unconventional — navigate with patience.', health:'Sleep disruption, emotional instability, and mental restlessness need attention.', finance:'Property matters carry unusual complications. Research every detail before proceeding.', advice:'Maintain domestic groundedness as Rahu creates its characteristic disruptions in the home.', intensity:3 },
    { h:5,  good:false, summary:'Unusual romantic obsessions, creative compulsions, and speculative instincts need careful channelling.', career:'Creative compulsions produce unusual work — sometimes brilliant, sometimes problematic.', love:'Intense, unconventional romantic attractions need reality-checking.', health:'Mental and digestive health need support during Rahu\'s 5th-house influence.', finance:'Speculative impulses are strong. Channel into research before committing financially.', advice:'Channel Rahu\'s creative obsession into something genuinely innovative and grounded.', intensity:3 },
    { h:6,  good:true,  summary:'Rahu in the 6th powerfully defeats enemies and obstacles through unconventional, strategic means.', career:'Unconventional professional strategies defeat competition and resolve workplace conflicts.', love:'Complex relationship dynamics are resolved through clever, unconventional approaches.', health:'Alternative health approaches and unconventional therapies produce positive results.', finance:'Unusual debt-reduction strategies and unconventional financial solutions work surprisingly well.', advice:'Think outside the conventional box. Rahu\'s unorthodox energy is genuinely powerful in the 6th.', intensity:4 },
    { h:7,  good:false, summary:'Unusual or unconventional partnerships and marriage circumstances. Foreign or cross-cultural relationship complexities arise.', career:'Business partnerships may involve unusual people or circumstances requiring careful navigation.', love:'Foreign, unconventional, or complex romantic circumstances require grounded handling.', health:'Relationship stress creates physical symptoms. Address relational disruptions directly.', finance:'Joint financial matters carry unusual complications. Document every agreement in detail.', advice:'Approach Rahu\'s partnership disruptions with both openness and careful discernment.', intensity:3 },
    { h:8,  good:false, summary:'Intense, transformative energies in hidden matters — occult, research, shared finances, and psychological depths.', career:'Research and investigation produce unusual, sometimes disturbing but valuable findings.', love:'Deep psychological revelations in relationships create necessary but challenging transformations.', health:'Hidden health matters need proactive investigation. Do not ignore unusual symptoms.', finance:'Hidden financial matters and unusual investments carry both risk and revelation.', advice:'Rahu in the 8th illuminates what was deliberately hidden. Use the revelations constructively.', intensity:4 },
    { h:9,  good:false, summary:'Unusual philosophical obsessions and unconventional spiritual paths may create confusion about life direction.', career:'International and academic matters take unusual, sometimes convoluted turns.', love:'Spiritually or philosophically complex romantic dynamics need practical grounding.', health:'Travel health precautions and philosophical anxiety both need conscious management.', finance:'Unusual international financial opportunities need careful, thorough due diligence.', advice:'Apply critical thinking to Rahu\'s unconventional spiritual impulses in the 9th house.', intensity:2 },
    { h:10, good:true,  summary:'Unusual and rapid career rise through unconventional means or foreign connections. Rahu energises public success.', career:'Career advancement through unconventional or foreign channels is genuinely possible now.', love:'Professional success and unusual social visibility create unexpected romantic opportunities.', health:'Career ambition energises the body. Balance drive with regular physical rest.', finance:'Unconventional career strategies produce surprisingly strong financial results.', advice:'Pursue the unusual career path Rahu is illuminating. The unconventional route leads to genuine success.', intensity:4 },
    { h:11, good:true,  summary:'Exceptional income gains and goal achievement through unusual, unconventional, or foreign channels.', career:'Professional networks with unusual or foreign individuals produce exceptional results.', love:'Unconventional social connections and surprising romantic developments flourish.', health:'Social energy and communal activities are energising and health-positive.', finance:'Unusual income channels and unconventional financial strategies produce strong returns.', advice:'Trust Rahu\'s disruptive energy in the 11th. The unusual path is producing the most abundant results.', intensity:4 },
    { h:12, good:false, summary:'Foreign travel, hidden expenses, and unusual spiritual experiences characterise Rahu in the 12th.', career:'Work involving foreign elements or behind-the-scenes environments produces results.', love:'Secret or distant romantic dynamics require honest, careful navigation.', health:'Hidden health issues and sleep disturbances need proactive attention and management.', finance:'Foreign-related expenses and hidden financial leaks need systematic identification.', advice:'Monitor hidden expenses carefully. The 12th-house Rahu can create financial disruptions silently.', intensity:3 },
  ],

  Ketu: [
    null,
    { h:1,  good:false, summary:'Ketu brings spiritual detachment, identity dissolution, and past-life themes to the self. Introspection is more productive than self-assertion now.', career:'Career direction may feel unclear. Reconnect with your deepest professional values.', love:'Emotional detachment may create distance in relationships. Deliberate presence is the remedy.', health:'Mysterious health symptoms, immune matters, and neurological wellbeing need attention.', finance:'Financial detachment may lead to unconventional but sometimes effective strategies.', advice:'Ketu in the 1st invites spiritual identity work. The detachment it creates is preparation for a clearer self.', intensity:3 },
    { h:2,  good:false, summary:'Financial detachment and past-life family karma are themes. Non-attachment to material accumulation is the teaching.', career:'Career earnings may feel less important than meaningful work. Trust this inner compass.', love:'Family relationships surface unresolved ancestral patterns requiring compassionate attention.', health:'Digestive health and speech patterns carry old karmic themes worth examining.', finance:'Material detachment is genuine but needs to be balanced with practical financial management.', advice:'Examine your relationship to money and family through Ketu\'s lens of spiritual non-attachment.', intensity:2 },
    { h:3,  good:true,  summary:'Spiritual communication, past-life sibling connections, and courageous inner knowing produce genuine results.', career:'Intuitive communication and unconventional competitive strategies produce results.', love:'Deep, spiritually resonant communication creates connections of unusual depth and meaning.', health:'Spiritual practices involving breath and movement are especially healing now.', finance:'Intuitive financial strategies and past-life skills produce income in unexpected ways.', advice:'Trust the deep, quiet knowing that Ketu activates in the 3rd house. It is genuinely accurate.', intensity:4 },
    { h:4,  good:false, summary:'Domestic karmic themes and emotional past-life patterns come to the surface for healing and release.', career:'Home-based work allows the deep psychological work Ketu is inviting.', love:'Family karmic themes need compassionate attention and patient healing.', health:'Emotional and psychological wellbeing are the primary health themes of this transit.', finance:'Property and home matters may involve karmic complications requiring patient resolution.', advice:'Allow Ketu to surface and heal old family and emotional patterns. The healing is permanent.', intensity:3 },
    { h:5,  good:false, summary:'Creative and romantic detachment, past-life patterns with children, and unusual spiritual experiences characterise this transit.', career:'Creative work takes on a spiritual or past-life dimension that deepens its meaning.', love:'Past-life romantic connections surface in unusual and sometimes overwhelming ways.', health:'Heart and digestive health need support as emotional patterns are processed.', finance:'Speculative activities carry karmic risk during this spiritually charged transit.', advice:'Allow Ketu to work through your creative and romantic life without resistance. Old patterns need release.', intensity:3 },
    { h:6,  good:true,  summary:'Ketu powerfully dissolves enemies, illness, and debts through spiritual means and past-life virtues.', career:'Workplace opposition dissolves through spiritual strength and karmic resolution.', love:'Difficult relationship dynamics resolve through forgiveness and spiritual understanding.', health:'Karmic healing of chronic health conditions is available through spiritual practice.', finance:'Past-life merit helps dissolve financial obstacles and debts.', advice:'Invoke your spiritual resources against every obstacle. Ketu\'s dissolution power in the 6th is extraordinary.', intensity:4 },
    { h:7,  good:false, summary:'Past-life partnership karma surfaces for healing. Relationships take on a fated, complex, and sometimes burdensome quality.', career:'Business partnerships involve karmic themes that require spiritual discernment.', love:'A relationship feels fated but also burdened — past-life patterns are seeking completion.', health:'Relationship stress needs to be processed through spiritual rather than reactive means.', finance:'Joint financial matters may involve karmic complications requiring patient, spiritual resolution.', advice:'Approach Ketu\'s 7th-house relationships as opportunities for karmic healing and completion.', intensity:3 },
    { h:8,  good:false, summary:'Deep occult studies, past-life trauma healing, and transformative karmic experiences are Ketu\'s 8th-house themes.', career:'Research, healing, and transformative professional work are supported by deep spiritual insight.', love:'Profound emotional depth and past-life healing make this a transformative relationship period.', health:'Past-life health karma surfaces for deep healing. Spiritual health practices are exceptionally effective.', finance:'Ancestral financial karma and inheritance matters carry deep, complex patterns needing resolution.', advice:'Approach every 8th-house Ketu experience as a doorway to the deepest healing available to you.', intensity:4 },
    { h:9,  good:false, summary:'Past-life spiritual paths surface, creating detachment from current belief systems. A profound philosophical questioning period.', career:'International and academic matters have a fated, karmic quality requiring spiritual navigation.', love:'Love with a spiritual or philosophical dimension carries past-life significance.', health:'Spiritual practices and pilgrimage offer the deepest healing available this period.', finance:'Past-life financial karma around education and international matters needs careful attention.', advice:'Question everything you believe with Ketu\'s penetrating clarity. The answers it reveals are eternal.', intensity:3 },
    { h:10, good:false, summary:'Career detachment and karmic professional themes make this a period for inner work rather than outer ambition.', career:'Career direction may be unclear. Reconnect with your deepest dharmic calling.', love:'Professional life and personal relationship need conscious attention and balance.', health:'The separation between professional identity and authentic self is a source of stress. Address it.', finance:'Career-related financial detachment needs to be balanced with practical financial management.', advice:'Ask Ketu\'s question: "What is my deepest work in the world?" The answer transforms everything.', intensity:3 },
    { h:11, good:true,  summary:'Past-life merit produces income and goal achievement through spiritual and non-conventional channels.', career:'Spiritual skills and past-life expertise produce unconventional but genuine professional results.', love:'Community and social connections carry spiritual depth and karmic significance.', health:'Communal spiritual activities are both healing and energising.', finance:'Past-life merits and non-conventional income channels produce surprisingly strong results.', advice:'Trust the unusual financial and social channels that Ketu activates in your 11th house.', intensity:4 },
    { h:12, good:true,  summary:'Ketu in the 12th — its natural placement — produces exceptional spiritual depth, liberation insights, and moksha-oriented awareness.', career:'Creative solitude and spiritual work produce quietly exceptional results.', love:'Solitary spiritual practice creates a profound inner peace that transforms all relationships.', health:'Spiritual retreat, meditation, and complete rest are the most powerful health investments.', finance:'Detachment from material concerns combined with practical basics produces unexpected financial peace.', advice:'Ketu in the 12th is at home. Allow it to guide you into the deepest spiritual work of your life.', intensity:5 },
  ],
};

// ── Mean daily motion (°/day) for approximate duration calculation ─────────────
const MEAN_MOTION = { Sun:1.0, Moon:13.2, Mars:0.524, Mercury:1.38, Jupiter:0.083, Venus:1.21, Saturn:0.033, Rahu:0.053, Ketu:0.053 };
const SIGN_SIZE   = 30; // degrees per sign

// ── Life area synthesis ────────────────────────────────────────────────────────
const LIFE_AREAS = ['career','love','health','finance'];

function synthesizeLifeArea(transits, area) {
  let score = 5; // baseline out of 10
  const notes = [];
  for (const t of transits) {
    if (!t.effect) continue;
    const weight = { Sun:1, Moon:1, Mars:1.5, Mercury:0.8, Jupiter:2, Venus:1.2, Saturn:2, Rahu:1, Ketu:0.8 }[t.planet] || 1;
    if (t.favorable) {
      score += weight * 0.8;
      notes.push({ planet:t.planet, note: t.effect[area], positive:true });
    } else {
      score -= weight * 0.6;
      notes.push({ planet:t.planet, note: t.effect[area], positive:false });
    }
  }
  return { score: Math.min(10, Math.max(1, Math.round(score * 10) / 10)), notes };
}

// ── Controller ─────────────────────────────────────────────────────────────────
async function calculate(req, res) {
  try {
    let { moonSign, dob, tob, lat, lng } = req.body;

    // Resolve natal Moon sign
    let natalMoonSign = moonSign;
    let birthData     = null;

    if (dob && tob && lat !== undefined && lng !== undefined) {
      const natal     = await calculateKundali(dob, tob, parseFloat(lat), parseFloat(lng), 5.5);
      natalMoonSign   = natal.moon_sign;
      birthData       = { lagna: natal.lagna, moonSign: natal.moon_sign, sunSign: natal.sun_sign };
    }

    if (!natalMoonSign || !SIGNS.includes(natalMoonSign)) {
      return res.status(400).json({ error: 'Provide moonSign (e.g. "Aries") or full birth details (dob, tob, lat, lng).' });
    }

    const moonIdx = SIGNS.indexOf(natalMoonSign);

    // Current planetary positions: call calculateKundali with today noon from New Delhi
    const today   = new Date();
    const todayStr= today.toISOString().split('T')[0];
    const currentKundali = await calculateKundali(todayStr, '12:00', 28.6139, 77.2090, 5.5);
    const pp = currentKundali.planetary_positions;

    // Build transit analysis for each planet
    const planets = ['Sun','Moon','Mars','Mercury','Jupiter','Venus','Saturn','Rahu','Ketu'];
    const transits = [];

    for (const planet of planets) {
      const pos     = pp[planet];
      if (!pos) continue;
      const curSign     = pos.sign;
      const curSignIdx  = pos.sign_index;
      const curDegInSign= pos.degree % 30;

      const houseFromMoon = ((curSignIdx - moonIdx + 12) % 12) + 1;
      const favorable     = FAVORABLE[planet]?.has(houseFromMoon) ?? false;

      // Approximate days remaining in sign
      let speed = Math.abs(MEAN_MOTION[planet]);
      if (planet === 'Rahu' || planet === 'Ketu') {
        // Retrograde — moving backward through signs
        const daysInSign = (30 - curDegInSign) / speed; // simplified: degrees until next backward boundary
        // Rahu moves backward: degree decreases → exits sign when deg hits 0
        const daysRemaining = Math.round(curDegInSign / speed);
        transits.push({
          planet, curSign, curSignIdx, houseFromMoon, favorable,
          degree: Math.round(pos.degree * 100) / 100,
          degreeInSign: Math.round(curDegInSign * 100) / 100,
          retrograde: true,
          daysInCurrentSign: Math.round((30 - curDegInSign) / speed + daysRemaining),
          daysUntilNext: daysRemaining > 0 ? daysRemaining : Math.round(30 / speed),
          effect: EFFECTS[planet]?.[houseFromMoon] || null,
          symbol: planet === 'Rahu' ? '☊' : '☋',
        });
      } else {
        const daysUntilNext = Math.round((30 - curDegInSign) / speed);
        transits.push({
          planet, curSign, curSignIdx, houseFromMoon, favorable,
          degree: Math.round(pos.degree * 100) / 100,
          degreeInSign: Math.round(curDegInSign * 100) / 100,
          retrograde: pos.retrograde || false,
          daysUntilNext: daysUntilNext,
          effect: EFFECTS[planet]?.[houseFromMoon] || null,
          symbol: { Sun:'☉', Moon:'☽', Mars:'♂', Mercury:'☿', Jupiter:'♃', Venus:'♀', Saturn:'♄' }[planet] || '✦',
        });
      }
    }

    // Life area synthesis
    const lifeAreas = {};
    for (const area of LIFE_AREAS) {
      lifeAreas[area] = synthesizeLifeArea(transits, area);
    }

    // Overall score
    const overallScore = LIFE_AREAS.reduce((s, a) => s + lifeAreas[a].score, 0) / LIFE_AREAS.length;

    // Most significant transits
    const keyPlanets   = transits.filter(t => ['Jupiter','Saturn'].includes(t.planet));
    const favorable_count   = transits.filter(t => t.favorable).length;
    const unfavorable_count = transits.filter(t => !t.favorable).length;

    // Current date info
    const dateLabel = today.toLocaleDateString('en-IN', { weekday:'long', day:'numeric', month:'long', year:'numeric' });

    res.json({
      natalMoonSign,
      moonSignIndex:  moonIdx,
      moonSignSymbol: SIGN_SYMBOLS[moonIdx],
      dateAnalysed:   todayStr,
      dateLabel,
      birthData,
      transits,
      lifeAreas,
      overallScore:    Math.round(overallScore * 10) / 10,
      favorable_count,
      unfavorable_count,
      keyPlanets,
      summary: `${favorable_count} of 9 planets are in favourable positions from your natal Moon in ${natalMoonSign}. ${
        keyPlanets.filter(t=>t.favorable).map(t=>`${t.planet} in ${t.curSign} (${t.houseFromMoon}th from Moon) is strongly supportive.`).join(' ')
      } ${
        keyPlanets.filter(t=>!t.favorable).map(t=>`${t.planet} in ${t.curSign} (${t.houseFromMoon}th from Moon) brings challenges requiring careful navigation.`).join(' ')
      }`.trim()
    });

  } catch (err) {
    console.error('[Gochara]', err);
    res.status(500).json({ error: 'Calculation failed', details: err.message });
  }
}

module.exports = { calculate };
