// AstroSage reference prices used as originalPrice (market rate).
// Our price = AstroSage × 0.95 (5% lower), rounded to nearest whole number.
const PAATHS = [
  // ── Online Paath Seva (no category) ──────────────────────────────────────
  {
    id: 'hanuman-chalisa-11',
    name: 'Hanuman Chalisa Paath',
    subtitle: '11 Times',
    deity: 'Lord Hanuman',
    icon: '🌅',
    image: '/images/hanuman.png',
    gradient: ['#FF6B35', '#C0392B'],
    duration: '3–4 Hours',
    price: 4749,
    originalPrice: 4999,
    planet: 'Mars',
    description: 'Hanuman Chalisa recited 11 times by our experienced Pandit Ji with full Vedic rituals — flowers, incense, dhoop, and proper puja vidhi.',
    benefits: ['Removes obstacles and enemies', 'Bestows courage and physical strength', 'Protection from evil forces and black magic', 'Fulfils sincere wishes and desires'],
    occasion: 'Hanuman Jayanti, Tuesdays, Saturdays, Mangal Dosha remedies',
    includes: ['Hanuman Chalisa × 11', 'Hanuman Aarti', 'Sankalp in your name & gotra', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'ramayan-paath',
    name: 'Shri Ramayan Paath',
    subtitle: 'Sampurna (Complete)',
    deity: 'Lord Ram',
    icon: '🏹',
    image: '/images/ram.png',
    gradient: ['#1565C0', '#283593'],
    duration: '7–9 Hours',
    price: 14249,
    originalPrice: 14999,
    planet: 'Sun',
    description: 'Complete Shri Ramayan Paath performed by our Pandit Ji as a divine offering — removes all doshas, brings peace, prosperity, and divine blessings of Lord Ram.',
    benefits: ['Removes all types of papa (sins) and doshas', 'Brings peace, prosperity, and happiness', 'Fulfils long-pending wishes and desires', 'Blesses with health, wealth, and harmony'],
    occasion: 'Ram Navami, Vivah, Griha Pravesh, General auspicious occasions',
    includes: ['Sampurna Ramayan recitation', 'Ram Aarti & Prasad', 'Sankalp in your name', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'sunderkand-paath',
    name: 'Sunderkand Paath',
    subtitle: '1 to 11 Times',
    deity: 'Lord Hanuman & Ram',
    icon: '🔥',
    image: '/images/ram-hanuman.png',
    gradient: ['#00897B', '#1B5E20'],
    duration: '1.5–16 Hours',
    price: 10449,
    originalPrice: 10999,
    planet: 'Mars',
    description: 'Sunderkand — the 5th chapter of Ramayan — is the most auspicious paath for removing obstacles, achieving victory, and receiving Hanuman ji\'s direct blessings.',
    benefits: ['Removes all obstacles from life', 'Brings victory in legal, career, and personal matters', 'Protects from enemies and negative forces', 'Bestows courage, faith, and divine protection'],
    occasion: 'Every Tuesday & Saturday, Hanuman Jayanti, Rahu/Ketu dosha remedies',
    includes: ['Sunderkand recitation (1–11 times)', 'Hanuman Aarti', 'Sankalp in your name', 'WhatsApp video proof'],
    variants: [
      { label: '1 Time',   price: 10449, originalPrice: 10999, duration: '1.5 Hours' },
      { label: '3 Times',  price: 28499, originalPrice: 29999, duration: '4 Hours' },
      { label: '5 Times',  price: 45499, originalPrice: 47999, duration: '7 Hours' },
      { label: '7 Times',  price: 60499, originalPrice: 63999, duration: '10 Hours' },
      { label: '11 Times', price: 89999, originalPrice: 94999, duration: '16 Hours' },
    ],
  },
  {
    id: 'maha-mrityunjaya-jaap',
    name: 'Maha Mrityunjaya Jaap',
    subtitle: '51 Mala / 51,000 Jaap',
    deity: 'Lord Shiva (Mrityunjaya)',
    icon: '🔱',
    gradient: ['#6A1B9A', '#4527A0'],
    duration: '1–3 Days',
    price: 10449,
    originalPrice: 10999,
    planet: 'Saturn',
    description: 'Maha Mrityunjaya Jaap — recitation of the powerful death-conquering mantra of Lord Shiva — performed for health, longevity, recovery from illness, and protection from untimely death.',
    benefits: ['Conquer serious illness and health challenges', 'Protect from accidents and untimely death', 'Remove fear, anxiety, and negative energy', 'Bestow long life, health, and vitality'],
    occasion: 'Sade Sati, illness, accident recovery, general protection',
    includes: ['Mahamrityunjaya Jaap', 'Sankalp in your name', 'WhatsApp video clip of sankalp'],
    variants: [
      { label: '51 Mala (~5,500 Jaap)',  price: 10449, originalPrice: 10999,  duration: '1 Day' },
      { label: '51,000 Jaap Anushthan',  price: 94499, originalPrice: 99999, duration: '3–5 Days' },
    ],
  },
  {
    id: 'satya-narayan-katha',
    name: 'Satya Narayan Katha',
    subtitle: 'Sampurna Paath',
    deity: 'Lord Vishnu (Satyanarayana)',
    icon: '🪷',
    gradient: ['#F57F17', '#E65100'],
    duration: '3–4 Hours',
    price: 9509,
    originalPrice: 10010,
    planet: 'Jupiter',
    description: 'Satya Narayan Katha is the most beloved and widely performed puja for home, business, and personal prosperity — bestowing the blessings of Lord Satyanarayana Vishnu.',
    benefits: ['Brings prosperity and happiness to home & family', 'Removes obstacles from business and career', 'Fulfils all righteous wishes and desires', 'Ideal for griha pravesh, marriage, and new beginnings'],
    occasion: 'Purnima, Griha Pravesh, Marriage, New Business, Monthly puja',
    includes: ['Sampurna Satyanarayan Katha (5 Adhyayas)', 'Vishnu Aarti & Prasad', 'Sankalp in your name', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'aditya-hridaya-strot',
    name: 'Aditya Hridaya Strot Paath',
    subtitle: '11 Times',
    deity: 'Surya Devta (Sun God)',
    icon: '☀️',
    gradient: ['#FF8F00', '#FF6F00'],
    duration: '2–3 Hours',
    price: 4749,
    originalPrice: 4999,
    planet: 'Sun',
    description: 'Aditya Hridaya Strot — the divine hymn of the Sun God taught by Sage Agastya to Lord Ram — recited 11 times for success, health, confidence, and solar energy activation.',
    benefits: ['Boosts confidence, willpower, and leadership', 'Strengthens Sun in the horoscope', 'Removes eye and heart-related health issues', 'Brings victory, recognition, and government favour'],
    occasion: 'Sunday, Makar Sankranti, Surya Jayanti, Chhath Puja',
    includes: ['Aditya Hridaya Strot × 11', 'Surya Aarti', 'Sankalp in your name', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'shiv-mans-pooja',
    name: 'Shiv Mans Pooja Paath',
    subtitle: 'Sampurna',
    deity: 'Lord Shiva',
    icon: '🕉️',
    gradient: ['#1A237E', '#0D47A1'],
    duration: '2–3 Hours',
    price: 4749,
    originalPrice: 4999,
    planet: 'Saturn',
    description: 'Shiv Mans Pooja is a meditative mental worship of Lord Shiva — imagining and offering all 16 upachara (services) to Shiva in the mind, as described in the scriptures.',
    benefits: ['Deep spiritual connection with Lord Shiva', 'Removes all mental stress and anxiety', 'Enhances meditation and inner peace', 'Bestows liberation (moksha) energy and divine grace'],
    occasion: 'Shivratri, Mondays, Shravan Month, Pradosh Vrat',
    includes: ['Shiv Mans Pooja complete recitation', 'Shiva Aarti & Abhishek', 'Sankalp in your name', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'shiv-ashtak',
    name: 'Shiv Ashtak Paath',
    subtitle: '11 Times',
    deity: 'Lord Shiva',
    icon: '🌙',
    gradient: ['#00ACC1', '#006064'],
    duration: '2 Hours',
    price: 3449,
    originalPrice: 3649,
    planet: 'Saturn',
    description: 'Shiv Ashtak — eight beautiful Sanskrit shlokas in praise of Lord Shiva — recited 11 times to invoke Shiva\'s blessings for health, peace, and spiritual upliftment.',
    benefits: ['Invokes Lord Shiva\'s direct blessings', 'Removes Shani and Rahu-related problems', 'Bestows health and long life', 'Creates divine peace and positive energy in home'],
    occasion: 'Mondays, Shivratri, Shravan Month, Sade Sati',
    includes: ['Shiv Ashtak × 11', 'Shiva Aarti', 'Sankalp in your name', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'hanuman-ashtak',
    name: 'Hanuman Ashtak Paath',
    subtitle: '11 Times',
    deity: 'Lord Hanuman',
    icon: '🛡️',
    gradient: ['#D84315', '#BF360C'],
    duration: '2 Hours',
    price: 3449,
    originalPrice: 3649,
    planet: 'Mars',
    description: 'Hanuman Ashtak — the eight devotional verses of Lord Hanuman — recited 11 times for courage, protection, and removal of all problems and evil influences.',
    benefits: ['Instant protection from evil and enemies', 'Builds courage and confidence', 'Removes all types of fears', 'Bestows Hanuman ji\'s powerful protection shield'],
    occasion: 'Tuesdays, Saturdays, Hanuman Jayanti, Mangal Dosha',
    includes: ['Hanuman Ashtak × 11', 'Hanuman Aarti', 'Sankalp in your name', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'durga-saptashati',
    name: 'Durga Saptashati Paath',
    subtitle: 'Sampurna (700 Shlokas)',
    deity: 'Maa Durga (Chandika)',
    icon: '🦁',
    gradient: ['#C2185B', '#880E4F'],
    duration: '6–8 Hours',
    price: 4816,
    originalPrice: 5070,
    planet: 'Mars',
    description: 'Durga Saptashati (Chandi Paath) — 700 sacred shlokas of Maa Durga — is the most powerful paath for removing all evils, winning over enemies, and receiving the divine mother\'s supreme blessings.',
    benefits: ['Destroys all negative energies and enemies', 'Removes witchcraft, black magic, and evil eye', 'Blesses with health, wealth, and happiness', 'Grants divine protection of the entire family'],
    occasion: 'Navratri, Durga Ashtami, Dussehra, Black magic removal',
    includes: ['Sampurna Durga Saptashati (700 shlokas)', 'Durga Aarti & Havan', 'Sankalp in your name', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'navgrah-pooja',
    name: 'Navgrah Pooja Paath',
    subtitle: 'All 9 Planets',
    deity: 'Nine Planets (Navgrah)',
    icon: '🌟',
    gradient: ['#4E342E', '#1B0000'],
    duration: '4–5 Hours',
    price: 19951,
    originalPrice: 21002,
    planet: 'All Planets',
    description: 'Navgrah Pooja — simultaneous worship and appeasement of all nine planets — performed for complete astrological balance, removal of planetary doshas, and harmonising all cosmic influences.',
    benefits: ['Pacifies all 9 planetary afflictions at once', 'Removes Sade Sati, Mangal, Rahu-Ketu doshas', 'Brings harmony between all planetary forces', 'Ideal before marriage, business launch, or house entry'],
    occasion: 'Before marriage/griha pravesh, Sade Sati, Janma Nakshatra, New Year',
    includes: ['Navgrah Stotra & Puja vidhi', 'Havan with 9 specific samagri', 'Sankalp in your name', 'WhatsApp video proof'],
    variants: null,
  },

  // ── Graha Shanti & Dosha Nivaran (category: 'graha-dosha') ──────────────
  {
    id: 'shani-graha-shanti',
    name: 'Shani Graha Shanti Puja',
    subtitle: 'Sade Sati & Saturn Dosha Relief',
    deity: 'Lord Shani (Saturn)',
    icon: '🪐',
    gradient: ['#1A237E', '#37474F'],
    duration: '4–5 Hours',
    price: 14249,
    originalPrice: 14999,
    planet: 'Saturn',
    category: 'graha-dosha',
    description: 'Shani Graha Shanti Puja pacifies Saturn — the most feared planet in Vedic astrology. Essential during Sade Sati, Dhaiya, or Shani Mahadasha to reduce hardships and transform Saturn\'s energy into discipline and success.',
    benefits: ['Reduces intensity of Sade Sati & Shani Dhaiya', 'Removes delays, obstacles, and career setbacks', 'Transforms Saturn\'s hardship into spiritual growth', 'Brings relief from chronic illness linked to Saturn'],
    occasion: 'Sade Sati, Shani Dhaiya, Shani Mahadasha/Antardasha, Saturdays',
    includes: ['Shani Stotra & 108-name recitation', 'Shani Yantra energisation', 'Til (sesame) havan', 'Sankalp in your name & gotra', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'rahu-shanti-puja',
    name: 'Rahu Shanti Puja',
    subtitle: 'North Node Appeasement',
    deity: 'Rahu (North Node)',
    icon: '🌑',
    gradient: ['#1B1B2F', '#4A148C'],
    duration: '3–4 Hours',
    price: 10449,
    originalPrice: 10999,
    planet: 'Rahu',
    category: 'graha-dosha',
    description: 'Rahu Shanti Puja pacifies the shadow planet Rahu — responsible for sudden upheavals, confusion, obsessive thinking, and deception. Performed during Rahu Mahadasha or when Rahu is afflicted in the birth chart.',
    benefits: ['Removes Rahu-caused confusion, fear, and anxiety', 'Protects from hidden enemies and deception', 'Reduces effects of Kaal Sarp Dosha (Rahu axis)', 'Brings clarity of mind and stable decision-making'],
    occasion: 'Rahu Mahadasha, Rahu-Ketu transit, Kaal Sarp Dosha, Rahu in 1st/7th/8th house',
    includes: ['Rahu Stotra & beej mantra jaap', 'Rahu Yantra energisation', 'Blue cloth & coconut offering', 'Sankalp in your name & gotra', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'ketu-shanti-puja',
    name: 'Ketu Shanti Puja',
    subtitle: 'South Node Appeasement',
    deity: 'Ketu (South Node)',
    icon: '☄️',
    gradient: ['#4A1942', '#880E4F'],
    duration: '3–4 Hours',
    price: 14246,
    originalPrice: 14996,
    planet: 'Ketu',
    category: 'graha-dosha',
    description: 'Ketu Shanti Puja removes malefic effects of Ketu — the planet of spiritual detachment, sudden losses, and karmic debts. Essential when Ketu causes health issues, accidents, or spiritual confusion in the chart.',
    benefits: ['Removes sudden losses and unexpected setbacks', 'Reduces health issues linked to Ketu (nerves, infections)', 'Balances karmic debts from past lives', 'Brings spiritual clarity and liberation from illusion'],
    occasion: 'Ketu Mahadasha, Ketu transit, accidents/health fears, spiritual seekers',
    includes: ['Ketu Stotra & beej mantra jaap', 'Ketu Yantra energisation', 'Multicolour cloth & camphor offering', 'Sankalp in your name & gotra', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'kaal-sarp-dosha-puja',
    name: 'Kaal Sarp Dosha Puja',
    subtitle: 'Complete 12-Type Dosha Nivaran',
    deity: 'Lord Shiva & Nag Devta',
    icon: '🐍',
    gradient: ['#1B4332', '#0F3460'],
    duration: '5–6 Hours',
    price: 14246,
    originalPrice: 14996,
    planet: 'Rahu–Ketu',
    category: 'graha-dosha',
    description: 'Kaal Sarp Dosha forms when all 7 planets are hemmed between Rahu and Ketu, causing repeated failures, health crises, and blocked destiny. Our Pandit Ji performs complete dosha nivaran with specific mantras for all 12 Kaal Sarp types.',
    benefits: ['Removes all 12 types of Kaal Sarp Dosha', 'Unlocks stalled success in career, marriage, and finances', 'Removes recurring nightmares and serpent-related fears', 'Clears delayed marriage and childbirth obstacles'],
    occasion: 'All planets between Rahu-Ketu in chart, repeated failures, marriage delays, persistent bad luck',
    includes: ['Kaal Sarp type identification & Sankalp', 'Nag Devta puja & Shiva abhishek', 'Sarpa Suktam recitation', 'Specific mantra per dosha type', 'Sankalp in your name & gotra', 'WhatsApp video proof'],
    variants: [
      { label: 'Standard (1 Type)',       price: 14246, originalPrice: 14996, duration: '5–6 Hours' },
      { label: 'Complete (All 12 Types)', price: 28499, originalPrice: 29999, duration: '1 Full Day' },
    ],
  },
  {
    id: 'pitra-dosha-nivaran',
    name: 'Pitra Dosha Nivaran Puja',
    subtitle: 'Ancestral Karma Removal',
    deity: 'Pitra Devta & Lord Vishnu',
    icon: '🪔',
    gradient: ['#7B3F00', '#4E342E'],
    duration: '5–6 Hours',
    price: 48449,
    originalPrice: 50999,
    planet: 'Saturn',
    category: 'graha-dosha',
    description: 'Pitra Dosha (ancestral debt) occurs when departed ancestors have unresolved wishes or improper last rites — causing repeated family problems, health crises, and childbirth difficulties across generations. This puja frees both the living and the departed souls.',
    benefits: ['Frees ancestors from unsatisfied desires and unrest', 'Removes generational health and family problems', 'Resolves childbirth difficulties and progeny issues', 'Brings lasting peace to family and departed souls'],
    occasion: 'Pitru Paksha (Shraddh), repeated family problems, childbirth difficulties, Saturn in 9th house',
    includes: ['Pitra Tarpan (water offering to ancestors)', 'Vishnu Sahasranaam recitation', 'Pind Daan arrangement', 'Til & sesame havan', 'Sankalp in your name & gotra', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'mangal-dosha-nivaran',
    name: 'Mangal Dosha Nivaran Puja',
    subtitle: 'Mars Dosha for Marriage',
    deity: 'Lord Mangal (Mars) & Lord Hanuman',
    icon: '🌋',
    gradient: ['#B71C1C', '#7F0000'],
    duration: '4–5 Hours',
    price: 13300,
    originalPrice: 14000,
    planet: 'Mars',
    category: 'graha-dosha',
    description: 'Mangal Dosha (Kuja Dosha) is the most feared marriage-related dosha in India — formed when Mars is in 1st, 4th, 7th, 8th, or 12th house. This puja permanently reduces dosha intensity and removes obstacles to finding and keeping a compatible life partner.',
    benefits: ['Permanently reduces Mangal Dosha intensity', 'Removes marriage delays and compatibility hurdles', 'Protects married life from conflicts and separation', 'Boosts career confidence and physical vitality'],
    occasion: 'Before marriage, kundali matching issues, Mars in 1/4/7/8/12 house, Mangal Mahadasha',
    includes: ['Mangal Stotra & 108-name archana', 'Red cloth & masoor dal offering', 'Hanuman Chalisa recitation', 'Mangal Yantra energisation', 'Sankalp in your name & gotra', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'surya-graha-shanti',
    name: 'Surya Graha Shanti Puja',
    subtitle: 'Sun Appeasement & Confidence',
    deity: 'Lord Surya (Sun God)',
    icon: '☀️',
    gradient: ['#E65100', '#BF360C'],
    duration: '3–4 Hours',
    price: 10449,
    originalPrice: 10999,
    planet: 'Sun',
    category: 'graha-dosha',
    description: 'Surya Graha Shanti Puja pacifies the Sun — the king of planets — for those suffering from poor confidence, father-related conflicts, career stagnation, or eye/heart health problems. Performed at sunrise with Aditya Hridaya and specific Surya mantras.',
    benefits: ['Boosts confidence, authority, and leadership', 'Removes conflicts with father and government', 'Relieves Sun-related health issues (eyes, heart)', 'Strengthens Sun in the horoscope for career growth'],
    occasion: 'Surya Mahadasha/Antardasha, Sun in debilitation, Sundays, Makar Sankranti',
    includes: ['Surya Stotra & Aditya Hridayam recitation', 'Surya Yantra energisation', 'Red flower & wheat offering', 'Sankalp in your name & gotra', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'chandra-graha-shanti',
    name: 'Chandra Graha Shanti Puja',
    subtitle: 'Moon Appeasement & Mental Peace',
    deity: 'Lord Chandra (Moon God)',
    icon: '🌙',
    gradient: ['#37474F', '#546E7A'],
    duration: '3–4 Hours',
    price: 10449,
    originalPrice: 10999,
    planet: 'Moon',
    category: 'graha-dosha',
    description: 'Chandra Graha Shanti Puja pacifies the Moon — the planet of mind, emotions, and mother. Ideal when Moon is afflicted causing anxiety, insomnia, emotional instability, or troubled relationship with mother. Performed on Purnima with white flowers and milk offering.',
    benefits: ['Brings mental peace, emotional stability, and clarity', 'Removes insomnia, anxiety, and mood disorders', 'Heals relationship with mother and female figures', 'Strengthens intuition, memory, and emotional intelligence'],
    occasion: 'Chandra Mahadasha, Moon in Scorpio or debilitation, Mondays, Purnima',
    includes: ['Chandra Stotra & 108-name archana', 'Chandra Yantra energisation', 'White flower & milk offering', 'Sankalp in your name & gotra', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'budh-graha-shanti',
    name: 'Budh Graha Shanti Puja',
    subtitle: 'Mercury Appeasement & Intelligence',
    deity: 'Lord Budh (Mercury)',
    icon: '🌿',
    gradient: ['#1B5E20', '#2E7D32'],
    duration: '3–4 Hours',
    price: 14246,
    originalPrice: 14996,
    planet: 'Mercury',
    category: 'graha-dosha',
    description: 'Budh Graha Shanti Puja pacifies Mercury — the planet of intellect, communication, and business. When afflicted, Mercury causes speech problems, business losses, poor decision-making, and skin issues. This puja activates sharp intellect and communication skills.',
    benefits: ['Sharpens intellect, memory, and analytical skills', 'Removes speech disorders and communication blocks', 'Attracts business success and negotiation ability', 'Relieves Mercury-related skin and nervous system issues'],
    occasion: 'Budh Mahadasha, Mercury retrograde effects, Wednesdays, business problems',
    includes: ['Budh Stotra & beej mantra jaap', 'Budh Yantra energisation', 'Green cloth & moong dal offering', 'Sankalp in your name & gotra', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'guru-graha-shanti',
    name: 'Guru Graha Shanti Puja',
    subtitle: 'Jupiter Appeasement & Wisdom',
    deity: 'Lord Brihaspati (Jupiter)',
    icon: '👑',
    gradient: ['#F57F17', '#E65100'],
    duration: '4–5 Hours',
    price: 14246,
    originalPrice: 14996,
    planet: 'Jupiter',
    category: 'graha-dosha',
    description: 'Guru Graha Shanti Puja pacifies Jupiter — the most benefic planet and Guru of the gods. When afflicted, Jupiter causes financial mismanagement, poor judgement, marital discord, and blocked spiritual growth. This puja restores Jupiter\'s wisdom and blessings in full.',
    benefits: ['Restores wisdom, good judgement, and spiritual guidance', 'Removes obstacles in marriage, wealth, and higher education', 'Attracts blessings of teachers, mentors, and elders', 'Brings dharmic success, children\'s wellbeing, and abundance'],
    occasion: 'Guru Mahadasha, Jupiter in Capricorn (debilitation), Thursdays, marriage delays',
    includes: ['Brihaspati Stotra & Vishnu Sahasranaam', 'Guru Yantra energisation', 'Yellow flower & chana dal offering', 'Sankalp in your name & gotra', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'shukra-graha-shanti',
    name: 'Shukra Graha Shanti Puja',
    subtitle: 'Venus Appeasement & Love',
    deity: 'Lord Shukra (Venus)',
    icon: '🌹',
    gradient: ['#880E4F', '#6A1B9A'],
    duration: '3–4 Hours',
    price: 13300,
    originalPrice: 14000,
    planet: 'Venus',
    category: 'graha-dosha',
    description: 'Shukra Graha Shanti Puja pacifies Venus — the planet of love, beauty, luxury, and relationships. When afflicted, Venus causes relationship breakdowns, lack of comfort, poor artistic expression, and reproductive health issues. This puja activates Shukra\'s full grace.',
    benefits: ['Restores love, romance, and marital harmony', 'Attracts luxury, comfort, and material pleasures', 'Removes relationship breakdowns and divorce fears', 'Heals reproductive health and hormonal balance'],
    occasion: 'Shukra Mahadasha, Venus in Virgo (debilitation), Fridays, relationship troubles',
    includes: ['Shukra Stotra & beej mantra jaap', 'Shukra Yantra energisation', 'White flower & ghee offering', 'Sankalp in your name & gotra', 'WhatsApp video proof'],
    variants: null,
  },

  // ── Deity & Special Pujas (category: 'deity-puja') ───────────────────────
  {
    id: 'mahalakshmi-puja',
    name: 'Mahalakshmi Puja',
    subtitle: 'Wealth & Prosperity Blessing',
    deity: 'Goddess Mahalakshmi',
    icon: '🪷',
    gradient: ['#B8860B', '#8B4513'],
    duration: '3–4 Hours',
    price: 10454,
    originalPrice: 11005,
    planet: 'Venus',
    category: 'deity-puja',
    description: 'Mahalakshmi Puja invokes the direct blessings of Goddess Lakshmi — the divine bestower of wealth, beauty, and abundance. Performed with lotus flowers, turmeric, and gold-coloured samagri for maximum Lakshmi energy activation.',
    benefits: ['Removes financial blocks and recurring debt', 'Attracts wealth, business success, and abundance', 'Brings harmony and luxury into home', 'Activates Lakshmi energy on Fridays and auspicious days'],
    occasion: 'Fridays, Diwali, Akshaya Tritiya, Navratri, new business launch',
    includes: ['Lakshmi Stotra & Ashta Lakshmi Aarti', 'Lotus & turmeric offering', 'Shodashopchara (16-step) puja', 'Sankalp in your name & gotra', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'ashta-lakshmi-puja',
    name: 'Ashta Lakshmi Puja',
    subtitle: '8 Forms of Goddess Lakshmi',
    deity: 'Ashta Lakshmi (8 Manifestations)',
    icon: '🌸',
    gradient: ['#C5870A', '#7B2D00'],
    duration: '4–5 Hours',
    price: 10449,
    originalPrice: 10999,
    planet: 'Venus',
    category: 'deity-puja',
    description: 'Ashta Lakshmi Puja worships all 8 manifestations of Goddess Lakshmi — Adi Lakshmi, Dhana Lakshmi, Dhanya Lakshmi, Gaja Lakshmi, Santana Lakshmi, Veera Lakshmi, Vijaya Lakshmi, and Vidya Lakshmi — granting 8-fold prosperity across all life domains.',
    benefits: ['Activates all 8 forms of prosperity simultaneously', 'Grants wealth, grain, family, courage, and victory', 'Removes poverty, debt, and lack in every area of life', 'Most powerful Lakshmi puja for complete abundance'],
    occasion: 'Varalakshmi Vrat, Diwali, Navratri, Fridays, major wealth goals',
    includes: ['Ashta Lakshmi Stotra (8-form worship)', '8 separate samagri sets for each form', 'Lotus & champa flower offering', 'Sankalp in your name & gotra', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'maha-vishnu-puja',
    name: 'Maha Vishnu Puja',
    subtitle: 'Divine Protection & Dharma',
    deity: 'Lord Vishnu (Narayana)',
    icon: '🐚',
    gradient: ['#0D3B8E', '#1565C0'],
    duration: '4–5 Hours',
    price: 14249,
    originalPrice: 14999,
    planet: 'Jupiter',
    category: 'deity-puja',
    description: 'Maha Vishnu Puja invokes Lord Vishnu — the Preserver of the Universe — for divine protection, dharmic success, and family harmony. Performed with Tulsi, Panchamrit abhishek, and Vishnu Sahasranaam recitation for full blessings.',
    benefits: ['Grants divine protection from all negativity and enemies', 'Removes obstacles in dharmic work, career, and business', 'Brings harmony, stability, and peace to family life', 'Ideal before major life decisions or new beginnings'],
    occasion: 'Ekadashi, Vaikunta Ekadashi, Vishnu Jayanti, Griha Pravesh, Vivah',
    includes: ['Vishnu Sahasranaam recitation', 'Panchamrit abhishek with Tulsi', 'Sudarshana Chakra mantra', 'Sankalp in your name & gotra', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'santan-gopal-puja',
    name: 'Santan Gopal Puja',
    subtitle: 'Blessings for Progeny & Child Protection',
    deity: 'Lord Santan Gopal (Bal Krishna)',
    icon: '🦚',
    gradient: ['#1B5E20', '#0288D1'],
    duration: '5–6 Hours',
    price: 90278,
    originalPrice: 95030,
    planet: 'Jupiter',
    category: 'deity-puja',
    description: 'Santan Gopal Puja is performed for couples seeking a child, those with repeated pregnancy loss, or parents seeking protection for an unborn or newborn child. Lord Santan Gopal (the child form of Krishna) is worshipped with deep devotion for the gift of progeny.',
    benefits: ['Blesses childless couples with the gift of a child', 'Removes obstacles causing repeated miscarriage or pregnancy loss', 'Protects the health and future of an unborn child', 'Ensures safe delivery and healthy, intelligent progeny'],
    occasion: 'Childless couples, repeated pregnancy loss, pregnancy protection, Janmashtami',
    includes: ['Santan Gopal Stotra & 108-name archana', 'Panchamrit abhishek of Bal Krishna', 'Yellow flowers & butter offering', 'Sankalp in your name & gotra', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'namkaran-puja',
    name: 'Namkaran Puja',
    subtitle: 'Sacred Naming Ceremony for Newborn',
    deity: 'Lord Ganesha & Goddess Saraswati',
    icon: '🐘',
    gradient: ['#E91E8C', '#9C27B0'],
    duration: '2–3 Hours',
    price: 6650,
    originalPrice: 7001,
    planet: 'Moon',
    category: 'deity-puja',
    description: 'Namkaran Puja is the sacred Hindu naming ceremony performed for a newborn — traditionally on the 11th day after birth. Our Pandit Ji performs the complete vidhi including Jatakarma, Nakshatr Pooja, and the formal name announcement under divine blessings.',
    benefits: ['Gives the child an auspicious name aligned with birth Nakshatra', 'Invokes divine blessings for the child\'s long, healthy life', 'Removes any birth-related doshas or inauspicious yoga', 'Marks a blessed beginning for the child\'s life journey'],
    occasion: '11th day after birth, or any auspicious day chosen by family',
    includes: ['Jatakarma & Nakshatra Puja', 'Ganesha & Saraswati invocation', 'Name announcement ceremony', 'Sankalp in your name & gotra', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'birthday-chiranjeevi-puja',
    name: 'Janma Din Puja',
    subtitle: 'Birthday Blessing Ceremony',
    deity: 'Ashta Chiranjeevi & Ishta Devta',
    icon: '🌟',
    gradient: ['#FF6F00', '#AD1457'],
    duration: '2–3 Hours',
    price: 10449,
    originalPrice: 10999,
    planet: 'Sun',
    category: 'deity-puja',
    description: 'Janma Din Puja (Birthday Puja) is performed on one\'s birthday to receive blessings from the Ashta Chiranjeevi (8 immortal beings) and one\'s Ishta Devta. It neutralises the negative effects of the Solar Return, removes Janma Nakshatra doshas, and sets a positive tone for the year ahead.',
    benefits: ['Neutralises malefic effects of the solar return year', 'Removes Janma Nakshatra and birth-day doshas', 'Bestows health, success, and protection for the year ahead', 'Receives blessings of all 8 immortal Chiranjeevi beings'],
    occasion: 'Birthday (Janma Din), Solar Return, Janma Nakshatra day',
    includes: ['Ashta Chiranjeevi invocation', 'Ishta Devta archana', 'Ayush Havan (longevity ritual)', 'Sankalp in your name & gotra', 'WhatsApp video proof'],
    variants: null,
  },

  // ── Vastu Pooja (category: 'vastu') ──────────────────────────────────────
  {
    id: 'vastu-shanti-havan',
    name: 'Vastu Shanti Havan',
    subtitle: 'Complete Dosha Nivaran',
    deity: 'Vastu Purusha & Panch Devta',
    icon: '🔥',
    gradient: ['#B45309', '#78350F'],
    duration: '3–4 Hours',
    price: 14249,
    originalPrice: 14999,
    planet: 'All Planets',
    category: 'vastu',
    description: 'A complete Vastu Shanti Havan performed by our expert Pandit Ji to remove all Vastu doshas from your home or office. Includes Vastu Purusha Mandala mantras, Panch Devta worship, and full havan with Vedic samagri.',
    benefits: ['Removes all Vastu doshas from home or office', 'Brings peace, health, and financial prosperity', 'Neutralises all negative cosmic energies', 'Restores positive Prana flow through the space'],
    occasion: 'Shifting to new home, after major renovation, persistent family problems',
    includes: ['Vastu Purusha Mandala Puja', 'Panch Devta Havan', 'Vastu Stotra recitation', 'Sankalp in your name', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'griha-pravesh-puja',
    name: 'Griha Pravesh Puja',
    subtitle: 'Housewarming Ceremony',
    deity: 'Lord Ganesha & Vastu Devta',
    icon: '🪔',
    gradient: ['#7C3AED', '#4C1D95'],
    duration: '4–5 Hours',
    price: 18999,
    originalPrice: 19999,
    planet: 'Jupiter',
    category: 'vastu',
    description: 'Griha Pravesh is the sacred housewarming ceremony performed before entering a new home. Our Pandit Ji conducts the complete puja with Ganesha puja, Vastu Shanti, Navagraha worship, and Griha Devta Havan — ensuring divine blessings for the new home.',
    benefits: ['Invites divine blessings into the new home', 'Removes any construction-related doshas', 'Ensures harmony, health, and prosperity', 'Auspicious beginning for family life in new home'],
    occasion: 'Moving into a new house or apartment, after construction completion',
    includes: ['Ganesha Puja & Kalash Sthapana', 'Vastu Shanti Havan', 'Navagraha Worship', 'Griha Devta Puja', 'Sankalp in your name', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'bhoomi-puja',
    name: 'Bhoomi Puja',
    subtitle: 'Land Worship Before Construction',
    deity: 'Bhoomi Devi (Mother Earth)',
    icon: '🌱',
    gradient: ['#065F46', '#064E3B'],
    duration: '2–3 Hours',
    price: 9449,
    originalPrice: 9999,
    planet: 'Saturn',
    category: 'vastu',
    description: 'Bhoomi Puja is the sacred worship of Mother Earth (Bhoomi Devi) performed before the first brick is laid. It seeks divine permission from the earth and ensures a blessed, dosha-free construction from the very foundation.',
    benefits: ['Seeks divine permission from Mother Earth', 'Removes underground Vastu doshas', 'Ensures smooth construction without accidents', 'Blesses the land for health and prosperity of future occupants'],
    occasion: 'Before construction begins on any plot, house, or commercial building',
    includes: ['Bhoomi Devi Puja', 'Vastu Purusha Sthapana', 'Panch Tattva worship', 'Sankalp in your name', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'vastu-dosh-nivaran',
    name: 'Vastu Dosh Nivaran Puja',
    subtitle: 'Targeted Dosha Removal',
    deity: 'Vastu Purusha',
    icon: '⚡',
    gradient: ['#DC2626', '#991B1B'],
    duration: '2–3 Hours',
    price: 9449,
    originalPrice: 9999,
    planet: 'All Planets',
    category: 'vastu',
    description: 'Targeted Vastu Dosh Nivaran Puja for correcting specific Vastu defects — such as toilet in northeast, south-facing entrance, or kitchen in wrong direction — without any physical construction changes.',
    benefits: ['Corrects specific Vastu defects energetically', 'No demolition or construction required', 'Removes effects of toilet in NE, S entrance, etc.', 'Brings immediate relief from Vastu-related problems'],
    occasion: 'Specific Vastu dosha identified by expert, persistent problems in one area of life',
    includes: ['Vastu Dosh diagnosis mantras', 'Targeted remedy puja', 'Vastu Yantra energisation', 'Sankalp in your name', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'office-vastu-puja',
    name: 'Office / Shop Vastu Puja',
    subtitle: 'Business Vastu Harmony',
    deity: 'Lord Kubera & Vastu Devta',
    icon: '🏢',
    gradient: ['#1D4ED8', '#1E3A8A'],
    duration: '3–4 Hours',
    price: 14249,
    originalPrice: 14999,
    planet: 'Mercury',
    category: 'vastu',
    description: 'Office Vastu Puja aligns your business premises with cosmic energies to attract wealth, clients, and success. Our Pandit Ji performs Kubera Puja, Vastu Shanti, and Lakshmi worship for maximum business prosperity.',
    benefits: ['Attracts wealth, clients, and business growth', 'Removes obstacles in business and career', 'Improves employee harmony and productivity', 'Activates Kubera energy for financial abundance'],
    occasion: 'Opening a new office or shop, business facing losses, moving to new business premises',
    includes: ['Kubera Puja & Vastu Shanti', 'Lakshmi worship', 'Vastu Mandala consecration', 'Sankalp in your name', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'vastu-kalash-sthapana',
    name: 'Vastu Kalash Sthapana',
    subtitle: 'Home Energisation',
    deity: 'Vastu Devta & Panch Tattva',
    icon: '🏺',
    gradient: ['#D97706', '#B45309'],
    duration: '1–2 Hours',
    price: 4749,
    originalPrice: 4999,
    planet: 'Moon',
    category: 'vastu',
    description: 'Vastu Kalash Sthapana is a lighter, affordable Vastu puja to energise your home with positive cosmic vibrations. A copper Kalash is consecrated with Ganga Jal, herbs, and Vastu mantras and placed in the northeast corner.',
    benefits: ['Fills home with positive cosmic energy', 'Ideal affordable option for general Vastu correction', 'Activates the sacred northeast (Ishaan) corner', 'Quick and powerful — results felt immediately'],
    occasion: 'General Vastu improvement, new month / Navratri / Purnima, small home corrections',
    includes: ['Copper Kalash consecration', 'Vastu Mantra chanting', 'Panch Tattva puja', 'Sankalp in your name', 'WhatsApp video proof'],
    variants: null,
  },
  {
    id: 'plot-bhoomi-shanti',
    name: 'Plot / Zameen Puja',
    subtitle: 'Agricultural & Empty Land',
    deity: 'Bhoomi Devi & Vayu Devta',
    icon: '🌾',
    gradient: ['#166534', '#14532D'],
    duration: '2–3 Hours',
    price: 6649,
    originalPrice: 6999,
    planet: 'Saturn',
    category: 'vastu',
    description: 'Plot Puja (Zameen Puja or Bhoomi Shanti) is performed for agricultural land, empty plots, or inherited land to remove any negative energies, ancestral doshas, or underground Vastu defects — blessing the land for prosperity.',
    benefits: ['Removes ancestral or inherited land doshas', 'Clears negative history of the land', 'Blesses agricultural land for good harvest', 'Ideal before selling or building on inherited land'],
    occasion: 'Inherited land, agricultural land blessing, empty plot before sale or construction',
    includes: ['Bhoomi Shanti puja', 'Ancestral dosha removal mantras', 'Land energisation rituals', 'Sankalp in your name', 'WhatsApp video proof'],
    variants: null,
  },
];

const crypto  = require('crypto');
const { getRazorpay } = require('../services/razorpay');

// ── Bookings (in-memory for now) ──────────────────────────────────────────
const bookings = [];
let bookingCounter = 1000;

function resolvePrice(paath, variant) {
  if (paath.variants && variant) {
    const v = paath.variants.find(v => v.label === variant);
    if (v) return v.price;
  }
  return paath.price;
}

function getPaaths(req, res) {
  const { category } = req.query;
  const paaths = category
    ? PAATHS.filter(p => p.category === category)
    : PAATHS.filter(p => !p.category); // default: return only generic paaths
  res.json({ paaths });
}

// Step 1 — create a Razorpay order (called when user submits the booking form)
async function createOrder(req, res) {
  try {
    const { paathId, name, mobile, date, variant } = req.body;
    if (!paathId || !name || !mobile || !date) {
      return res.status(400).json({ error: 'paathId, name, mobile, and date are required' });
    }
    const paath = PAATHS.find(p => p.id === paathId);
    if (!paath) return res.status(404).json({ error: 'Paath not found' });

    const price = resolvePrice(paath, variant);
    const razorpay = getRazorpay();

    const order = await razorpay.orders.create({
      amount:   price * 100,
      currency: 'INR',
      receipt:  `pooja_${Date.now()}`,
      notes:    { paathId, name, mobile },
    });

    res.json({
      order_id: order.id,
      amount:   order.amount,
      currency: order.currency,
      key:      process.env.RAZORPAY_KEY_ID,
    });
  } catch (err) {
    if (err.message === 'Razorpay credentials not configured') {
      return res.status(503).json({ error: 'Payment gateway not configured. Please set RAZORPAY_KEY_ID and RAZORPAY_KEY_SECRET in .env' });
    }
    console.error('createOrder error:', err);
    res.status(500).json({ error: 'Failed to create payment order' });
  }
}

// Step 2 — verify Razorpay payment and confirm the booking
function verifyAndBook(req, res) {
  try {
    const {
      razorpay_order_id, razorpay_payment_id, razorpay_signature,
      paathId, name, mobile, date, timeSlot, gotra, intention, variant,
    } = req.body;

    if (!razorpay_order_id || !razorpay_payment_id || !razorpay_signature) {
      return res.status(400).json({ error: 'Payment details missing' });
    }

    const secret = process.env.RAZORPAY_KEY_SECRET;
    if (!secret || secret === 'your_razorpay_secret') {
      return res.status(503).json({ error: 'Payment gateway not configured' });
    }

    // Verify HMAC signature
    const hmac = crypto.createHmac('sha256', secret);
    hmac.update(`${razorpay_order_id}|${razorpay_payment_id}`);
    const digest = hmac.digest('hex');
    if (digest !== razorpay_signature) {
      return res.status(400).json({ error: 'Payment verification failed — invalid signature' });
    }

    const paath = PAATHS.find(p => p.id === paathId);
    if (!paath) return res.status(404).json({ error: 'Paath not found' });

    const price = resolvePrice(paath, variant);
    const refId = `AVP${++bookingCounter}`;

    const booking = {
      refId, paathId, paathName: paath.name, variant: variant || null,
      name, mobile, date, timeSlot: timeSlot || 'Morning (5:30 – 8:00 AM)',
      gotra: gotra || '', intention: intention || '',
      price, status: 'Confirmed',
      razorpay_order_id, razorpay_payment_id,
      createdAt: new Date().toISOString(),
    };
    bookings.push(booking);

    console.log(`[PoojaBooking] Payment confirmed — ${refId} | ${paath.name} | ${name} (${mobile}) | ₹${price}`);

    res.json({ success: true, refId, booking });
  } catch (err) {
    console.error('verifyAndBook error:', err);
    res.status(500).json({ error: 'Booking failed after payment' });
  }
}

module.exports = { getPaaths, createOrder, verifyAndBook };
